# (샘플) 파이썬 - 벡터와 행렬선언
> 작성완료 

- toc: true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

### 벡터만들기

#### `0`으로 가득찬 벡터만들기 

`-` 리스트를 활용

In [1]:
[0]*10

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

`-` 넘파이로 만들기

In [2]:
import numpy as np 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

`-` 이미 정의된 다른 벡터를 활용

In [3]:
a=[1]*10
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 벡터의 원소를 랜덤변수의 실현치로 초기화 

`-` 정규분포 

In [6]:
np.random.normal(loc=0,scale=1,size=10)

array([ 0.18593842,  0.49912885,  0.19033439,  1.25723443,  0.2841971 ,
       -0.41081701, -2.67312962,  0.38790871,  0.90058517,  0.61180291])

`–` 유니폼

In [7]:
np.random.uniform(low=0,high=1,size=10)

array([0.90520095, 0.33190157, 0.75969148, 0.60467567, 0.419799  ,
       0.57242601, 0.98146429, 0.87479678, 0.62021425, 0.78307091])

#### `1:10`과 같은 수열 만들기 

`–` `range()`와 `list()`이용 

In [8]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

`–` `np.arange()`

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3,10) ## [3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

`–` `np.linspace()`

In [12]:
np.linspace(start=2.0, stop=3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [13]:
np.linspace(start=2.0, stop=3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [14]:
np.linspace(start=2.0, stop=3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

#### 데이터형변환

`–` 데이터형을 `float`으로 하려면 아래와 같이 하면 된다. 

In [15]:
np.arange(10, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

`-` 이미 만들어진 자료의 데이터 변환을 하려면 아래와 같이 `.astype()`을 하면 된다. 

In [16]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### 매트릭스