# (노트) 순환신경망

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [빅데이터분석]

### 강인공지능(AGI)? 

`-` https://zdnet.co.kr/view/?no=20160622145838

> 김 교수는 “인공지능은 사람보다 훌륭한 강인공지능과 사람보다 못하지만 사람에게 도움이 되는 약인공지능으로 나눌 수 있다”며 “90년대 후반부터 부활한 인공지능은 기계학습의 발전, 데이터로부터의 지식 추출, 빠른 컴퓨터와 다양한 데이터로 새로운 지식을 창출할 수 있는 방향으로 발전했다”고 설명했다.
또 “사람들은 지식의 오류를 인정하는 약인공지능으로 갔고 약인공지능은 확률, 통계 이론을 중심으로 발전하고 있다”고 덧붙였다.
강인공지능은 영화 터미네이터, 아이로봇에 나오는 로봇처럼 사람의 능력을 뛰어넘는 인공지능을 의미한다. 사람보다 강한 체력과 지능으로 인간이 못하는 일을 척척 해내는 인공지능이다.
반면 약인공지능은 바이센티니얼맨이나 A.I.에 나오는 로봇으로 감성 등 인간 고유의 특성을 넘을 수 없고 오류가 나기도 하지만 뛰어난 연산능력으로 사람의 업무에 도움을 주는 인공지능이다.
인공지능 초기에는 강인공지능이 대세를 이뤘다. 튜링테스트를 시작으로 초기의 자연어 처리 기능이 등장했지만 강인공지능은 커진 기대감을 충족시키지 못하고 큰 실망감을 안기며 사라졌다. 김 교수는 “70년대 중반부터 과학기술 투자 펀드가 인공지능 연구 지원을 끊었는데 이유는 결과물이 없었기 때문”이라고 설명했다.


`-` GPT3를 기점으로 언어모델의 발전이 눈부심 $\to$ AGI의 출현이라 말하는 사람도 있음 

### Import 

In [1]:
from fastai.text.all import *
import torch 
import numpy as np

### 실제활용예시

In [2]:
path = untar_data(URLs.IMDB)

In [3]:
files = get_text_files(path)
files

(#100002) [Path('/home/cgb3/.fastai/data/imdb/train/neg/7473_4.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/11965_4.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/11897_3.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/9582_4.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/2709_2.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/7593_2.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/3936_2.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/12323_4.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/576_3.txt'),Path('/home/cgb3/.fastai/data/imdb/train/neg/12303_1.txt')...]

- 경로안에 train, test, unsup이라는 폴더가 있는데, 이 폴더들내의 모든 텍스트파일을 가져오라. 

In [4]:
dls=DataBlock(blocks=TextBlock.from_folder(path,is_lm=True),get_items=get_text_files,splitter=RandomSplitter(0.1)).dataloaders(source=path, bs=128, seq_len=80)

- `is_lm`: 문장생성을 위해서는 is_lm=True로 설정해야함.   
- splitter: train / val 으로 나눔 

In [5]:
dls.show_batch()

,text,text_
0,"xxbos xxmaj the volleyball genre is strangely overlooked by most screenwriters . xxmaj thankfully , highly acclaimed director xxmaj nelson mccormick has brought us the second best volleyball movie of all time ( rated lower than xxmaj side xxmaj out and higher than , well , umm ) . xxmaj however , do n't let the cover of this movie xxunk you . xxmaj kill xxmaj shot stars up and coming star xxmaj koji as a modern day xxmaj sherlock","xxmaj the volleyball genre is strangely overlooked by most screenwriters . xxmaj thankfully , highly acclaimed director xxmaj nelson mccormick has brought us the second best volleyball movie of all time ( rated lower than xxmaj side xxmaj out and higher than , well , umm ) . xxmaj however , do n't let the cover of this movie xxunk you . xxmaj kill xxmaj shot stars up and coming star xxmaj koji as a modern day xxmaj sherlock xxmaj"
1,". xxmaj on xxmaj operative , you can breeze through in a few hours . xxmaj on xxmaj agent , a few weeks . xxmaj on xxmaj double xxmaj oh , a few months . xxmaj the difficulty level can be changed for each individual mission . xxmaj garnering high scores on missions will unlock gold and platinum awards and effect features such as vehicle upgrades and the skimpy outfits the xxmaj bond girls wear . xxmaj some missions can","xxmaj on xxmaj operative , you can breeze through in a few hours . xxmaj on xxmaj agent , a few weeks . xxmaj on xxmaj double xxmaj oh , a few months . xxmaj the difficulty level can be changed for each individual mission . xxmaj garnering high scores on missions will unlock gold and platinum awards and effect features such as vehicle upgrades and the skimpy outfits the xxmaj bond girls wear . xxmaj some missions can be"
2,"short duration . xxmaj the movie follows an illegal immigrant , xxmaj freddy , who is trying to make his way in the country as he struggles to deal with intolerant locals . xxmaj he supports a family back home and wants them to join him in xxmaj buenos xxmaj aires when he saves up enough money . \n\n xxmaj the film delivers a powerful message about xenophobia and poverty in xxmaj south xxmaj america in the modern era .","duration . xxmaj the movie follows an illegal immigrant , xxmaj freddy , who is trying to make his way in the country as he struggles to deal with intolerant locals . xxmaj he supports a family back home and wants them to join him in xxmaj buenos xxmaj aires when he saves up enough money . \n\n xxmaj the film delivers a powerful message about xenophobia and poverty in xxmaj south xxmaj america in the modern era . xxmaj"
3,"a secondary plot point . xxmaj there 's a ghetto kid who has too much xxunk what , was i surprised ? xxmaj and guess what ? xxmaj they all want to become big stars , finding fame and fortune , and they 'd all be willing to crawl over their own mothers ' smoking corpses to get it . \n\n xxmaj oddly enough , this film is remembered for its music . xxmaj but in actuality , the only","secondary plot point . xxmaj there 's a ghetto kid who has too much xxunk what , was i surprised ? xxmaj and guess what ? xxmaj they all want to become big stars , finding fame and fortune , and they 'd all be willing to crawl over their own mothers ' smoking corpses to get it . \n\n xxmaj oddly enough , this film is remembered for its music . xxmaj but in actuality , the only moderately"
4,"' was made in xxmaj germany in 1913 , starring xxmaj paul xxmaj wegener ( who was also in ' the xxmaj golem ' a few years later ) . xxmaj in this film he plays a dual role ( technically impressive for a 95 year old film to see them in the same shot ) after meeting a mysterious old man who makes a pact with him for gold - the gold he needs to woo a countess he","was made in xxmaj germany in 1913 , starring xxmaj paul xxmaj wegener ( who was also in ' the xxmaj golem ' a few years later ) . xxmaj in this film he plays a dual role ( technically impressive for a 95 year old film to see them in the same shot ) after meeting 

- xxbox: 새로운 텍스트의 시작 
- xxmaj: 다음단어가 대문자로 시작함을 의미 (모든단어는 기본적으로 소문자라고 생각함) 
- .. 

In [6]:
lrnr = language_model_learner(dls,AWD_LSTM,metrics=accuracy).to_fp16()

- to_fp16(): 그레디언트를 대충계산한다. 

In [7]:
lrnr.fit_one_cycle(5)

epoch,train_loss,valid_loss,accuracy,time
0,4.462815,4.136233,0.283587,07:26
1,4.335924,4.033761,0.290330,07:23
2,4.293494,3.999372,0.292693,07:22
3,4.274117,3.986934,0.293585,07:21
4,4.258859,3.984887,0.293765,07:36


In [8]:
TEXT = 'I liked this movie because' 
N_WORDS= 40 
N_SENTENCES = 5
preds = [lrnr.predict(TEXT,N_WORDS,temperature=0.75) for _ in range(N_SENTENCES)]
print("\n".join(preds))

i liked this movie because i had already heard of the Academy Award for this movie and i loved it . It was truly one of the best movies i have ever seen . i was pretty happy with it . i
i liked this movie because i wanted to be a fan of B 6.5 movies in the early 80 's and lived for a long time . It was so interesting that i was hoping for it to make it it 's "
i liked this movie because it was a fun movie . i thought it was a cheap , gritty movie about a man who has been around for years , his father is a film maker , i believe he picked out the Dutch
i liked this movie because they were watching this film on TV , but this was one of the worst movies ever made . So , i tried not to throw in this movie . The plot is simple , and this
i liked this movie because i liked Jaws when there was a plot and it was a great movie . The only flaw in this movie is that there is nothing going on that he does not even make it … a very


- 말이 안되는것 같은데 그럴듯해보이긴함 

### 문제의설계 

In [9]:
text= 'h e l l o '*100
text

'h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o

In [10]:
tokens= text.split(' ')[:-1]
tokens[:10]

['h', 'e', 'l', 'l', 'o', 'h', 'e', 'l', 'l', 'o']

`-` 바로직전문자로 다음문자를 맞춰보자. 
- hello 니까, h $\to$ e, e $\to$ l, l $\to$ l/o (?), l $\to$ o, o $\to$ h ... 
- l 다음에 올 문자가 조금 애매하다. 

`-` 마치 아래의 표에서 $X \to y$인 맵핑을 알아차려 $X$를 보고 $y$를 예측하듯이 

|X|y|
|:-:|:-:|
|1|2|
|2|4|
|3|6|
|1|2|
|2|4|
|3|6|
|...|...|

우리는 이제 아래를 예측하는 규칙을 알아차리는게 목표이다. 

|X|y|
|:-:|:-:|
|h|e|
|e|l|
|l|l/o|
|o|h|
|h|e|
|...|...|

### Embedding 

`-` X,y를 설정하자.  

In [11]:
X= tokens[:(len(tokens)-1)]
y= tokens[1:len(tokens)]

In [12]:
X[0],y[0]

('h', 'e')

In [13]:
X[1],y[1]

('e', 'l')

`-` 다 좋은데 학습가능한 형태로 만들어야 하므로 문자를 숫자로 바꾸자. 

In [14]:
dic = {'h': 0, 'e': 1, 'l': 2, 'o': 3}
dic

{'h': 0, 'e': 1, 'l': 2, 'o': 3}

In [15]:
dic['h'],dic['e'],dic['l'],dic['o'] 

(0, 1, 2, 3)

In [16]:
nums = [dic[i] for i in tokens]

In [17]:
tokens[:10],nums[:10]

(['h', 'e', 'l', 'l', 'o', 'h', 'e', 'l', 'l', 'o'],
 [0, 1, 2, 2, 3, 0, 1, 2, 2, 3])

`-` (맵핑방식1) 아래와 같이 문자와 숫자를 mapping 하였다.

|문자(tokens)|숫자(nums)|
|:-:|:-:|
|'h'|0|
|'e'|1|
|'l'|2|
|'l'|2|
|'o'|3|
|'h'|0|
|'e'|1|
|'l'|2|
|'l'|2|
|'o'|3|
|'h'|0|
|'e'|1|
|'l'|2|
|'l'|2|
|'o'|3|
|...|...|

`-` (맵핑방식2) 사실 아래와 같이 맵핑하는 것이 더 좋다. 위의방식대로하면 의미가 `e=1`, `l=2`가 되는데 그렇다고해서 `l이 e보다 2배가 강한 입력`을 의미하는것은 아니므로.. 

|문자(tokens)|숫자(nums)|
|:-:|:-:|
|'h'|1,0,0,0|
|'e'|0,1,0,0|
|'l'|0,0,1,0|
|'l'|0,0,1,0|
|'o'|0,0,0,1|
|'h'|1,0,0,0|
|'e'|0,1,0,0|
|'l'|0,0,1,0|
|'l'|0,0,1,0|
|'o'|0,0,0,1|
|'h'|1,0,0,0|
|'e'|0,1,0,0|
|'l'|0,0,1,0|
|'l'|0,0,1,0|
|'o'|0,0,0,1|
|...|...|

`-` 맵핑방식2로 처리하고 싶은데, 데이터 전처리 하기가 너무 하기 어려울것 같다. 
- 그런데 이러한것은 빈번하게 일어나는 상황아닌가?.. 
- 누군가 구해놓지 않았을까?.. 
- torch.nn.Embedding 

`-` 맵핑방식1의 구현 

In [18]:
_l1 = torch.nn.Linear(in_features=1,out_features=20,bias=False)

In [19]:
_x = torch.tensor([[0.0],[1.0],[2.0],[2.0],[3.0],[0.0],[1.0],[2.0],[2.0],[3.0]])
_l1(_x)

tensor([[ 0.0000, -0.0000, -0.0000, -0.0000, -0.0000,  0.0000, -0.0000, -0.0000,
          0.0000,  0.0000,  0.0000,  0.0000, -0.0000,  0.0000, -0.0000, -0.0000,
          0.0000, -0.0000, -0.0000,  0.0000],
        [ 0.4261, -0.7680, -0.4899, -0.4162, -0.9343,  0.2654, -0.7111, -0.7218,
          0.3798,  0.1341,  0.1394,  0.8057, -0.1466,  0.4929, -0.8309, -0.5733,
          0.6384, -0.3503, -0.9432,  0.7543],
        [ 0.8522, -1.5359, -0.9797, -0.8324, -1.8687,  0.5308, -1.4221, -1.4437,
          0.7595,  0.2682,  0.2788,  1.6114, -0.2932,  0.9858, -1.6617, -1.1466,
          1.2768, -0.7007, -1.8863,  1.5087],
        [ 0.8522, -1.5359, -0.9797, -0.8324, -1.8687,  0.5308, -1.4221, -1.4437,
          0.7595,  0.2682,  0.2788,  1.6114, -0.2932,  0.9858, -1.6617, -1.1466,
          1.2768, -0.7007, -1.8863,  1.5087],
        [ 1.2783, -2.3039, -1.4696, -1.2487, -2.8030,  0.7962, -2.1332, -2.1655,
          1.1393,  0.4023,  0.4182,  2.4172, -0.4397,  1.4787, -2.4926, -1.7199,
      

- 입력: (10,1) 
- 출력: (10,20) 

`-` 맵핑방식2의 구현 

In [20]:
e1=torch.nn.Embedding(num_embeddings=4,embedding_dim=20) 

In [21]:
_x = torch.tensor([0,1,2,3,0,1,2,3])
e1(_x)

tensor([[ 0.4826,  0.1979,  0.6964, -1.1062, -0.8036, -0.6258, -0.9893, -0.4021,
          1.1672, -0.1955,  0.1773, -1.5316, -2.2204, -0.4605,  2.0872, -3.1483,
         -1.0550, -0.2203, -0.5524,  1.1378],
        [-0.2646, -0.2168,  0.1466,  0.6471,  0.2696,  1.1243, -0.2466, -0.5574,
          0.5946,  1.4415, -0.8816,  1.3108,  1.4673,  0.1498,  0.3163,  0.8087,
          0.8232, -1.5435,  0.4836,  0.5355],
        [ 1.5430,  1.0280,  0.7876,  1.5524,  0.9246,  2.2404,  0.4866,  0.6147,
         -0.9670,  0.6367, -0.6069,  0.9140, -0.1382,  0.8137,  1.0065, -0.5454,
         -0.9137, -0.3055, -0.7676,  1.3403],
        [ 2.2334, -0.5390,  0.2648,  1.3212,  1.0973,  0.5246, -0.2448, -0.4751,
          0.2873, -0.4603, -0.1851,  1.4525,  1.2113,  0.3581,  1.1385, -0.6595,
          1.1618,  0.5289,  0.8194, -1.4222],
        [ 0.4826,  0.1979,  0.6964, -1.1062, -0.8036, -0.6258, -0.9893, -0.4021,
          1.1672, -0.1955,  0.1773, -1.5316, -2.2204, -0.4605,  2.0872, -3.1483,
      

- 입력차원: (10,1) 
- 출력차원: (10,20)

`-` 결과가 똑같다? 하지만 내부 수행과정은 약간 다르다. 

In [22]:
list(_l1.parameters())

[Parameter containing:
 tensor([[ 0.4261],
         [-0.7680],
         [-0.4899],
         [-0.4162],
         [-0.9343],
         [ 0.2654],
         [-0.7111],
         [-0.7218],
         [ 0.3798],
         [ 0.1341],
         [ 0.1394],
         [ 0.8057],
         [-0.1466],
         [ 0.4929],
         [-0.8309],
         [-0.5733],
         [ 0.6384],
         [-0.3503],
         [-0.9432],
         [ 0.7543]], requires_grad=True)]

- 맵핑방식1의 경우 $1\times 20$의 차원의 ${\bf W}$가 존재함. 따라서 
    - ${\bf X}$: (10,1) 
    - ${\bf W}$: (1,20) 
    - ${\bf X}{\bf W}$: (10,20)

In [23]:
list(e1.parameters())

[Parameter containing:
 tensor([[ 0.4826,  0.1979,  0.6964, -1.1062, -0.8036, -0.6258, -0.9893, -0.4021,
           1.1672, -0.1955,  0.1773, -1.5316, -2.2204, -0.4605,  2.0872, -3.1483,
          -1.0550, -0.2203, -0.5524,  1.1378],
         [-0.2646, -0.2168,  0.1466,  0.6471,  0.2696,  1.1243, -0.2466, -0.5574,
           0.5946,  1.4415, -0.8816,  1.3108,  1.4673,  0.1498,  0.3163,  0.8087,
           0.8232, -1.5435,  0.4836,  0.5355],
         [ 1.5430,  1.0280,  0.7876,  1.5524,  0.9246,  2.2404,  0.4866,  0.6147,
          -0.9670,  0.6367, -0.6069,  0.9140, -0.1382,  0.8137,  1.0065, -0.5454,
          -0.9137, -0.3055, -0.7676,  1.3403],
         [ 2.2334, -0.5390,  0.2648,  1.3212,  1.0973,  0.5246, -0.2448, -0.4751,
           0.2873, -0.4603, -0.1851,  1.4525,  1.2113,  0.3581,  1.1385, -0.6595,
           1.1618,  0.5289,  0.8194, -1.4222]], requires_grad=True)]

- 맵핑방식2의 경우 $4\times 20$의 차원의 ${\bf W}$가 존재함. 따라서 
    - ${\bf X}$: (10,1) 
    - $\tilde{{\bf X}}$: (10,4) 
    - ${\bf W}$: (4,20) 
    - $\tilde{{\bf X}}{\bf W}$: (10,20)

`-` 결국 우리가 맵핑방식2처럼 구현하고 싶다고 하더라도, 입력은 아래와 같이 넣어도 무방하다. 이후에는 알아서 파이토치가 해결해준다. 

In [24]:
_x

tensor([0, 1, 2, 3, 0, 1, 2, 3])

### 네트워크 구축 

`-` 이제 숫자화된 자료를 이용하여 다시 X,y를 선언하자. 

In [25]:
X = torch.tensor(nums[:499])
y = torch.tensor(nums[1:])

In [26]:
X[0],y[0]

(tensor(0), tensor(1))

In [27]:
X[1],y[1]

(tensor(1), tensor(2))

`-` 간단한 네트워크를 통하여 학습을 시도하자. 

In [28]:
e1=torch.nn.Embedding(num_embeddings=4,embedding_dim=20) 
l1=torch.nn.Linear(in_features=20,out_features=20)
a1=torch.nn.ReLU()
l2=torch.nn.Linear(in_features=20,out_features=4)
a2=torch.nn.Softmax()

In [29]:
X.shape,e1(X).shape

(torch.Size([499]), torch.Size([499, 20]))

In [30]:
e1(X).shape,a1(l1(e1(X))).shape

(torch.Size([499, 20]), torch.Size([499, 20]))

In [31]:
a1(l1(e1(X))).shape,l2(a1(l1(e1(X)))).shape

(torch.Size([499, 20]), torch.Size([499, 4]))

In [32]:
l2(a1(l1(e1(X))))[0]

tensor([-0.1417,  0.3425,  0.4224, -0.1411], grad_fn=<SelectBackward0>)

In [33]:
a2(l2(a1(l1(e1(X)))))[0]

<ipython-input-33-17d00ccf79de>:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  a2(l2(a1(l1(e1(X)))))[0]


tensor([0.1858, 0.3016, 0.3267, 0.1859], grad_fn=<SelectBackward0>)

- $X$의 차원이 명시되지 않아서 대충 내가 알아서 계산했다는 워닝

`-` 경고가 찝찝하여 손계산해봄 $\to$ 알아서 잘 계산했음 

In [34]:
np.exp(0.1195)/(np.exp(0.1195)+np.exp(-0.3600)+np.exp(-0.1282)+np.exp(-0.5230))

0.34180289149024373

`-` 순전파차원변화 요약 

```
torch.Size([499]) ## X with levels=4 
torch.Size([499, 20]) ## 임베딩 이후
torch.Size([499, 20]) ## 선형변환1 이후
torch.Size([499, 20]) ## 렐루 이후
torch.Size([499, 4]) ## 선형변환2 이후 
torch.Size([499, 4]) ## 소프트맥스 이후 = yhat 
```

In [35]:
net = torch.nn.Sequential(
    torch.nn.Embedding(num_embeddings=4,embedding_dim=20),
    torch.nn.Linear(in_features=20,out_features=20),
    torch.nn.ReLU(),
    torch.nn.Linear(in_features=20,out_features=4))
    #torch.nn.Softmax()

In [36]:
net(X)

tensor([[-0.0390,  0.1723,  0.0680,  0.1800],
        [ 0.1135,  0.0763, -0.1970,  0.3331],
        [ 0.0660,  0.0039, -0.0388, -0.0393],
        ...,
        [ 0.1135,  0.0763, -0.1970,  0.3331],
        [ 0.0660,  0.0039, -0.0388, -0.0393],
        [ 0.0660,  0.0039, -0.0388, -0.0393]], grad_fn=<AddmmBackward0>)

- 순전파 

`-` 손실함수, 옵티마이저 

In [37]:
loss_fn = torch.nn.CrossEntropyLoss() 
optimizer = torch.optim.Adam(net.parameters())

In [38]:
for i in range(1000):
    ## 1 
    yhat = net(X) 
    ## 2 
    loss = loss_fn(yhat,y) 
    ## 3 
    loss.backward()
    ## 4 
    optimizer.step()
    optimizer.zero_grad()

In [43]:
dic

{'h': 0, 'e': 1, 'l': 2, 'o': 3}

In [44]:
X[:7] 

tensor([0, 1, 2, 2, 3, 0, 1])

In [45]:
net(X)[:7]

tensor([[-1.6775,  5.5011, -3.4213, -3.4339],
        [-3.4982, -2.7990,  6.1543, -0.7833],
        [-2.9557, -3.5165,  4.2790,  4.2780],
        [-2.9557, -3.5165,  4.2790,  4.2780],
        [ 5.1552, -2.7903, -3.2462, -2.7748],
        [-1.6775,  5.5011, -3.4213, -3.4339],
        [-3.4982, -2.7990,  6.1543, -0.7833]], grad_fn=<SliceBackward0>)

In [46]:
y[:7]

tensor([1, 2, 2, 3, 0, 1, 2])

- 학습이 잘 되었다. 

### net의 개선 

`-` 단어수가 바뀔때마다 아래를 새로 정의해야 하나?
```python
net = torch.nn.Sequential(
    torch.nn.Embedding(num_embeddings=4,embedding_dim=20),
    torch.nn.Linear(in_features=20,out_features=20),
    torch.nn.ReLU(),
    torch.nn.Linear(in_features=20,out_features=4))
    #torch.nn.Softmax()
```

`-` 네트워크를 찍어내는 뭔가가 있음 좋지 않을까? 제가 만들어볼게요!

In [47]:
class BDA(Module): 
    def __init__(self, num_embeddings): 
        self.embedding = nn.Embedding(num_embeddings,20)
        self.linear1 = nn.Linear(20,20)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(20,num_embeddings) 
    def forward(self,X):
        u= self.linear1(self.embedding(X))
        v= self.relu(u)
        return self.linear2(v)

- 그냥 이렇게 간단해보이는 코드로 가능하다고? $\to$ 필요한 다른기능들은 Module에서 상속받았으므로 가능하다!

In [48]:
net2 = BDA(4) # 4는 dic의 size

In [49]:
net

Sequential(
  (0): Embedding(4, 20)
  (1): Linear(in_features=20, out_features=20, bias=True)
  (2): ReLU()
  (3): Linear(in_features=20, out_features=4, bias=True)
)

In [50]:
net2

BDA(
  (embedding): Embedding(4, 20)
  (linear1): Linear(in_features=20, out_features=20, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=20, out_features=4, bias=True)
)

- 오.. 

In [51]:
loss_fn = torch.nn.CrossEntropyLoss() 
optimizer2 = torch.optim.Adam(net2.parameters())

In [52]:
for i in range(1000):
    ## 1 
    yhat = net2(X) 
    ## 2 
    loss = loss_fn(yhat,y) 
    ## 3 
    loss.backward()
    ## 4 
    optimizer2.step()
    optimizer2.zero_grad()

In [53]:
net2(X)

tensor([[-1.9487,  5.3394, -2.0415, -3.1098],
        [-3.6909, -3.4377,  3.7789, -4.3068],
        [-4.1058, -4.1514,  2.9291,  2.9290],
        ...,
        [-3.6909, -3.4377,  3.7789, -4.3068],
        [-4.1058, -4.1514,  2.9291,  2.9290],
        [-4.1058, -4.1514,  2.9291,  2.9290]], grad_fn=<AddmmBackward0>)

In [54]:
net(X)

tensor([[-1.6775,  5.5011, -3.4213, -3.4339],
        [-3.4982, -2.7990,  6.1543, -0.7833],
        [-2.9557, -3.5165,  4.2790,  4.2780],
        ...,
        [-3.4982, -2.7990,  6.1543, -0.7833],
        [-2.9557, -3.5165,  4.2790,  4.2780],
        [-2.9557, -3.5165,  4.2790,  4.2780]], grad_fn=<AddmmBackward0>)

`-` net2도 잘 학습 되었다.

### 이전2단계

In [55]:
X = torch.tensor([nums[:498],nums[1:499]]).T
y = torch.tensor(nums[2:])

In [56]:
X[0],y[0] # he -> l 

(tensor([0, 1]), tensor(2))

In [57]:
X[1],y[1] # el -> l 

(tensor([1, 2]), tensor(2))

In [58]:
X[2],y[2] # ll -> o

(tensor([2, 2]), tensor(3))

`-` 아키텍처를 대충 스케치해보자. 

In [59]:
_e1 = torch.nn.Embedding(num_embeddings=4,embedding_dim=20)

In [60]:
X.shape, _e1(X).shape

(torch.Size([498, 2]), torch.Size([498, 2, 20]))

`-` 이전의 아키텍처는 아래와 같았음. 

```
torch.Size([499]) ## X with levels=4 
torch.Size([499, 20]) ## 임베딩 이후
torch.Size([499, 20]) ## 선형변환1 이후
torch.Size([499, 20]) ## 렐루 이후
torch.Size([499, 4]) ## 선형변환2 이후 
torch.Size([499, 4]) ## 소프트맥스 이후 = yhat 
```

`-` 벌써부터 꼬이는데?? 마지막 차원은 어쩌지? 합치나? 
- 합치는게 나쁜건 아닐지 몰라도 다른 대안이 있음 $\to$ 순환신경망의 발견 

`-` 순환신경망의 설계 

In [61]:
class BDA2(Module): 
    def __init__(self, num_embeddings): 
        self.embedding = nn.Embedding(num_embeddings,20)
        self.linear1 = nn.Linear(20,20)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(20,num_embeddings) 
    def forward(self,X):
        x1=X[:,0] # X의 첫번째 칼럼, y보다 2시점이전
        x2=X[:,1] # X의 두번째 칼럼, y보다 1시점이전 
        v=self.relu(self.linear1(self.embedding(x1))) # v: (498,20) 
        v2=self.relu(self.linear1(v+self.embedding(x2))) # 
        return self.linear2(v2)

`-` 결국 최종출력인 v2는 v와 x2이 담긴 함수이다. 그런데 v는 x1이 담긴 함수이다. 따라서 v2는 x2가 담겨있는 동시에 x1도 약하게 담겨있다 볼 수 있음. 

In [62]:
net3=BDA2(4)
net3

BDA2(
  (embedding): Embedding(4, 20)
  (linear1): Linear(in_features=20, out_features=20, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=20, out_features=4, bias=True)
)

In [63]:
net2

BDA(
  (embedding): Embedding(4, 20)
  (linear1): Linear(in_features=20, out_features=20, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=20, out_features=4, bias=True)
)

- 구조의 차이는 없지만 순전파 계산방식이 다르다! (그렇다면 역전파 계산방식도 다르겠지?..) 

`-` 다시 학습해보자. 

In [64]:
loss_fn = torch.nn.CrossEntropyLoss() # 사실손실함수는 계속 재활용해도 괜찮은데.. 어차피 같은거임 
optimizer3 = torch.optim.Adam(net3.parameters())

In [65]:
for i in range(1000):
    ## 1 
    yhat = net3(X) 
    ## 2 
    loss = loss_fn(yhat,y) 
    ## 3 
    loss.backward() 
    ## 4 
    optimizer3.step()
    optimizer3.zero_grad()

In [66]:
X[:5]

tensor([[0, 1],
        [1, 2],
        [2, 2],
        [2, 3],
        [3, 0]])

In [67]:
net3(X)[:5]

tensor([[-4.1867, -2.5231,  5.6130, -2.6112],
        [-2.9066, -4.9354,  6.1277, -2.1195],
        [-2.7608, -4.4389, -1.9106,  5.8098],
        [ 5.2848, -3.3778, -3.6655, -3.0704],
        [-2.0908,  5.7988, -3.1842, -3.2361]], grad_fn=<SliceBackward0>)

- he $\to$ l 
- el $\to$ l 
- ll $\to$ o 
- lo $\to$ h
- oh $\to$ e 

`-` 학습이 잘되었다. 

`-` 네트워크를 만드는 클래스를 조금 정리하자. 

```python 
### 원래 이런클래스였음 
class BDA2(Module): 
    def __init__(self, num_embeddings): 
        self.embedding = nn.Embedding(num_embeddings,20)
        self.linear1 = nn.Linear(20,20)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(20,num_embeddings) 
    def forward(self,X):
        x1=X[:,0] # X의 첫번째 칼럼, y보다 2시점이전
        x2=X[:,1] # X의 두번째 칼럼, y보다 1시점이전 
        v=self.relu(self.linear1(self.embedding(x1))) # v: (498,20) 
        v2=self.relu(self.linear1(v+self.embedding(x2))) # 
        return self.linear2(v2)

```

In [68]:
class BDA2(Module): ## 조금 정리한 클래스
    def __init__(self, num_embeddings): 
        self.embedding = nn.Embedding(num_embeddings,20)
        self.linear1 = nn.Linear(20,20)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(20,num_embeddings) 
    def forward(self,X):
        v=0 
        for i in range(2):        
            v=self.relu(self.linear1(v+self.embedding(X[:,i]))) # 
        return self.linear2(v)

In [69]:
net3=BDA2(4)
loss_fn = torch.nn.CrossEntropyLoss() # 사실손실함수는 계속 재활용해도 괜찮은데.. 어차피 같은거임 
optimizer3 = torch.optim.Adam(net3.parameters())

In [70]:
for i in range(1000):
    ## 1 
    yhat = net3(X) 
    ## 2 
    loss = loss_fn(yhat,y) 
    ## 3 
    loss.backward() 
    ## 4 
    optimizer3.step()
    optimizer3.zero_grad()

In [71]:
X[:5]

tensor([[0, 1],
        [1, 2],
        [2, 2],
        [2, 3],
        [3, 0]])

In [72]:
net3(X)[:5]

tensor([[-2.6838, -2.8267,  6.9506, -5.3724],
        [-3.9758, -4.1013,  6.3548, -1.7511],
        [-2.6599, -2.9786, -2.2506,  5.5550],
        [ 5.5041, -3.3523, -4.0357, -2.7792],
        [-4.2855,  4.9629, -4.2295, -5.0334]], grad_fn=<SliceBackward0>)

- 동일한 결과가 나옴. 코드정리가 성공적이었음. 

`-` 문자를 단어로 바꾸고 한개의 단어 예측을 여러 단어 예측으로 바꾸면? $\to$ 그럴듯한 단어를 내뱉는 시스템만들어짐 (모르는 사람이 보면 AGI와 같을 정도) 