# (노트) 에일리어싱, 얕은복사, 깊은복사 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

### About this doc 

`-` 2021년 1학기 전북대학교 파이썬입문 강의노트

### Introduction 

`-` (예제1) 아래의 코드를 관찰하자. 

In [93]:
a=[1,2,3]
b=a
a.append(4)

현재 b라는 변수의 출력결과는? 

In [95]:
b

[1, 2, 3, 4]

`-` (예제2) 이제 다시 아래의 코드를 관찰하자. 

In [91]:
a=[1,2,3]
b=a
a=[1,2,3]+[4]

In [92]:
b

[1, 2, 3]

### 할당문

#### 메모리구조의 상상

`-` 다시 아래의 코드를 살펴보자. 

In [96]:
a=[1,2,3]
b=a
a.append(4)

a,b라는 변수들은 메모리에 어떻게 저장되어있을까? 

상상력을 조금 발휘하면 아래와 같이 여길 수 있다. 

- 메모리는 방이 100개 있는호텔이라고 생각하자. 

- ```python 
a=[1,2,3]
```
    - 메모리 주소1에 존재하는 방을 앞으로 a라고 부르자. 그리고 그 방에 [1,2,3]을 넣는다. 

- ```python
b=a
```
    - 메모리 주소2에 존재하는 방을 b라고 부르고 그 방에 a를 넣는다. 
    - 그런데 a=[1,2,3]이므로 b라는 방 역시 [1,2,3]이 있다. 

- ```python
a.append(4)
```
    - 방 a로 가서 [1,2,3]을 [1,2,3,4]로 바꾼다. 
    - 방 b는 아무일도 일어나지 않는다. 


다른언어에서는 맞는 이야기 일 수 있는데 파이썬에서는 조금 다르다. 

In [97]:
id(a)

140200175254400

In [98]:
id(b)

140200175254400

실제로는 변수 a,b의 방주소가 동일하기 때문이다. 따라서 아래와 같은 비유가 더 적절하다. 

- 메모리는 방이 100개 있는호텔이라고 생각하자. 

- ```python 
a=[1,2,3]
```
    - 메모리 주소1에서 [1,2,3]을 만든다. 
    - 메모리 주소1의 방문에 a라는 포스트잇을 붙인다. (따라서 앞으로 [1,2,3]을 찾으려면 a라고 적힌 포스트잇을 찾으면 된다.) 

- ```python
b=a
```
    - 메모리 주소1의 방문에 b라는 포스트잇을 붙인다. (더 원시적인 해석으로는 "b라는 포스트잇을 만들고 a라는 포스트잇과 동일한 효과를 주도록 한다"로 읽으면 된다.)
    - 따라서 [1,2,3]을 찾으려면 a라는 포스트잇을 찾거나 b라는 포스트잇을 찾으면 된다. 

- ```python
a.append(4)
```
    - a라는 포스트잇이 붙어있는 방으로 찾아가서 [1,2,3]을 찾고 거기에서 append함수를 써서 [1,2,3,4]로 바꾼다. 
    - 같은방에 a,b라는 포스트잇이 붙어이므로 b라는 포스트잇을 찾아가서 내용을 열어보면 [1,2,3,4]가 나온다. 

#### 할당문의 이해

파이썬에서 할당문을 이해하려면 언제나 오른쪽을 먼저 읽어야 한다. 

- 할당문의 오른쪽에서 객체를 생성하거나 가져온다. 
- 그 후에 레이블을 붙이듯이 할당문 왼족의 변수가 객체에 바인딩 된다. 

#### 에일리어싱(aliasing)

`b=a`는 

> 나는 이미 a가 의미하는걸 알고 있어, 그런데 a가 의미하는걸 b라고도 부르고싶어 

라는 것과 같다. 즉 이미 a라고 부르고 있던것을 `가져와서` b라고도 부르고싶다는 의미인데, 이러한 관점에서 b는 a의 별칭(alias)이라고 볼 수 있다. 

반대로 생각해보면 a역시 b의 별명이라고 볼 수 있다. 

이처럼 하나의 메모리 주소에 여러개의 변수이름을 라벨링하는 것을 aliasing이라고 부른다. 

#### ID vs value

`-` 모든 객체(object)는 ID, value, type을 가진다. 

https://docs.python.org/3/reference/datamodel.html#objects-values-and-types


`-` 아래의 예제를 고려하자. 

In [99]:
a=[1,2,3]
b=a
a.append(4)
c=[1,2,3,4]

`-` 위의 예제에서 a,b,c는 모두 같은 값을 가진다. 

In [101]:
a,b,c

([1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4])

In [102]:
a==b,b==c,a==c

(True, True, True)

`-` 하지만 그 ID가 같은 것은 아니다. 

In [103]:
id(a),id(b),id(c)

(140200420846528, 140200420846528, 140200170151488)

In [104]:
a is b, b is c, a is c

(True, False, False)

Note: 연산자 == 는 두 객체간의 값을 비교하고 연산자 is 는 두 객체간의 메모리주소값을 비교한다. 

#### 마무리 

아래 코드를 다시 비교해보라. 

- ```python 
a=[1,2,3]
b=a
a.append(4)
```


- ```python
a=[1,2,3]
b=a
a=[1,2,3]+[4]
```

`a=[1,2,3]+[4]`는 새로운 메모리주소에서 새로운 객체를 만든다. 

`a.append(4)`는 이미 있는 객체를 변경한다. 



아래의 사이트를 방문하면 좀 더 직관적인 이해가 가능하다. 

http://www.pythontutor.com

### interning

`–` 예제1 

In [74]:
a=257
b=257 
id(a),id(b)

(140200165375536, 140200165375664)

어떠한 메모리 주소에 257이라는 오브젝트를 만들고 a라하고, 또 다른 메모리 주소에 257이라는 오브젝트를 만들고 b라고 하였다. 

따라서 a,b의 id가 다르게 나오는 것은 자명한일 

`-` 예제2

In [75]:
a=256
b=256
id(a),id(b)

(94276032097568, 94276032097568)

그런데, 이건 왜 똑같지??

효율성 때문에 파이썬에서는 내부에 [-5,256]까지의 정수를 미리 저장해둔다고 한다. 

https://docs.python.org/3/c-api/long.html#c.PyLong_FromLong

에서 PyLong_FromLong 참고

`-` 예제3 

In [79]:
a=2
b=a
c=5
d=a+3
id(a),id(b),id(c),id(d)

(94276032089440, 94276032089440, 94276032089536, 94276032089536)

### 에일리어싱, 깊은복사, 얕은복사 

`-` 예제 1

case1: 2개의 객체를 생성

In [159]:
l1=[[3,2],[55,44]]
l2=[[3,2],[55,44]]
print(l1==l2)
print(l1[0]==l2[0])
print(l1[1]==l2[1])
print(id(l1),id(l2),id(l1)==id(l2))
print(id(l1[0]),id(l2[0]),id(l1[0])==id(l2[0]))
print(id(l1[1]),id(l2[1]),id(l1[1])==id(l2[1]))

True
True
True
140200175761792 140200174007168 False
140200178157312 140200176747136 False
140200175761536 140200174009536 False


In [160]:
l1[1].append(77)
print(l1)
print(l2)

[[3, 2], [55, 44, 77]]
[[3, 2], [55, 44]]


In [161]:
l1.append('asdf')
print(l1)
print(l2)

[[3, 2], [55, 44, 77], 'asdf']
[[3, 2], [55, 44]]


case2: 에일리어싱

In [165]:
l1=[[3,2],[55,44]]
l2=l1
print(l1==l2)
print(l1[0]==l2[0])
print(l1[1]==l2[1])
print(id(l1),id(l2),id(l1)==id(l2))
print(id(l1[0]),id(l2[0]),id(l1[0])==id(l2[0]))
print(id(l1[1]),id(l2[1]),id(l1[1])==id(l2[1]))

True
True
True
140200173636800 140200173636800 True
140200178158016 140200178158016 True
140200178157312 140200178157312 True


case3: 얕은복사

In [287]:
l1=[[3,2],[55,44]]
l2=l1.copy()
print(l1==l2)
print(l1[0]==l2[0])
print(l1[1]==l2[1])
print(id(l1),id(l2),id(l1)==id(l2))
print(id(l1[0]),id(l2[0]),id(l1[0])==id(l2[0]))
print(id(l1[1]),id(l2[1]),id(l1[1])==id(l2[1]))

True
True
True
140200167579264 140200167577472 False
140200167579520 140200167579520 True
140200167577536 140200167577536 True


In [288]:
l1[1].append(77)
print(l1)
print(l2)

[[3, 2], [55, 44, 77]]
[[3, 2], [55, 44, 77]]


In [289]:
l1.append('asdf')
print(l1)
print(l2)

[[3, 2], [55, 44, 77], 'asdf']
[[3, 2], [55, 44, 77]]


case4: 깊은복사

In [290]:
from copy import deepcopy

In [291]:
l1=[[3,2],[55,44]]
l2=deepcopy(l1)
print(l1==l2)
print(l1[0]==l2[0])
print(l1[1]==l2[1])
print(id(l1),id(l2),id(l1)==id(l2))
print(id(l1[0]),id(l2[0]),id(l1[0])==id(l2[0]))
print(id(l1[1]),id(l2[1]),id(l1[1])==id(l2[1]))

True
True
True
140200167070720 140200167578304 False
140200167578880 140200169939136 False
140200167603712 140200167070336 False


In [292]:
l1[1].append(77)
print(l1)
print(l2)

[[3, 2], [55, 44, 77]]
[[3, 2], [55, 44]]


In [293]:
l1.append('asdf')
print(l1)
print(l2)

[[3, 2], [55, 44, 77], 'asdf']
[[3, 2], [55, 44]]


#### Numpy

`-` 예제1 (에일리어싱)

In [359]:
import numpy as np

In [362]:
a=np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
b=a[1][1:]
a,b

(array([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]),
 array([3, 4]))

In [363]:
b[0]=100

In [364]:
a,b

(array([[  1,   2,   3],
        [  2, 100,   4],
        [  3,   4,   5],
        [  4,   5,   6]]),
 array([100,   4]))

`-` 예제2 (복사)

In [366]:
a=np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
b=a[1][1:].copy()
a,b

(array([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]),
 array([3, 4]))

In [367]:
b[0]=100

In [368]:
a,b

(array([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]),
 array([100,   4]))