In [2]:
#hide
options(jupyter.plot_scale=3)
options(jupyter.display_mimetypes=c("text/html"))
options(jupyter.rich_display=FALSE)
options(repr.plot.width=6,repr.plot.height=6,repr.plot.res=300)
options(max.print=1000)

# (6주차) 10월19일
> 숫자 카드 게임  

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈

### 강의노트

> youtube: https://youtube.com/playlist?list=PLQqh36zP38-xqwIaFUv3Gd0YjvohLV2gW


`-` (1/1) 숫자 카드 게임

### 숫자 카드 게임 (2019 국가 교육기관 코딩테스트) 

숫자 카드 게임은 여러개의 숫자중에서 가장 높은 숫자가 쓰인 카드를 한장 뽑는 게임이다. 

단, 게임의 룰을 지키며 카드를 뽑아야 하고 룰은 다음과 같다. 

- 숫자가 쓰인 카드들이 N $\times $M 형태로 놓여 있다. 
- 먼저 뽑고자 하는 카드가 포함되어 있는 행을 선택한다. 
- 그 다음 선택된 행에 포함된 카드들 중에서 가장 숫자가 낮은 카드를 뽑아야 한다. 
- 따라서 처음에 카드를 골라낼 행을 선택할때, 이후에 해당 행에서 가장 숫자가 낮은 카드를 뽑을 것을 고려하여 최종적으로 가장 높은 숫자의 카드를 뽑을 수 있도록 전략을 세워야 한다. 

`-` 예시1

```
입력
3 1 2 
4 1 4 
2 2 2 
```

```
출력 
2
```

`-` 예시2

```
입력
7 3 1 8 
3 3 3 4 
```

```
출력
3
```

(풀이) 

(전략회의)

In [3]:
a1=c(3,1,2) 
a2=c(4,1,4)
a3=c(2,2,2)

우리는 일단 아래와 같은 모양을 만들어야함 

```
3 1 2
4 1 4 
2 2 2 
```

a1,a2,a3을 각각 row-vector 로 해석하고 bind 하면된다. 

In [4]:
A = rbind(a1,a2,a3)

In [5]:
A

   [,1] [,2] [,3]
a1 3    1    2   
a2 4    1    4   
a3 2    2    2   

In [6]:
A= rbind(c(3,1,2),c(4,1,4),c(2,2,2))

입력이 A일경우 출력이 2가 나와야한다. 

전략: 
1. A의 각 행(row)을 돌아가면서 가장 작은 숫자를 찾아 기록한다. 
2. 기록한 숫자들을 모아서 벡터로 만든다. 
3. 벡터의 최대값을 구한다. 

할수있어야 하는것 

- A의 1번째 행, 2번째행, 3번째행을 순서대로 뽑을수 잇어야 한다. 

(실질적풀이)

In [7]:
A= rbind(c(3,1,2),c(4,1,4),c(2,2,2))

In [8]:
vec<-c()
for (i in 1:3) vec[i]<- min(A[i,])

In [9]:
max(vec)

[1] 2

`-` 입력이 아래와 같은 경우 

```
7 3 1 8 
3 3 3 4 
```

In [10]:
A=rbind(c(7,3,1,8),c(3,3,3,4)) 

In [11]:
vec<-c()
for (i in 1:2) vec[i]<- min(A[i,])

In [12]:
max(vec)

[1] 3

### 숙제

입력구조가 
```
3 4 5 1 
7 7 7 2 
8 1 8 2
3 3 4 5 
```

출력을 구하는 코드를 작성하시오. 

### tibble 

In [15]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.3     ✔ dplyr   1.0.7
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()



In [36]:
A=rbind(c(7,3,1,8),c(3,3,3,4)) 

In [37]:
A %>% as_tibble %>% pmap_dbl(min) %>% max

[1] 3

In [38]:
a=c(1,3,2,3,2)

In [39]:
outer(a,a)

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2   
[2,] 3    9    6    9    6   
[3,] 2    6    4    6    4   
[4,] 3    9    6    9    6   
[5,] 2    6    4    6    4   

In [62]:
a%o%a

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1     5    4    3    2    4    5    2  
[2,] 5    25   20   15   10   20   25   10  
[3,] 4    20   16   12    8   16   20    8  
[4,] 3    15   12    9    6   12   15    6  
[5,] 2    10    8    6    4    8   10    4  
[6,] 4    20   16   12    8   16   20    8  
[7,] 5    25   20   15   10   20   25   10  
[8,] 2    10    8    6    4    8   10    4  

 [1] FALSE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[13]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[25]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[37] FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[49]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
[61] FALSE  TRUE  TRUE FALSE

In [50]:
a=c(1,5,4,3,2,4,5,2)

In [54]:
sum(a%o%a %in% c(1,4,9,16,25))

[1] 18