In [33]:
#hide
options(jupyter.plot_scale=3)
options(repr.plot.width=6,repr.plot.height=6,repr.plot.res=300)
options(jupyter.rich_display=FALSE)
options(max.print=1000)

# (노트) 벡터, 매트릭스, 데이터프레임 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [R]

### %>% 

`-` tidyverse중 하나인 dplyr의 기능 

In [34]:
library(dplyr)

`-` 예시1

In [35]:
f<-function(x) x+2

In [36]:
f(2) 

[1] 4

In [37]:
2 %>% f

[1] 4

`-` 예시2

In [38]:
f<-function(x,y) x**2 +y 

In [39]:
f(2,3)

[1] 7

In [40]:
2 %>% f(3) 

[1] 7

`-` 포인트: 첫번째 입력은 %>% 전의 결과로 생각한다. (하나의 입력만 받는 함수라면 함수이름만 쓸 수 있음!) 
- 첫입력을 생략한다는 것이 포인트 

### 두 개 이상의 벡터, 행렬을 결합

#### 벡터의 결합

`-` 예제1

In [41]:
x<-c(1,2,3)
y<-c(1,2,3,4)

In [42]:
x

[1] 1 2 3

In [43]:
y

[1] 1 2 3 4

In [44]:
c(x,y)

[1] 1 2 3 1 2 3 4

- c는 사실 `결합하라`라는 의미를 가짐. 

`-` 예제2

In [45]:
x<-c(1,2,3)
y<-c(4,4,4)

In [46]:
cbind(x,y)

     x y
[1,] 1 4
[2,] 2 4
[3,] 3 4

`-` 예제2-1

In [47]:
x<-c(1,2,3,4)
y<-c(1,2)

In [48]:
cbind(x,y)

     x y
[1,] 1 1
[2,] 2 2
[3,] 3 1
[4,] 4 2

`-` 예제2-2

In [51]:
x<-c(1,2,3,4)

In [52]:
cbind(1,x)

       x
[1,] 1 1
[2,] 1 2
[3,] 1 3
[4,] 1 4

`-` 예제3

In [54]:
x<-c(1,2,3,4)
y<-c(1,2)

In [55]:
rbind(x,y)

  [,1] [,2] [,3] [,4]
x 1    2    3    4   
y 1    2    1    2   

`-` 예제4

In [57]:
x<-c(1,2,3)
y<-c(4,5)

In [58]:
cbind(1,c(x,y))

     [,1] [,2]
[1,] 1    1   
[2,] 1    2   
[3,] 1    3   
[4,] 1    4   
[5,] 1    5   

#### 매트릭스의 결합

`-` 예제1

In [65]:
X<-rbind(1:5,6:10)
y<-c(1,2)

In [66]:
cbind(X,y)

                y
[1,] 1 2 3 4  5 1
[2,] 6 7 8 9 10 2

`*` 이름을 지우기 위해서는 아래와 같이 한다. 

In [73]:
Xy=cbind(X,y) 
colnames(Xy) = NULL
Xy

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    2    3    4     5   1   
[2,] 6    7    8    9    10   2   

`-` 예제2

In [75]:
X<-rbind(1:5,6:10)
rbind(X,1)

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10  
[3,] 1    1    1    1     1  

`-` 예제3

In [76]:
X<-rbind(1:5,6:10,1:5)
Y<-cbind(c(1,2,3),c(4,5,6),c(7,8,9))

In [77]:
X

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10  
[3,] 1    2    3    4     5  

In [78]:
Y

     [,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9   

In [79]:
cbind(X,Y)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    2    3    4     5   1    4    7   
[2,] 6    7    8    9    10   2    5    8   
[3,] 1    2    3    4     5   3    6    9   

In [80]:
rbind(X,Y)

ERROR: Error in rbind(X, Y): number of columns of matrices must match (see arg 2)


- 드디어 에러!

### 매트릭스 원소 선택 

In [82]:
X<-rbind(1:5,6:10,1:5)
X

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10  
[3,] 1    2    3    4     5  

`-` 예제1

In [89]:
X[,1]

[1] 1 6 1

- 선택된 것은 자동으로 백터화된다. 

In [90]:
x=X[,1]

In [91]:
x

[1] 1 6 1

In [92]:
dim(x)

NULL

In [93]:
dim(x)<-c(3,1)

In [94]:
x

     [,1]
[1,] 1   
[2,] 6   
[3,] 1   

`-` 예제2

In [86]:
X[,1:2]

     [,1] [,2]
[1,] 1    2   
[2,] 6    7   
[3,] 1    2   

`-` 예제3

In [96]:
X[,-1]

     [,1] [,2] [,3] [,4]
[1,] 2    3    4     5  
[2,] 7    8    9    10  
[3,] 2    3    4     5  

`-` 예제4

In [97]:
X[,-(1:2)]

     [,1] [,2] [,3]
[1,] 3    4     5  
[2,] 8    9    10  
[3,] 3    4     5  

`-` 예제5

In [99]:
X[1:2,]

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10  

`-` 예제6

In [100]:
X[1:2,1:3]

     [,1] [,2] [,3]
[1,] 1    2    3   
[2,] 6    7    8   

`-` 예제7 

In [101]:
X[1:2,-1]

     [,1] [,2] [,3] [,4]
[1,] 2    3    4     5  
[2,] 7    8    9    10  

### 벡터관련 연산

`-` 예제1

In [103]:
c(1,2,5) %in% c(1,2,3,4)

[1]  TRUE  TRUE FALSE

`-` 예제2

In [107]:
union(c(1,1,2,2),c(2,3,4))

[1] 1 2 3 4

`-` 예제3

In [109]:
intersect(1:5,2:6)

[1] 2 3 4 5

`-` 예제4

In [132]:
x<-1:5

In [133]:
x%*%x

     [,1]
[1,] 55  

`-` 예제5

In [134]:
x%o%x

     [,1] [,2] [,3] [,4] [,5]
[1,] 1     2    3    4    5  
[2,] 2     4    6    8   10  
[3,] 3     6    9   12   15  
[4,] 4     8   12   16   20  
[5,] 5    10   15   20   25  

### 매트릭스관련 연산 

`-` 예제1: 트랜스포즈

In [111]:
A=cbind(c(1,2,3),c(4,5,6),c(7,8,9))
A

     [,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9   

In [112]:
t(A)

     [,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9   

`-` 예제2: 상수 곱하기

In [113]:
A=cbind(c(1,2,3),c(4,5,6),c(7,8,9))
-A

     [,1] [,2] [,3]
[1,] -1   -4   -7  
[2,] -2   -5   -8  
[3,] -3   -6   -9  

In [119]:
A*2

     [,1] [,2] [,3]
[1,] 2     8   14  
[2,] 4    10   16  
[3,] 6    12   18  

`-` 예제3: 덧셈, 뺄셈

In [137]:
A=cbind(c(1,2,3),c(4,5,6),c(7,8,9))
B=cbind(1:3,1:3,2:4)

In [138]:
A

     [,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9   

In [139]:
B

     [,1] [,2] [,3]
[1,] 1    1    2   
[2,] 2    2    3   
[3,] 3    3    4   

In [140]:
A+B

     [,1] [,2] [,3]
[1,] 2    5     9  
[2,] 4    7    11  
[3,] 6    9    13  

`-` 예제4: 행렬곱셈

In [144]:
A=cbind(1:2,2:3)
A

     [,1] [,2]
[1,] 1    2   
[2,] 2    3   

In [145]:
A %*% A

     [,1] [,2]
[1,] 5     8  
[2,] 8    13  

`-` 예제5: 역행렬

In [129]:
A=rbind(c(0,1),c(2,0))
A

     [,1] [,2]
[1,] 0    1   
[2,] 2    0   

In [130]:
solve(A)

     [,1] [,2]
[1,] 0    0.5 
[2,] 1    0.0 

In [131]:
A %*% solve(A)

     [,1] [,2]
[1,] 1    0   
[2,] 0    1   

### 티블 만드는 방법

`-` 보통은 일부러 만들기보다 생기는 경우가 많을거에요 

`-` 벡터로 만들기 

In [157]:
x<-c(1,2,3)
y<-c('a','b','c')

In [158]:
tb=tibble(x=x,y=y)

In [159]:
tb

  x y
1 1 a
2 2 b
3 3 c

In [160]:
tb$x

[1] 1 2 3

In [161]:
tb$y

[1] "a" "b" "c"

`-` 매트릭스로 만들기 

In [179]:
X=cbind(1:10,31:40)
X

      [,1] [,2]
 [1,]  1   31  
 [2,]  2   32  
 [3,]  3   33  
 [4,]  4   34  
 [5,]  5   35  
 [6,]  6   36  
 [7,]  7   37  
 [8,]  8   38  
 [9,]  9   39  
[10,] 10   40  

In [180]:
tb=as_tibble(X)

In [181]:
tb

   V1 V2
1   1 31
2   2 32
3   3 33
4   4 34
5   5 35
6   6 36
7   7 37
8   8 38
9   9 39
10 10 40

### 티블을 쓰는이유? 

#### mutate

In [183]:
tb %>% mutate(V3=V1**2+V2,V4=-V3,V5=V4-1)

   V1 V2 V3  V4   V5  
1   1 31  32  -32  -33
2   2 32  36  -36  -37
3   3 33  42  -42  -43
4   4 34  50  -50  -51
5   5 35  60  -60  -61
6   6 36  72  -72  -73
7   7 37  86  -86  -87
8   8 38 102 -102 -103
9   9 39 120 -120 -121
10 10 40 140 -140 -141

- 열간의 결합으로 새로운 열을 만들기 편리함 

In [185]:
tb 

   V1 V2
1   1 31
2   2 32
3   3 33
4   4 34
5   5 35
6   6 36
7   7 37
8   8 38
9   9 39
10 10 40

- 원래 데이터프레임은 변화하지 않음. 변화를 위해서는 
```r
tb <- tb %>% mutate(V3=V1**2+V2,V4=-V3,V5=V4-1)
```
를 해야함  

`-` 아래와 같은코드임 

In [187]:
mutate(tb, V3=V1**2+V2,V4=-V3,V5=V4-1)

   V1 V2 V3  V4   V5  
1   1 31  32  -32  -33
2   2 32  36  -36  -37
3   3 33  42  -42  -43
4   4 34  50  -50  -51
5   5 35  60  -60  -61
6   6 36  72  -72  -73
7   7 37  86  -86  -87
8   8 38 102 -102 -103
9   9 39 120 -120 -121
10 10 40 140 -140 -141

#### filter

In [188]:
tb2 <- mutate(tb, V3=V1**2+V2,V4=-V3,V5=V4-1)

In [189]:
tb2

   V1 V2 V3  V4   V5  
1   1 31  32  -32  -33
2   2 32  36  -36  -37
3   3 33  42  -42  -43
4   4 34  50  -50  -51
5   5 35  60  -60  -61
6   6 36  72  -72  -73
7   7 37  86  -86  -87
8   8 38 102 -102 -103
9   9 39 120 -120 -121
10 10 40 140 -140 -141

In [190]:
tb2 %>% filter(V1>5, V3<100) 

  V1 V2 V3 V4  V5 
1 6  36 72 -72 -73
2 7  37 86 -86 -87

#### mutete + filter 가능 

In [192]:
tb

   V1 V2
1   1 31
2   2 32
3   3 33
4   4 34
5   5 35
6   6 36
7   7 37
8   8 38
9   9 39
10 10 40

In [195]:
tb %>% mutate(V3 = (V1-mean(V1))/sd(V1))

   V1 V2 V3        
1   1 31 -1.4863011
2   2 32 -1.1560120
3   3 33 -0.8257228
4   4 34 -0.4954337
5   5 35 -0.1651446
6   6 36  0.1651446
7   7 37  0.4954337
8   8 38  0.8257228
9   9 39  1.1560120
10 10 40  1.4863011

In [196]:
tb %>% mutate(V3 = (V1-mean(V1))/sd(V1)) %>% filter(V3>0.5)

  V1 V2 V3       
1  8 38 0.8257228
2  9 39 1.1560120
3 10 40 1.4863011