# (노트) numpy  

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

## import 

In [239]:
import numpy as np

In [76]:
def test(a,b):
    if id(a)==id(b): 
        print('별명')
    elif id(a)==id(b.base) or id(a.base)==id(a):
        print('뷰')
    elif id(a.base)!=id(None) and id(b.base)!=id(None) and id(a.base)==id(b.base):
        print('공통의 base를 가짐')
    else:
        print('카피이거나 아무 관련 없는 오브젝트')

## 형변환

### flatten

In [95]:
test(x,x.flatten())

카피이거나 아무 관련 없는 오브젝트


### ravel 

In [96]:
test(x,x.ravel())

뷰


## 수학연산

### np.hypot

In [77]:
np.hypot([3,6],[4,8]) # sqrt(np.array([3,6])**2 + np.array([4,8])**2) 

array([ 5., 10.])

### np.norm 

In [78]:
np.linalg.norm([3,6,4,8])

11.180339887498949

### .sum 

In [82]:
A=np.array([[1,2,3,4],[2,4,6,7]])

In [83]:
A

array([[1, 2, 3, 4],
       [2, 4, 6, 7]])

In [84]:
A.shape

(2, 4)

In [85]:
A.sum(axis=0)

array([ 3,  6,  9, 11])

In [86]:
A.sum(axis=1)

array([10, 19])

### np.rollaxis 

In [284]:
A=np.random.randn(2,3,4)
A

array([[[-1.12772522, -0.45553628, -0.46320573,  1.16261367],
        [ 1.14600971,  2.57182336,  0.76275254, -0.39589891],
        [-0.0725335 , -1.46449042, -0.74691515,  0.67791825]],

       [[-0.4056458 ,  1.47866196, -0.28515258,  0.56726787],
        [-0.60418559,  0.84930601,  0.37249086,  0.05278224],
        [-0.59767525, -0.22147117, -0.13686311,  0.27337911]]])

In [287]:
np.rollaxis(A,2,1)

array([[[-1.12772522,  1.14600971, -0.0725335 ],
        [-0.45553628,  2.57182336, -1.46449042],
        [-0.46320573,  0.76275254, -0.74691515],
        [ 1.16261367, -0.39589891,  0.67791825]],

       [[-0.4056458 , -0.60418559, -0.59767525],
        [ 1.47866196,  0.84930601, -0.22147117],
        [-0.28515258,  0.37249086, -0.13686311],
        [ 0.56726787,  0.05278224,  0.27337911]]])

### np.swapaxes

In [101]:
x=np.array([[1,2,3]])
np.swapaxes(x,0,1) # x.T 와 같음 

array([[1],
       [2],
       [3]])

In [102]:
test(x,np.swapaxes(x,0,1))

뷰


In [103]:
test(x,x.T)

뷰


In [104]:
test(np.swapaxes(x,0,1),x.T)

공통의 base를 가짐


### np.expand_dims

In [88]:
x= np.array([1,2])
y= np.expand_dims(x, axis=0)
z= np.expand_dims(x, axis=1)

In [89]:
x

array([1, 2])

In [90]:
y

array([[1, 2]])

In [91]:
z

array([[1],
       [2]])

In [92]:
test(x,y)

뷰


In [93]:
test(x,z)

뷰


### np.fabs

In [238]:
np.fabs([-1.2, 1.2])

array([1.2, 1.2])

## 매트릭스 

### np.linalg.matrix_rank

In [79]:
A=np.array([[1,2,3,4],[2,4,6,8]])
np.linalg.matrix_rank(A)

1

In [80]:
A=np.array([[1,2,3,4],[2,4,6,7]])
np.linalg.matrix_rank(A)

2

### np.linalg.det 

In [81]:
np.linalg.det(A.T @ A)

0.0

### np.trace 

In [114]:
A = np.array([[1,2,3],[4,5,6],[7,8,8]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [115]:
np.trace(a)

14

### np.diagonal, np.diag

In [116]:
A = np.array([[1,2,3],[4,5,6],[7,8,8]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [117]:
np.diag(A)

array([1, 5, 8])

In [118]:
np.diagonal(A)

array([1, 5, 8])

In [119]:
A.diagonal()

array([1, 5, 8])

In [120]:
test(A,np.diag(A))

뷰


In [121]:
test(A,np.diagonal(A))

뷰


In [124]:
test(A,A.diagonal())

뷰


## 배열생성 

### np.eye: 단위행렬 생성 

`-` np.identity 보다 조금 더 다양한 기능이 있음 

In [141]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [142]:
np.eye(4,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [144]:
np.eye(4,4,k=-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [145]:
np.eye(4,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [146]:
np.eye(4,4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.identity

In [147]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.diag

In [268]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

- 대각행렬생성 

In [269]:
np.diag(np.diag([1,2,3,4]))

array([1, 2, 3, 4])

- 생성된 행렬을 다시 대각화할때도 사용할수 있음 

### np.tril

In [154]:
A=np.arange(1,17).reshape(4,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [155]:
np.tril(A)

array([[ 1,  0,  0,  0],
       [ 5,  6,  0,  0],
       [ 9, 10, 11,  0],
       [13, 14, 15, 16]])

In [156]:
np.tril(A,k=-1)

array([[ 0,  0,  0,  0],
       [ 5,  0,  0,  0],
       [ 9, 10,  0,  0],
       [13, 14, 15,  0]])

### np.triu

In [160]:
A=np.arange(1,17).reshape(4,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [161]:
np.triu(A)

array([[ 1,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 0,  0, 11, 12],
       [ 0,  0,  0, 16]])

In [162]:
np.triu(A,k=1)

array([[ 0,  2,  3,  4],
       [ 0,  0,  7,  8],
       [ 0,  0,  0, 12],
       [ 0,  0,  0,  0]])

### np.zeros

In [169]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [166]:
A=np.zeros((4,4))
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [210]:
A=np.arange(1,17).reshape(4,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [211]:
np.zeros_like(A)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### np.empty

In [212]:
np.empty(16) ## 초기화하지 않음. 메모리에 있는 값을 그대로 쓴다. 

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       2.14321575e-312, 5.30276956e+180, 6.00736842e-067, 5.16823469e+097,
       1.11032409e-047, 4.09934544e+126, 4.25223142e+180, 7.48543529e+247,
       2.32363010e+251, 6.11130817e+223, 2.59903818e-144, 1.17687403e-047])

In [213]:
np.empty(16).reshape(4,4)

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [2.14321575e-312, 5.30276956e+180, 6.00736842e-067,
        5.16823469e+097],
       [1.11032409e-047, 4.09934544e+126, 4.25223142e+180,
        7.48543529e+247],
       [2.32363010e+251, 6.11130817e+223, 2.59903818e-144,
        1.17687403e-047]])

## 평가

### np.array_equal

In [214]:
np.array_equal([1, 2], [1, 2])

True

### np.array_equiv

In [215]:
np.array_equiv([1, 2], [[1, 2], [1, 2]])

True

In [216]:
np.array_equal([1, 2], [[1, 2], [1, 2]])

False

### np.allclose 

In [233]:
I1 = np.eye(4) 
I2 = I1+1e-10

In [234]:
I1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [235]:
I2

array([[1.e+00, 1.e-10, 1.e-10, 1.e-10],
       [1.e-10, 1.e+00, 1.e-10, 1.e-10],
       [1.e-10, 1.e-10, 1.e+00, 1.e-10],
       [1.e-10, 1.e-10, 1.e-10, 1.e+00]])

In [236]:
np.allclose(I1,I2)

True

## 결합

### np.c_

In [253]:
a=np.array([1,2,3])
b=np.array([3,4,5])

In [254]:
np.c_[a,b]

array([[1, 3],
       [2, 4],
       [3, 5]])

### np.r_

In [255]:
a=np.array([1,2,3])
b=np.array([3,4,5])

In [256]:
np.r_[a,b]

array([1, 2, 3, 3, 4, 5])

## 난수생성 

### np.random.rand

In [263]:
np.random.rand(4,4) ## uniform

array([[0.8617704 , 0.37552256, 0.66993283, 0.61025431],
       [0.80114982, 0.17587509, 0.91847435, 0.06284125],
       [0.9213696 , 0.7914015 , 0.33548067, 0.9816348 ],
       [0.63528142, 0.10903412, 0.97652282, 0.97116242]])

### np.random.randn

In [265]:
np.random.randn(4,4) ## normal

array([[ 0.20741595,  0.01043493,  1.10312322, -0.81210193],
       [-1.07920239, -0.60986871, -0.79381177, -0.20408819],
       [-0.2992278 ,  1.63919626,  1.25238605, -0.23849863],
       [ 0.47920461, -0.72575884, -0.28330463, -0.03245252]])

### np.random.randint

In [297]:
np.random.randint(2,size=(4,4))

array([[1, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 1, 1, 0]])

In [298]:
np.random.randint(3,size=(4,4))

array([[0, 1, 0, 2],
       [2, 2, 2, 2],
       [2, 0, 2, 2],
       [0, 0, 1, 2]])

## 인덱스

In [308]:
A=np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [309]:
A[(0,0)] # A[0,0]와 같음

0