# (연구) Spectral Clustering 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [논문연구]

In [1]:
from sklearn.datasets import make_circles
from sklearn.neighbors import kneighbors_graph
import numpy as np

# create the data
X, labels = make_circles(n_samples=500, noise=0.1, factor=.2)

# use the nearest neighbor graph as our adjacency matrix
A = kneighbors_graph(X, n_neighbors=5).toarray()
print(A)

# [[0. 0. 0. ... 0. 0. 0.]
#  [0. 0. 0. ... 0. 0. 0.]
#  [0. 0. 0. ... 0. 0. 0.]
#  ...
#  [0. 0. 0. ... 0. 1. 0.]
#  [0. 0. 0. ... 0. 0. 0.]
#  [0. 0. 0. ... 0. 0. 0.]]
 
# create the graph laplacian
D = np.diag(A.sum(axis=1))
L = D-A

# find the eigenvalues and eigenvectors
vals, vecs = np.linalg.eig(L)

# sort
vecs = vecs[:,np.argsort(vals)]
vals = vals[np.argsort(vals)]

# use Fiedler value to find best cut to separate data
clusters = vecs[:,1] > 0

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [2]:
clusters

array([False, False,  True,  True,  True,  True, False, False, False,
        True,  True, False, False,  True,  True,  True, False, False,
       False,  True, False,  True, False, False, False, False,  True,
        True,  True,  True, False, False, False, False, False,  True,
        True, False,  True, False, False, False, False, False,  True,
        True,  True, False,  True, False,  True,  True, False, False,
       False,  True,  True, False, False, False,  True,  True, False,
       False,  True, False,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True, False, False, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True, False, False,  True, False, False,  True,  True, False,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False, False,  True,  True,  True,  True, False, False,  True,
       False, False, False,  True,  True, False,  True,  True, False,
       False, False,