# (노트) Hook

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [빅데이터분석]

In [358]:
import torch 

In [360]:
X=torch.tensor([1.5])

In [361]:
X

tensor([1.5000])

In [362]:
list(net.parameters())

[Parameter containing:
 tensor([[-0.3335]], requires_grad=True),
 Parameter containing:
 tensor([[-0.1402]], requires_grad=True)]

In [363]:
net(X)

tensor([0.0701], grad_fn=<SqueezeBackward3>)

In [364]:
1.5*0.3609

0.54135

In [375]:
net = torch.nn.Sequential(
    torch.nn.Linear(in_features=1,out_features=1,bias=False),
    torch.nn.Linear(in_features=1,out_features=1,bias=False))

In [376]:
def hook_fn(m,i,o): 
    #print('module:', m)
    print('input:', i)
    #print('output:', o)

In [377]:
net.register_forward_hook(hook_fn)

In [378]:
net(X)

input: (tensor([1.5000]),)


tensor([-0.1610], grad_fn=<SqueezeBackward3>)