# (노트) 뷰와 사본

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [파이썬특강]

### import 

In [3]:
import numpy as np 
import pandas as pd

### numpy 

In [4]:
def show(a):
    print('*id: %s' % id(a)) 
    print('*type: %s' % type(a))
    print('*base:')    
    print(a.base)
    print('*base id: %s' %id(a.base))    
    #print('\n')
    print('*value:')    
    print(a)
    #print('\n')

### 참조 

`-` a를 선언, b는 a의 참조 

In [77]:
a=np.array([[1,2],[3,4]])
b=a ## 이거 shallow copy 아님. 인터넷에 자꾸 shallow copy라고 주장하는 사람들 있음. 

`-` shape을 조사하자 

In [78]:
a.shape

(2, 2)

In [79]:
b.shape

(2, 2)

`-` shape의 모양을 직접확인: (2,2) shape으로 잘 정리되어 있음 

In [80]:
a

array([[1, 2],
       [3, 4]])

In [81]:
b

array([[1, 2],
       [3, 4]])

`-` a의 shape을 바꾸면? $\to$ b도 따라서 바뀐다. 

In [82]:
a.shape=(4,)

In [83]:
a

array([1, 2, 3, 4])

In [84]:
b

array([1, 2, 3, 4])

### view 

`-` a를 선언, b는 a의 view. (b는 a의 shallow copy 라고 부르기도 함) 

In [110]:
a=np.array([[1,2],[3,4]])
b=a.view() ## 이게 shallow copy 

`-` a,b 의 shape확인 

In [111]:
a

array([[1, 2],
       [3, 4]])

In [112]:
b

array([[1, 2],
       [3, 4]])

`-` a의 shape을 바꿔도 b는 바뀌지 않음. 

In [113]:
a.shape=(4,)

In [114]:
a

array([1, 2, 3, 4])

In [115]:
b

array([[1, 2],
       [3, 4]])

`-` 하지만 값을 바꾸면 같이 바뀐다. 

In [116]:
a[0]=100

In [117]:
a

array([100,   2,   3,   4])

In [118]:
b

array([[100,   2],
       [  3,   4]])

### copy 

`-` a를 선언, b는 a의 카피 

In [125]:
a=np.array([[1,2],[3,4]])
b=a.copy()

`-` a의 shape을 바꿔도 b는 적용되지 않음 (이건 당연하죠) 

In [128]:
a.shape = (4,)

In [129]:
a

array([1, 2, 3, 4])

In [130]:
b

array([[1, 2],
       [3, 4]])

`-` 그리고 a[0]의 값을 바꿔도 b에는 적용되지 않음 

In [131]:
a[0]=100

In [132]:
a

array([100,   2,   3,   4])

In [133]:
b

array([[1, 2],
       [3, 4]])

***copy의 한계(?)***

In [200]:
a=np.array([1,[1,2]],'O')
b=a.copy()

In [201]:
a

array([1, list([1, 2])], dtype=object)

In [202]:
a[0]=2

In [203]:
a

array([2, list([1, 2])], dtype=object)

In [204]:
b

array([1, list([1, 2])], dtype=object)

In [205]:
a[1][0]=100

In [206]:
a

array([2, list([100, 2])], dtype=object)

In [207]:
b

array([1, list([100, 2])], dtype=object)

***더 깊은 복사: 이게 필요할까?***

In [208]:
import copy 

In [215]:
a=np.array([1,[1,2]],'O')
b=copy.deepcopy(a)

In [218]:
a[1][0]=100

In [219]:
a

array([1, list([100, 2])], dtype=object)

In [220]:
b

array([1, list([1, 2])], dtype=object)

### 개념 