# (노트) 파이토치 
> 미완성

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이토치]

### 텐서

`-` 예제1: view()

In [1]:
import torch

In [7]:
x1=torch.tensor([[1,2],[3,4]])

In [25]:
x1

tensor([[1, 2],
        [3, 4]])

In [9]:
x1.view(4,1)

tensor([[1],
        [2],
        [3],
        [4]])

In [11]:
x1.view(1,-1)

tensor([[1, 2, 3, 4]])

In [12]:
x1.view(-1,1)

tensor([[1],
        [2],
        [3],
        [4]])

`-` 예제2: t()

In [15]:
import torch

In [16]:
x2=torch.tensor([[10,20,30],[40,50,60]])
x2

tensor([[10, 20, 30],
        [40, 50, 60]])

In [17]:
x2.t()

tensor([[10, 40],
        [20, 50],
        [30, 60]])

`-` 예제3: cat()

In [26]:
import torch
x1=torch.tensor([[1,2],[3,4]])
x2=torch.tensor([[10,20,30],[40,50,60]])

In [27]:
x1

tensor([[1, 2],
        [3, 4]])

In [28]:
x2

tensor([[10, 20, 30],
        [40, 50, 60]])

In [29]:
torch.cat([x1,x2],dim=1) # cbind 

tensor([[ 1,  2, 10, 20, 30],
        [ 3,  4, 40, 50, 60]])

In [31]:
torch.cat([x1,x2.t()],dim=0) # rbind

tensor([[ 1,  2],
        [ 3,  4],
        [10, 40],
        [20, 50],
        [30, 60]])

In [32]:
torch.cat([x1,x2.t()]) # default is dim=0 

tensor([[ 1,  2],
        [ 3,  4],
        [10, 40],
        [20, 50],
        [30, 60]])

> Note: 차원이 안맞으면 에러가 난다. 

In [35]:
torch.cat([x1,x2],dim=0)

RuntimeError: Sizes of tensors must match except in dimension 0. Got 2 and 3 in dimension 1 (The offending index is 1)

In [34]:
torch.cat([x1,x2.t()],dim=1) 

RuntimeError: Sizes of tensors must match except in dimension 1. Got 2 and 3 in dimension 0 (The offending index is 1)

`-` 예제4: transpose()

In [87]:
#collapse-output
x3=torch.rand(100,64,32,3)
x3

tensor([[[[0.3130, 0.8518, 0.3898],
          [0.3694, 0.6313, 0.7090],
          [0.3276, 0.5215, 0.8826],
          ...,
          [0.2538, 0.5051, 0.5540],
          [0.5399, 0.7080, 0.5065],
          [0.1091, 0.9843, 0.6071]],

         [[0.1565, 0.5755, 0.0519],
          [0.2501, 0.5027, 0.3488],
          [0.9004, 0.8383, 0.9017],
          ...,
          [0.2876, 0.6128, 0.9059],
          [0.0907, 0.0286, 0.7585],
          [0.2830, 0.0131, 0.8836]],

         [[0.1643, 0.8675, 0.0719],
          [0.5792, 0.2316, 0.3648],
          [0.1261, 0.4686, 0.1623],
          ...,
          [0.2359, 0.9745, 0.2561],
          [0.5320, 0.2315, 0.4846],
          [0.4078, 0.8382, 0.9577]],

         ...,

         [[0.2403, 0.7544, 0.6342],
          [0.0213, 0.6327, 0.1930],
          [0.1198, 0.3287, 0.7838],
          ...,
          [0.0995, 0.1922, 0.7497],
          [0.0457, 0.0516, 0.5522],
          [0.8936, 0.6733, 0.0975]],

         [[0.5540, 0.4544, 0.4415],
          [0.0123

In [54]:
x3.shape # 63*32*3 인 데이터가 100개 

torch.Size([100, 64, 32, 3])

In [81]:
print('.transpose(0,1):', x3.shape, '-->', x3.transpose(0,1).shape)
print('.transpose(1,0):', x3.shape, '-->', x3.transpose(1,0).shape)
print('.transpose(0,2):', x3.shape, '-->', x3.transpose(0,2).shape)
print('.transpose(2,0):', x3.shape, '-->', x3.transpose(2,0).shape)

.transpose(0,1): torch.Size([100, 64, 32, 3]) --> torch.Size([64, 100, 32, 3])
.transpose(1,0): torch.Size([100, 64, 32, 3]) --> torch.Size([64, 100, 32, 3])
.transpose(0,2): torch.Size([100, 64, 32, 3]) --> torch.Size([32, 64, 100, 3])
.transpose(2,0): torch.Size([100, 64, 32, 3]) --> torch.Size([32, 64, 100, 3])


In [85]:
x3.shape, x3.transpose(2,0).shape

(torch.Size([100, 64, 32, 3]), torch.Size([32, 64, 100, 3]))

In [84]:
print('.transpose(0,1):', x3.shape, '-->', x3.transpose(0,1).shape)
print('.transpose(0,2):', x3.shape, '-->', x3.transpose(0,2).shape)
print('.transpose(0,3):', x3.shape, '-->', x3.transpose(0,3).shape)
print('.transpose(1,0):', x3.shape, '-->', x3.transpose(1,0).shape)
print('.transpose(1,2):', x3.shape, '-->', x3.transpose(1,2).shape)
print('.transpose(1,3):', x3.shape, '-->', x3.transpose(1,3).shape)
print('.transpose(2,0):', x3.shape, '-->', x3.transpose(2,0).shape)
print('.transpose(2,1):', x3.shape, '-->', x3.transpose(2,1).shape)
print('.transpose(2,3):', x3.shape, '-->', x3.transpose(2,3).shape)
print('.transpose(3,0):', x3.shape, '-->', x3.transpose(3,0).shape)
print('.transpose(3,1):', x3.shape, '-->', x3.transpose(3,1).shape)
print('.transpose(3,2):', x3.shape, '-->', x3.transpose(3,2).shape)

.transpose(0,1): torch.Size([100, 64, 32, 3]) --> torch.Size([64, 100, 32, 3])
.transpose(0,2): torch.Size([100, 64, 32, 3]) --> torch.Size([32, 64, 100, 3])
.transpose(0,3): torch.Size([100, 64, 32, 3]) --> torch.Size([3, 64, 32, 100])
.transpose(1,0): torch.Size([100, 64, 32, 3]) --> torch.Size([64, 100, 32, 3])
.transpose(1,2): torch.Size([100, 64, 32, 3]) --> torch.Size([100, 32, 64, 3])
.transpose(1,3): torch.Size([100, 64, 32, 3]) --> torch.Size([100, 3, 32, 64])
.transpose(2,0): torch.Size([100, 64, 32, 3]) --> torch.Size([32, 64, 100, 3])
.transpose(2,1): torch.Size([100, 64, 32, 3]) --> torch.Size([100, 32, 64, 3])
.transpose(2,3): torch.Size([100, 64, 32, 3]) --> torch.Size([100, 64, 3, 32])
.transpose(3,0): torch.Size([100, 64, 32, 3]) --> torch.Size([3, 64, 32, 100])
.transpose(3,1): torch.Size([100, 64, 32, 3]) --> torch.Size([100, 3, 32, 64])
.transpose(3,2): torch.Size([100, 64, 32, 3]) --> torch.Size([100, 64, 3, 32])


In [63]:
x3.transpose(0,2).shape

torch.Size([32, 64, 100, 3])

In [64]:
x3.transpose(2,0).shape

torch.Size([32, 64, 100, 3])

In [72]:
x3.transpose(0,3).shape

torch.Size([3, 64, 32, 100])

In [71]:
x3.transpose(3,0).shape

torch.Size([3, 64, 32, 100])

In [73]:
x3.transpose(1,2).shape

torch.Size([100, 32, 64, 3])

In [ ]:
x3.transpose(1,2).shape