# (노트) 배치정규화

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [빅데이터분석]

### 개념 

In [1]:
import torch

In [39]:
import numpy as np

In [40]:
bn=torch.nn.BatchNorm1d(1)

In [41]:
x=torch.Tensor([[0.1],[0.2],[0.3]])

In [42]:
x

tensor([[0.1000],
        [0.2000],
        [0.3000]])

In [43]:
bn.weight, bn.bias

(Parameter containing:
 tensor([1.], requires_grad=True),
 Parameter containing:
 tensor([0.], requires_grad=True))

In [44]:
np.array(bn(x).tolist()).round(4)

array([[-1.2238],
       [ 0.    ],
       [ 1.2238]])

In [47]:
np.std([0.1,0.2,0.3])

0.0816496580927726

In [48]:
np.mean([0.1,0.2,0.3])

0.20000000000000004

In [49]:
-0.1/0.0816496580927726

-1.2247448713915892

In [50]:
0.1/0.0816496580927726

1.2247448713915892

In [52]:
bn.weight.data=torch.Tensor([2.0])

In [54]:
bn(x)

tensor([[-2.4477e+00],
        [ 1.6831e-07],
        [ 2.4477e+00]], grad_fn=<NativeBatchNormBackward0>)