# (시험) 빅데이터분석 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈
- hide: true
- categories: [빅데이터분석]

## asdf

In [288]:
import torch 

In [289]:
net = torch.nn.Linear(in_features=1,out_features=1,bias=False)

In [291]:
X=torch.tensor([1.5])

In [292]:
X

tensor([1.5000])

In [294]:
net.weight

Parameter containing:
tensor([[0.3609]], requires_grad=True)

In [295]:
net(X)

tensor([0.5413], grad_fn=<SqueezeBackward3>)

In [296]:
1.5*0.3609

0.54135