# (노트) 뷰와 사본

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [파이썬특강]

### import 

In [468]:
import numpy as np 
import pandas as pd

### numpy 

In [688]:
def show(a):
    print('*id: %s' % id(a)) 
    print('*type: %s' % type(a))
    print('*base:')    
    print(a.base)
    print('*base id: %s' %id(a.base))    
    #print('\n')
    print('*value:')    
    print(a)
    #print('\n')

In [689]:
show(a)

*id: 139636299426864
*type: <class 'numpy.ndarray'>
*base:
None
*base id: 94394120088832
*value:
[[1 2]
 [3 4]]


`-` =

In [690]:
a=np.array([[1,2],[3,4]])

In [691]:
b=a

In [692]:
a[0]=np.array([-1,-2])

In [693]:
a

array([[-1, -2],
       [ 3,  4]])

In [694]:
b

array([[-1, -2],
       [ 3,  4]])

(해설) 

In [695]:
show(a)

*id: 139636299426384
*type: <class 'numpy.ndarray'>
*base:
None
*base id: 94394120088832
*value:
[[-1 -2]
 [ 3  4]]


In [696]:
show(b)

*id: 139636299426384
*type: <class 'numpy.ndarray'>
*base:
None
*base id: 94394120088832
*value:
[[-1 -2]
 [ 3  4]]


In [697]:
show(a[0])

*id: 139636299475440
*type: <class 'numpy.ndarray'>
*base:
[[-1 -2]
 [ 3  4]]
*base id: 139636299426384
*value:
[-1 -2]


In [699]:
show(b[0])

*id: 139636299427728
*type: <class 'numpy.ndarray'>
*base:
[[-1 -2]
 [ 3  4]]
*base id: 139636299426384
*value:
[-1 -2]


In [700]:
show(a[1])

*id: 139636299420080
*type: <class 'numpy.ndarray'>
*base:
[[-1 -2]
 [ 3  4]]
*base id: 139636299426384
*value:
[3 4]


In [701]:
show(b[1])

*id: 139636299475440
*type: <class 'numpy.ndarray'>
*base:
[[-1 -2]
 [ 3  4]]
*base id: 139636299426384
*value:
[3 4]


`-` .view()

In [747]:
a=np.array([[1,2],[3,4]])

In [748]:
b=a.view()

In [749]:
a[0]=np.array([-1,-2])

In [750]:
a

array([[-1, -2],
       [ 3,  4]])

In [751]:
b

array([[-1, -2],
       [ 3,  4]])

In [752]:
b.base

array([[-1, -2],
       [ 3,  4]])

In [755]:
id(b)

139636029394736

(해설) 

In [716]:
show(a)

*id: 139636469912464
*type: <class 'numpy.ndarray'>
*base:
None
*base id: 94394120088832
*value:
[[-1 -2]
 [ 3  4]]


In [717]:
show(b)

*id: 139636299420080
*type: <class 'numpy.ndarray'>
*base:
[[-1 -2]
 [ 3  4]]
*base id: 139636469912464
*value:
[[-1 -2]
 [ 3  4]]


In [718]:
show(a[0])

*id: 139636299426960
*type: <class 'numpy.ndarray'>
*base:
[[-1 -2]
 [ 3  4]]
*base id: 139636469912464
*value:
[-1 -2]


In [719]:
show(b[0])

*id: 139636299485072
*type: <class 'numpy.ndarray'>
*base:
[[-1 -2]
 [ 3  4]]
*base id: 139636469912464
*value:
[-1 -2]


In [725]:
show(a.reshape(-1))

*id: 139636299493072
*type: <class 'numpy.ndarray'>
*base:
[[-1 -2]
 [ 3  4]]
*base id: 139636469912464
*value:
[-1 -2  3  4]


`-` .copy()

In [ ]:
a.

`-` copy는 shollow ? 

In [649]:
a=np.array([-0.1, np.ones((3,))],'O')

In [650]:
a

array([-0.1, array([1., 1., 1.])], dtype=object)

In [651]:
b=a.copy()

In [652]:
b

array([-0.1, array([1., 1., 1.])], dtype=object)

In [653]:
id(a)

139636299475728

In [654]:
id(b)

139636299425616

In [655]:
id(a[0])

139636299477744

In [656]:
id(b[0])

139636299477744

In [657]:
id(a[1])

139636299475344

In [658]:
id(b[1])

139636299475344

In [659]:
b[0]=1

In [660]:
a

array([-0.1, array([1., 1., 1.])], dtype=object)

In [661]:
b

array([1, array([1., 1., 1.])], dtype=object)

In [662]:
b[1][0]=100

In [663]:
b

array([1, array([100.,   1.,   1.])], dtype=object)

In [664]:
a

array([-0.1, array([100.,   1.,   1.])], dtype=object)

`-` deepcopy 

In [666]:
import copy 
a=np.array([-0.1, np.ones((3,))],'O')
b=copy.deepcopy(a)

In [667]:
b

array([-0.1, array([1., 1., 1.])], dtype=object)

In [668]:
b[1][0]=100

In [669]:
b

array([-0.1, array([100.,   1.,   1.])], dtype=object)

In [670]:
a

array([-0.1, array([1., 1., 1.])], dtype=object)

In [759]:
a = np.array([1,2,3,4])
view_of_a = a.view()
reference_of_a = a.copy()