# (노트) 뷰와 사본 (넘파이)

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [파이썬특강]

### import 

In [1]:
import numpy as np 

### numpy공부 1단계 (복습) 

`-` 넘파이의 위력 

In [2]:
a=np.array([1,2,3])
l=[1,2,3]

`-` 사칙연산 브로드캐스팅 

In [6]:
a+1

array([2, 3, 4])

In [7]:
l+1

TypeError: can only concatenate list (not "int") to list

In [8]:
a*2

array([2, 4, 6])

In [9]:
l*2

[1, 2, 3, 1, 2, 3]

In [10]:
a/2

array([0.5, 1. , 1.5])

In [12]:
l/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [13]:
a-2

array([-1,  0,  1])

In [14]:
l-2

TypeError: unsupported operand type(s) for -: 'list' and 'int'

`-` 기타수학연산가능 

In [17]:
np.sqrt(a), np.sqrt(l)

(array([1.        , 1.41421356, 1.73205081]),
 array([1.        , 1.41421356, 1.73205081]))

In [18]:
np.log(a), np.log(l)

(array([0.        , 0.69314718, 1.09861229]),
 array([0.        , 0.69314718, 1.09861229]))

### numpy공부 2단계 

#### 2차원 배열과 연립1차방정식

`-` 아래의 연립방정식 고려 

$\begin{cases}
y + z + w= 3 \\
x + z + w= 3 \\
x + y + w= 3 \\ 
x + y + z= 3 \\ 
\end{cases}$ 

`-` 행렬표현은? 

$\begin{bmatrix}
0 & 1 & 1 & 1 \\ 
1 & 0 & 1 & 1 \\
1 & 1 & 0 & 1 \\ 
1 & 1 & 1 & 0 \\ 
\end{bmatrix} \begin{bmatrix} x \\ y \\ z \\ w \end{bmatrix} = \begin{bmatrix} 3 \\ 3 \\ 3 \\ 3  \end{bmatrix}$

In [80]:
A = [[0,1,1,1],[1,0,1,1],[1,1,0,1],[1,1,1,0]] 
A

[[0, 1, 1, 1], [1, 0, 1, 1], [1, 1, 0, 1], [1, 1, 1, 0]]

In [81]:
A2 = np.array(A)
A2

array([[0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]])

`-` A에서 원소인덱싱 

In [82]:
A[0][0], A[0][1], A[0][2], A[0][3]

(0, 1, 1, 1)

In [83]:
A[1][0], A[1][1], A[1][2], A[1][3]

(1, 0, 1, 1)

In [84]:
A[2][0], A[2][1], A[2][2], A[2][3]

(1, 1, 0, 1)

In [85]:
A[3][0], A[3][1], A[3][2], A[3][3]

(1, 1, 1, 0)

`-` A2에서 원소인덱싱 

In [86]:
A2[0][0], A2[0][1], A2[0][2], A2[0][3]

(0, 1, 1, 1)

In [87]:
A2[1][0], A2[1][1], A2[1][2], A2[1][3]

(1, 0, 1, 1)

In [88]:
A2[2][0], A2[2][1], A2[2][2], A2[2][3]

(1, 1, 0, 1)

In [89]:
A2[3][0], A2[3][1], A2[3][2], A2[3][3]

(1, 1, 1, 0)

`-` 이렇게 해도된다? (넘파이에서 제시하는 신기술, R에서는 기본탑재기능) 

In [90]:
A2[0,0], A2[0,1], A2[0,2], A2[0,3]

(0, 1, 1, 1)

In [91]:
A2[1,0], A2[1,1], A2[1,2], A2[1,3]

(1, 0, 1, 1)

In [92]:
A2[2,0], A2[2,1], A2[2,2], A2[2,3]

(1, 1, 0, 1)

`-` 슬라이싱!

In [93]:
A2[0,:] ## R에서는 A2[0,]

array([0, 1, 1, 1])

In [94]:
A2[1,:] ## R에서는 A2[1,]

array([1, 0, 1, 1])

In [95]:
A2[2,:] ## R에서는 A2[2,]

array([1, 1, 0, 1])

In [96]:
A2[3,:] ## R에서는 A2[2,]

array([1, 1, 1, 0])

`-` 아무튼 문제를 더 풀어보자. 

$\begin{bmatrix}
0 & 1 & 1 & 1 \\ 
1 & 0 & 1 & 1 \\
1 & 1 & 0 & 1 \\ 
1 & 1 & 1 & 0 \\ 
\end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ x_4 \end{bmatrix} = \begin{bmatrix} 3 \\ 3 \\ 3 \\ 3  \end{bmatrix}
\Longleftrightarrow {\bf A} {\bf x} = {\bf b} 
$

In [97]:
A2

array([[0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]])

In [98]:
b=np.array([3,3,3,3])

In [99]:
np.linalg.inv(A2) @ b ## solve(A2) 

array([1., 1., 1., 1.])

#### 인덱싱

`-` 선언 

In [116]:
l=[11,22,33,44,55,66]
a=np.array(l)

`-` 인덱스로 접근 

In [117]:
l[0],l[1],l[2],l[3],l[4],l[5]

(11, 22, 33, 44, 55, 66)

In [120]:
a[0],a[1],a[2],a[3],a[4],a[5]

(11, 22, 33, 44, 55, 66)

`-` `:`이용 (슬라이싱) 

In [125]:
l[2:4] ## index=2에서 출발해서 index=4에서 멈춘다. (4는 포함하지 않음) 

[33, 44]

In [126]:
a[2:4]

array([33, 44])

이것때문에 마지막 원소까지 포함하려면 너무 헷갈리게도 아래와 같이 해야한다. 

In [133]:
l[6] ## index=6에 해당하는 원소는 없지만 

IndexError: list index out of range

In [134]:
l[2:6] ## 이렇게 해야지 index=2,3,4,5 에 해당하는 원소가 출력됨 

[33, 44, 55, 66]

In [135]:
a[2:6]

array([33, 44, 55, 66])

다행히도 위에서 6은 생략가능하다. 즉 아래와 같이 해도 마지막원소까지 포함해준다. 

In [138]:
l[2:]

[33, 44, 55, 66]

In [139]:
a[2:]

array([33, 44, 55, 66])

비슷한 논리로 index=0 역시 생략가능하다 

In [141]:
l[0:2], a[0:2]

([11, 22], array([11, 22]))

In [142]:
l[:2], a[:2]

([11, 22], array([11, 22]))

`-` 정수배열에 의한 인덱싱 

In [145]:
a

array([11, 22, 33, 44, 55, 66])

In [146]:
a[[0,2,4]]

array([11, 33, 55])

`-` 부울값에 의한 인덱싱 

In [147]:
a

array([11, 22, 33, 44, 55, 66])

In [148]:
a[ [True,False,True,False,True,False] ]

array([11, 33, 55])

응용하면? 

In [150]:
a < 33

array([ True,  True, False, False, False, False])

In [151]:
a[a<33]

array([11, 22])

리스트는 불가능 

In [155]:
l

[11, 22, 33, 44, 55, 66]

In [156]:
l<33 ## 여기서부터 에러남 

TypeError: '<' not supported between instances of 'list' and 'int'

#### reshape 

`-` reshape

In [226]:
l=[11,22,33,44,55,66]
a=np.array(l)

In [227]:
a ## 길이가 6인 벡터

array([11, 22, 33, 44, 55, 66])

In [228]:
a.reshape(2,3)

array([[11, 22, 33],
       [44, 55, 66]])

In [229]:
a ## reshape은 a자체를 변화시키진 않음

array([11, 22, 33, 44, 55, 66])

In [230]:
b = a.reshape(3,2)
b

array([[11, 22],
       [33, 44],
       [55, 66]])

`-` 다시 b를 a처럼 바꾸고싶다면? 

In [231]:
b.reshape(6)

array([11, 22, 33, 44, 55, 66])

In [232]:
b.flatten()

array([11, 22, 33, 44, 55, 66])

In [233]:
b.reshape(-1)

array([11, 22, 33, 44, 55, 66])

In [235]:
b.ravel()

array([11, 22, 33, 44, 55, 66])

### numpy공부 3단계 

`-` 2차원 array a,b를 선언하자. 

In [252]:
a=np.array([11,22,33,44]).reshape(2,2)
a

array([[11, 22],
       [33, 44]])

In [253]:
b=np.array([11,22,33,44,55,66]).reshape(2,3)
b

array([[11, 22, 33],
       [44, 55, 66]])

`-` 속성을 알아보자. 

In [254]:
a.shape, b.shape

((2, 2), (2, 3))

In [255]:
a.size, b.size

(4, 6)

In [256]:
a.itemsize, b.itemsize ## 8비트

(8, 8)

- ?

In [257]:
a.strides, b.strides

((16, 8), (24, 8))

- ?

뭔가 느낌이 오긴하는데.. 확실하지 않음 

***a의 모양***

In [265]:
a

array([[11, 22],
       [33, 44]])

***b의 모양***

In [266]:
b

array([[11, 22, 33],
       [44, 55, 66]])

`-` itemsize와 stride의 의미를 유추하여 보자. 

In [258]:
c = np.array([11,22,33,44]).reshape(4,1)
d = np.array([11,22,33,44])

***c의 모양***

In [259]:
c

array([[11],
       [22],
       [33],
       [44]])

***d의 모양***

In [260]:
d

array([11, 22, 33, 44])

`-` a,b,c,d 속성비교 

In [269]:
a.shape, b.shape, c.shape, d.shape ## 차원 

((2, 2), (2, 3), (4, 1), (4,))

In [270]:
a.size, b.size, c.size, d.size ## 원소의수 

(4, 6, 4, 4)

In [272]:
a.itemsize, b.itemsize, c.itemsize, d.itemsize ## 항상 8?

(8, 8, 8, 8)

In [283]:
a.strides, b.strides, c.strides, d.strides ## 차원과 관련은 있는데.. + 8의 배수네?

((16, 8), (24, 8), (8, 8), (8,))

`-` itemsize와 strides는 무엇일까? 
- itemsize: 숫자하나를 저장하는데 필요한 공간 
- strides: (다음행으로 가기위해 jump해야하는 메모리공간수, 다음열로 가기위해서 jump해야하는 메모리공간수) $\to$ 메모리에는 기본적으로 행방향으로 길게 자료가 늘어져있다. 

`-` strides에 대한 추가해설 

**(오브젝트 a)**

2차원 자료형 a는 아래와 같은 형태로 인간눈에 보이지만 

In [284]:
a

array([[11, 22],
       [33, 44]])

실제로 메모리구조상에는 아래와 같이 저장되어 있음 

In [285]:
a.reshape(-1)

array([11, 22, 33, 44])

a의 첫번째 원소 11에서 아래로 한칸가면(=다음행으로 이동) 22를 얻고, 아래로 한칸가면 (=다음열로 이동) 33이 나온다. 

인간눈에는 똑같은 한칸이지만 컴퓨터는 다르다. 

컴퓨터 입장에서는 아래로한칸 = 16칸의 메모리공간을 이동, 오른쪽으로 한칸 = 8칸의 메모리공간을 이동해야한다. 

인간입장에서 아래로 한칸, 오른쪽으로 한칸가라는 것은 컴퓨터 입장에서는 16칸 + 8칸 이동하라는 것과 같다. (너무 어렵다..) 

하여튼 이정보를 어딘가에 기록해야 컴퓨터도 일할 수 있는데, 이러한 정보가 바로 strides에 기록되어 있다. 

In [286]:
a.strides

(16, 8)

**(오브젝트 b)**

In [287]:
b

array([[11, 22, 33],
       [44, 55, 66]])

In [288]:
b.reshape(-1)

array([11, 22, 33, 44, 55, 66])

b의 경우 아래로 한칸가려면 메모리공간에서 24칸을 점프해야함. 오른쪽으로 이동하는것은 똑같겠지. 

In [282]:
b.strides

(24, 8)

`-` itemsize는 항상 8이다?

그런것은 아니다. 기본적으로 8칸에 저장하는데, 경우에 따라서는 더 적은칸을 사용하여 저장할 수도 있다. 

In [291]:
e=np.array([11,22,33,44,55,66],dtype='int32')
e

array([11, 22, 33, 44, 55, 66], dtype=int32)

In [292]:
e.itemsize

4

In [295]:
e=e.reshape(2,3)
e

array([[11, 22, 33],
       [44, 55, 66]], dtype=int32)

In [296]:
e.strides

(12, 4)

***넘파이의 동작 원리 (틀렸음)***

`-` 11,22,33,44,55,66 이 어딘가에 저장되어 있을것이다. 

`-` 그것은 그대로 유지하고 새로운 추가공간에 a,b,c라는 오브젝트를 만든다. 

`-` 자기들끼리 a.shape b.shape c.shape, a.strides, b.strides, c.strides ... 등을 조정하여 나는 (3,2) 차원이다 혹은 (2,3) 차원이다 혹은 (6,1) 차원이다 하는 것임 

`-` 실제로 메모리 공간에 그러한 배열이 만들어지는것은 아니다. 즉 11,22,33,44,55,66은 항상 그자리에 가만히 저장되어있음. 

### 참조 

`-` a를 선언, b는 a의 참조 

In [297]:
a=np.array([[1,2],[3,4]])
b=a ## 이거 shallow copy 아님. 인터넷에 자꾸 shallow copy라고 주장하는 사람들 있음. 

`-` shape을 조사하자 

In [298]:
a.shape

(2, 2)

In [299]:
b.shape

(2, 2)

`-` shape의 모양을 직접확인: (2,2) shape으로 잘 정리되어 있음 

In [300]:
a

array([[1, 2],
       [3, 4]])

In [301]:
b

array([[1, 2],
       [3, 4]])

`-` a의 shape을 바꾸면? $\to$ b도 따라서 바뀐다. 

In [302]:
a.shape=(4,)

In [303]:
a

array([1, 2, 3, 4])

In [304]:
b

array([1, 2, 3, 4])

### view 

`-` a를 선언, b는 a의 view. (b는 a의 shallow copy 라고 부르기도 함) 

In [340]:
a=np.array([[1,2],[3,4]])
b=a.view() ## 이게 shallow copy 

`-` a,b 의 shape확인 

In [341]:
a

array([[1, 2],
       [3, 4]])

In [342]:
b

array([[1, 2],
       [3, 4]])

`-` a의 shape을 바꿔도 b는 바뀌지 않음. 

In [367]:
a.shape=(4,1)

In [368]:
a

array([[100],
       [  2],
       [  3],
       [  4]])

In [369]:
b

array([[100,   2],
       [  3,   4]])

`-` 하지만 값을 바꾸면 같이 바뀐다. 

In [370]:
a[0]=100

In [371]:
a

array([[100],
       [  2],
       [  3],
       [  4]])

In [372]:
b

array([[100,   2],
       [  3,   4]])

`-` 출생의 비밀

In [373]:
b

array([[100,   2],
       [  3,   4]])

In [374]:
b.base

array([[100],
       [  2],
       [  3],
       [  4]])

- ? 이거 바뀐 a 아니야? 

In [360]:
id(b.base)

140407834709808

In [361]:
id(a)

140407834709808

`-` View 
- b는 a의 뷰라는 의미는, b가 a를 소스로하여 만들어진 오브젝트란 의미이다. 
- 따라서 이때 b.base = a 가 된다.
- b는 자체적으로 데이터를 가지고 있지는 않으며 오브젝트 a와 공유한다. 
- 이러한 의미에서 view를 shallow copy라고 부르기도한다. (가장 껍데기 구조만 복사하니까) 

`note1` 원본 ndarray 일 경우는 .base 속성이 None으로 나온다. 

In [365]:
a.base

In [366]:
a.base, b.base

(None, array([100,   2,   3,   4]))

`note2` b.base의 shape과 b의 shape은 아무 관련없다. 

In [377]:
a,b.base,b

(array([[100],
        [  2],
        [  3],
        [  4]]),
 array([[100],
        [  2],
        [  3],
        [  4]]),
 array([[100,   2],
        [  3,   4]]))

### copy 

`-` a를 선언, b는 a의 카피 

In [378]:
a=np.array([[1,2],[3,4]])
b=a.copy()

`-` a의 shape을 바꿔도 b는 적용되지 않음 (이건 당연하죠) 

In [385]:
a.shape = (4,1)

In [386]:
a

array([[100],
       [  2],
       [  3],
       [  4]])

In [387]:
b

array([[1, 2],
       [3, 4]])

`-` 그리고 a[0]의 값을 바꿔도 b에는 적용되지 않음 

In [388]:
a[0]=100

In [389]:
a

array([[100],
       [  2],
       [  3],
       [  4]])

In [390]:
b

array([[1, 2],
       [3, 4]])

`-` 출생의 비밀은 없었다. (둘다 원본 ndarray)

In [393]:
a.base, b.base

(None, None)

***copy의 한계(?)***

In [321]:
a=np.array([1,[1,2]],dtype='O')
b=a.copy()

In [322]:
a

array([1, list([1, 2])], dtype=object)

In [323]:
a[0]=2

In [324]:
a

array([2, list([1, 2])], dtype=object)

In [325]:
b

array([1, list([1, 2])], dtype=object)

In [326]:
a[1][0]=100

In [327]:
a

array([2, list([100, 2])], dtype=object)

In [328]:
b

array([1, list([100, 2])], dtype=object)

***더 깊은 복사: 이게 필요할까?***

In [329]:
import copy 

In [330]:
a=np.array([1,[1,2]],'O')
b=copy.deepcopy(a)

In [331]:
a[1][0]=100

In [332]:
a

array([1, list([100, 2])], dtype=object)

In [333]:
b

array([1, list([1, 2])], dtype=object)

일반적인 매트릭스나 다차원배열의 형태라면 copy모듈이 불필요함!

### 별명, 뷰, 카피 

`-` 별명, 뷰, 카피를 테스트하는 함수를 만들자. 

In [394]:
def test(a,b):
    if id(a)==id(b): 
        print('별명')
    elif id(a)==id(b.base) or id(a.base)==id(a):
        print('뷰')
    elif id(a.base)!=id(None) and id(b.base)!=id(None) and id(a.base)==id(b.base):
        print('공통의 base를 가짐')
    else:
        print('카피이거나 아무 관련 없는 오브젝트')

`-` 혹시 잘 동작하나? 

(테스트1)

In [402]:
a=np.array([1,2,3,4])
b=a

In [403]:
test(a,b)

별명


(테스트2)

In [405]:
a=np.array([1,2,3,4])
b=a.view()

In [406]:
test(a,b)

뷰


(테스트3)

In [407]:
a=np.array([1,2,3,4])
b=a.view()
c=a.view()

In [408]:
test(b,c)

공통의 base를 가짐


In [410]:
test(a,b)

뷰


In [411]:
test(a,c)

뷰


(테스트4)

In [412]:
a=np.array([1,2,3,4])
b=a.copy()

In [413]:
test(a,b)

카피이거나 아무 관련 없는 오브젝트


`-` 우리가 사용했던 어떠한 것들이 뷰가 나올지 카피가 나올지 사실 잘 모른다. 

In [414]:
a=np.array([1,2,3,4])
b=a[:3]

In [415]:
a

array([1, 2, 3, 4])

In [416]:
b

array([1, 2, 3])

In [417]:
test(a,b)

뷰


In [418]:
a=np.array([1,2,3,4])
c=a[[0,1,2]] # a=[:3] 이거랑 사실상같음

In [419]:
a

array([1, 2, 3, 4])

In [420]:
c

array([1, 2, 3])

In [421]:
test(a,c)

카피이거나 아무 관련 없는 오브젝트


`-` 왜 b는 뷰이고 c는 카피인가? $\to$ 만든사람 마음 (메모리 구조로 설명할순있음) 

In [422]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [425]:
b=a.flatten()
c=a.ravel()
d=a.reshape(-1)

In [428]:
a

array([[1, 2],
       [3, 4]])

In [429]:
b,c,d

(array([1, 2, 3, 4]), array([1, 2, 3, 4]), array([1, 2, 3, 4]))

In [430]:
test(a,b)

카피이거나 아무 관련 없는 오브젝트


In [431]:
test(a,c)

뷰


In [432]:
test(a,d)

뷰


In [433]:
test(c,d)

공통의 base를 가짐
