In [5]:
#hide
options(jupyter.plot_scale=3)
options(repr.plot.width=6,repr.plot.height=6,repr.plot.res=300)
options(jupyter.rich_display=FALSE)
options(max.print=1000)

# (노트) R입문 - 볼링공
> 볼링공

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [R]

### import 

In [6]:
library(tidyverse)

### 볼링공 문제 (2019 SW마에스트로 입학 테스트)

A,B 두 사람이 볼링을 치고 있습니다. 두 사람은 서로 무게가 다른 볼링공을 고르려고 합니다. 볼링공은 총 N개가 있으며 각 볼링공마다 무게가 적혀 있고, 공의 번호는 1번부터 순서대로 부여됩니다. 또한 같은 무게의 공이 여러개 있을 수 있지만, 서로 다른 공으로 간주합니다. 볼링공의 무게는 1부터 M까지의 자연수 형태로 존재합니다. 

예를들어 N이 5이고, M이 3이며 각각의 무게가 차례대로 1,3,2,3,2일 때 각 공의 번호가 차례대로 1번부터 5번까지 부여됩니다. 이때 두 사람이 고를 수 있는 볼링공 번호의 조합을 구하면 다음과 같습니다. 

(1번,2번), (1번,3번), (1번,4번), (1번,5번), (2번,3번), (2번,5번), (3번,4번), (4번,5번)

결과적으로 두 사람이 공을 고르는 경우의 수는 8가지입니다. N개의 공의 무게가 각각 주어질 때, 두 사람이 볼링공을 고르는 경우의 수를 구하는 프로그램을 작성하세요. 

#### 문제해설 

> $M$개의 볼링공의 무게를 각각 $x_1,\dots,x_M$ 이라고 하자. $M$개의 공중에서 무게가 서로 다른 2개 공을 뽑는 조합의 수를 구하는 알고리즘을 구현하라. 

> 예시: $(x_1,\dots,x_5)=(1,3,2,3,2)$ 일 경우 가능한 조합의 집합은 아래와 같다. 
$(x_1,x_2), (x_1,x_3),(x_1,x_4), (x_1,x_5),(x_2,x_3), (x_2,x_5), (x_3,x_4), (x_4,x_5)$

### 풀이1

In [7]:
a=c(1,3,2,3,2)

In [8]:
a

[1] 1 3 2 3 2

In [9]:
count=0
for (i in 1:5){
    for (j in 1:5){
        if (a[i]!=a[j]) count=count+1
    }
}
count

[1] 16

- ? 중복이 계산되어서 이상한 값이 나왔다.. 

`-` 아래와 같이 수정하면 된다. 

In [78]:
count=0
for (i in 1:5){
    for (j in 1:5){
        if ((a[i]!=a[j])&(j>i)) count=count+1
    }
}
count

[1] 8

### 풀이2

`-` `((a[i]!=a[j])&(j>i))` 에서 `j>i`는 for문의 선언부에서 처리할 수 있다. 

In [79]:
count=0
for (i in 1:5){
    for (j in i:5){ ## index가 i부터 시작하도록 한다
        if (a[i]!=a[j]) count=count+1
    }
}
count

[1] 8

### 풀이3

In [91]:
a=c(1,3,2,3,2)
A=rep(0,(length(a)**2)*2)
dim(A)=c(length(a)**2,2)
A

      [,1] [,2]
 [1,] 0    0   
 [2,] 0    0   
 [3,] 0    0   
 [4,] 0    0   
 [5,] 0    0   
 [6,] 0    0   
 [7,] 0    0   
 [8,] 0    0   
 [9,] 0    0   
[10,] 0    0   
[11,] 0    0   
[12,] 0    0   
[13,] 0    0   
[14,] 0    0   
[15,] 0    0   
[16,] 0    0   
[17,] 0    0   
[18,] 0    0   
[19,] 0    0   
[20,] 0    0   
[21,] 0    0   
[22,] 0    0   
[23,] 0    0   
[24,] 0    0   
[25,] 0    0   

In [92]:
k=1
for (i in 1:5){
    for (j in 1:5){
        A[k,]=c(a[i],a[j])
        k=k+1
    }
}
A

      [,1] [,2]
 [1,] 1    1   
 [2,] 1    3   
 [3,] 1    2   
 [4,] 1    3   
 [5,] 1    2   
 [6,] 3    1   
 [7,] 3    3   
 [8,] 3    2   
 [9,] 3    3   
[10,] 3    2   
[11,] 2    1   
[12,] 2    3   
[13,] 2    2   
[14,] 2    3   
[15,] 2    2   
[16,] 3    1   
[17,] 3    3   
[18,] 3    2   
[19,] 3    3   
[20,] 3    2   
[21,] 2    1   
[22,] 2    3   
[23,] 2    2   
[24,] 2    3   
[25,] 2    2   

`-` 이중에서 (1) 첫번째열 = 두번째열 이면서 (2) 중복을 피하면 된다. 

In [93]:
vec1<-c()
vec2<-c()
for(i in 1:25){
    vec1[i]<- A[i,1]-A[i,2] ## 첫번째열 = 두번째열 임을 파악하기 위해서 두 칼럼을 뺀다. (!=0이 되는 값을 체크하면됨) 
    vec2[i]<- A[i,1]>A[i,2] ## 중복을 피하기 위한 장치 
}

In [94]:
vec1

 [1]  0 -2 -1 -2 -1  2  0  1  0  1  1 -1  0 -1  0  2  0  1  0  1  1 -1  0 -1  0

In [95]:
vec2

 [1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE
[13] FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE
[25] FALSE

In [96]:
(vec1!=0) & (vec2==TRUE)

 [1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE
[13] FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE
[25] FALSE

In [97]:
sum((vec1!=0) & (vec2==TRUE))

[1] 8

### 풀이4 

`-` vec1,vec2를 꼭 for문을 사용해서 구할필요는 없음. 

In [89]:
a=c(1,3,2,3,2)
A=rep(0,(length(a)**2)*2)
dim(A)=c(length(a)**2,2)
k=1
for (i in 1:5){
    for (j in 1:5){
        A[k,]=c(a[i],a[j])
        k=k+1
    }
}
A

      [,1] [,2]
 [1,] 1    1   
 [2,] 1    3   
 [3,] 1    2   
 [4,] 1    3   
 [5,] 1    2   
 [6,] 3    1   
 [7,] 3    3   
 [8,] 3    2   
 [9,] 3    3   
[10,] 3    2   
[11,] 2    1   
[12,] 2    3   
[13,] 2    2   
[14,] 2    3   
[15,] 2    2   
[16,] 3    1   
[17,] 3    3   
[18,] 3    2   
[19,] 3    3   
[20,] 3    2   
[21,] 2    1   
[22,] 2    3   
[23,] 2    2   
[24,] 2    3   
[25,] 2    2   

In [90]:
A[,1]-A[,2] # vec1 

 [1]  0 -2 -1 -2 -1  2  0  1  0  1  1 -1  0 -1  0  2  0  1  0  1  1 -1  0 -1  0

In [21]:
A[,1]>A[,2] # vec2

 [1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE
[13] FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE
[25] FALSE

In [22]:
(A[,1]-A[,2] != 0) & (A[,1]>A[,2])

 [1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE
[13] FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE
[25] FALSE

In [23]:
((A[,1]-A[,2] != 0) & (A[,1]>A[,2])) %>% sum

[1] 8

### 풀이5

`-` 생각해보니까 단순히 첫번째 열이 두번째 열보다 큰지만 체크해도 될 것 같다.  

In [24]:
a=c(1,3,2,3,2)
A=rep(0,(length(a)**2)*2)
dim(A)=c(length(a)**2,2)
k=1
for (i in 1:5){
    for (j in 1:5){
        A[k,]=c(a[i],a[j])
        k=k+1
    }
}
A

      [,1] [,2]
 [1,] 1    1   
 [2,] 1    3   
 [3,] 1    2   
 [4,] 1    3   
 [5,] 1    2   
 [6,] 3    1   
 [7,] 3    3   
 [8,] 3    2   
 [9,] 3    3   
[10,] 3    2   
[11,] 2    1   
[12,] 2    3   
[13,] 2    2   
[14,] 2    3   
[15,] 2    2   
[16,] 3    1   
[17,] 3    3   
[18,] 3    2   
[19,] 3    3   
[20,] 3    2   
[21,] 2    1   
[22,] 2    3   
[23,] 2    2   
[24,] 2    3   
[25,] 2    2   

In [25]:
sum(A[,1]>A[,2])

[1] 8

### 현재까지 풀이 정리 

`-` 풀이1-2의 코드: 매트릭스를 쓰지 않음 

`-` 풀이3-5의 코드: 매트릭스를 사용 

`-` 현재까지는 풀이2가 가장 간결하며 루프도 적게돌아간다(=빠르다). 하지만 간결한 풀이도 중요한데 틀리지 않는것이 가장 중요함. 

`-` 풀이2와 같은 접근법은 디버깅이 어렵다. $\to$ 예외사항을 처리하기 어려움. 

`-` 특히 삼성에서 실시하는 코딩테스트 문제의 경우 예외사항을 잘 처리해야하는 문제가 주로 출제된다. 

`-` 시간이 많다면 2개 이상으로 구현하고 결과를 맞춰보는것도 좋음. 

### 풀이6

`-` 사실 A를 구하기 쉽게 해주는 함수가 R에 존재함. 

In [62]:
A=expand.grid(a,a)
A

   Var1 Var2
1  1    1   
2  3    1   
3  2    1   
4  3    1   
5  2    1   
6  1    3   
7  3    3   
8  2    3   
9  3    3   
10 2    3   
11 1    2   
12 3    2   
13 2    2   
14 3    2   
15 2    2   
16 1    3   
17 3    3   
18 2    3   
19 3    3   
20 2    3   
21 1    2   
22 3    2   
23 2    2   
24 3    2   
25 2    2   

- expand.grid(): 벡터들을 입력으로 받아서 그 벡터들의 원소가 만들어내는 순서쌍 조합을 데이터프레임 형태로 리턴함 
- 데이터프레임 

In [63]:
library(tidyverse)

In [65]:
A %>% mutate(C=Var1-Var2) # 

   Var1 Var2 C 
1  1    1     0
2  3    1     2
3  2    1     1
4  3    1     2
5  2    1     1
6  1    3    -2
7  3    3     0
8  2    3    -1
9  3    3     0
10 2    3    -1
11 1    2    -1
12 3    2     1
13 2    2     0
14 3    2     1
15 2    2     0
16 1    3    -2
17 3    3     0
18 2    3    -1
19 3    3     0
20 2    3    -1
21 1    2    -1
22 3    2     1
23 2    2     0
24 3    2     1
25 2    2     0

- mutate(): 데이터프레임에서 새로운 column 을 추가하는 기능 (위의 기존의 컬럼을 활용하여 새로운 파생컬럼을 만들 수 있음) 

In [29]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0) 

  Var1 Var2 C
1 3    1    2
2 2    1    1
3 3    1    2
4 2    1    1
5 3    2    1
6 3    2    1
7 3    2    1
8 3    2    1

- filter(): 데이터프레임에서 특정조건을 만족하는 행을 필터링하는 방법 

In [30]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0) %>% count 

  n
1 8

`-` 결과가 데이터프레임으로 나옴 $\to$ 숫자 하나인데 자료형이 굳이 데이터프레임일 이유가 없음 (다루기도 불편함) 

In [32]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0) %>% count -> rslt

In [36]:
rslt+1

  n
1 9

- 우리가 아는 숫자처럼 행동하는듯 하지만 

In [37]:
1:rslt

ERROR: Error in 1:rslt: NA/NaN argument


- 그렇지 않을때도 많음 (불편함) 

`-` 우리가 평소 쓰던 숫자로 바꾸고싶다. 

In [38]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0) %>% count %>% as.numeric

[1] 8

- as.numeric(): 자료형을 뉴메릭으로 바꾸는 함수 

### 풀이7

In [40]:
a<-c(1,3,2,3,2)

In [41]:
a1<-a
a2<-a

In [42]:
dim(a1)

NULL

In [43]:
dim(a2)

NULL

In [44]:
dim(a1)<-c(5,1)

In [45]:
dim(a2)<-c(1,5)

In [46]:
a1

     [,1]
[1,] 1   
[2,] 3   
[3,] 2   
[4,] 3   
[5,] 2   

In [47]:
a2

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2   

In [48]:
a1 %*% a2

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2   
[2,] 3    9    6    9    6   
[3,] 2    6    4    6    4   
[4,] 3    9    6    9    6   
[5,] 2    6    4    6    4   

- %*% 연산자: 매트릭스의 곱셉 (중요함) 

In [49]:
A = a1 %*% a2 

In [51]:
upper.tri(A)

     [,1]  [,2]  [,3]  [,4]  [,5] 
[1,] FALSE  TRUE  TRUE  TRUE  TRUE
[2,] FALSE FALSE  TRUE  TRUE  TRUE
[3,] FALSE FALSE FALSE  TRUE  TRUE
[4,] FALSE FALSE FALSE FALSE  TRUE
[5,] FALSE FALSE FALSE FALSE FALSE

In [52]:
A[upper.tri(A)] # 매트릭스 인덱싱 (신기술) 

 [1] 3 2 6 3 9 6 2 6 4 6

- 매트릭스 인덱싱 (중요함)
- upper.tri (그렇게 중요한것은 아님) 

In [77]:
A[upper.tri(A)] %in% c(4,9) # %in% 연산자 (신기술) 

 [1] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE

In [76]:
sum(!(A[upper.tri(A)] %in% c(4,9)))

[1] 8

- %in% 연산자 (중요함)

### 풀이8

In [68]:
a<-c(1,3,2,3,2)

In [69]:
A=outer(a,a)

- outer(): 벡터의 outer product를 구함 

In [70]:
A 

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2   
[2,] 3    9    6    9    6   
[3,] 2    6    4    6    4   
[4,] 3    9    6    9    6   
[5,] 2    6    4    6    4   

In [75]:
sum(!(A[upper.tri(A)] %in% c(4,9))) 

[1] 8

### 풀이 6,7,8 

`-` 풀이6: 데이터프레임 활용 $\to$ 사용하기 쉽고 확장성이 좋아보임 

`-` 풀이7,8: 코드가 간결함 / 에러가 발생할수 있는 여지가 있음 (무게가 1인 공이 있다면 1,4,9를 만드는 조합이 거듭제곱만 있는것은 아닐것임) 