In [71]:
#hide
options(jupyter.plot_scale=3)
options(repr.plot.width=6,repr.plot.height=6,repr.plot.res=300)
options(jupyter.rich_display=FALSE)
options(max.print=1000)

# R입문 - 볼링공
> 숫자 카드 게임  

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [R]

### import 

In [72]:
library(tidyverse)

### 볼링공 문제

### 풀이1

In [73]:
a=c(1,3,2,3,2)

In [74]:
a

[1] 1 3 2 3 2

In [78]:
count=0
for (i in 1:5){
    for (j in 1:5){
        if (a[i]!=a[j]) count=count+1
    }
}
count

[1] 16

- ? 중복이 계산되어서 이상한 값이 나왔다.. 

`-` 아래와 같이 수정하면 된다. 

In [80]:
count=0
for (i in 1:5){
    for (j in 1:5){
        if ((a[i]!=a[j])&(i>j)) count=count+1
    }
}
count

[1] 8

### 풀이2

In [120]:
count=0
for (i in 1:5){
    for (j in i:5){ ## index가 i부터 시작하도록 한다
        if (a[i]!=a[j]) count=count+1
    }
}
count

[1] 8

### 풀이3

In [121]:
a=c(1,3,2,3,2)
A=rep(0,(length(a)**2)*2)
dim(A)=c(length(a)**2,2)
A

      [,1] [,2]
 [1,] 0    0   
 [2,] 0    0   
 [3,] 0    0   
 [4,] 0    0   
 [5,] 0    0   
 [6,] 0    0   
 [7,] 0    0   
 [8,] 0    0   
 [9,] 0    0   
[10,] 0    0   
[11,] 0    0   
[12,] 0    0   
[13,] 0    0   
[14,] 0    0   
[15,] 0    0   
[16,] 0    0   
[17,] 0    0   
[18,] 0    0   
[19,] 0    0   
[20,] 0    0   
[21,] 0    0   
[22,] 0    0   
[23,] 0    0   
[24,] 0    0   
[25,] 0    0   

In [132]:
k=1
for (i in 1:5){
    for (j in 1:5){
        A[k,]=c(a[i],a[j])
        k=k+1
    }
}
A

      [,1] [,2]
 [1,] 1    1   
 [2,] 1    3   
 [3,] 1    2   
 [4,] 1    3   
 [5,] 1    2   
 [6,] 3    1   
 [7,] 3    3   
 [8,] 3    2   
 [9,] 3    3   
[10,] 3    2   
[11,] 2    1   
[12,] 2    3   
[13,] 2    2   
[14,] 2    3   
[15,] 2    2   
[16,] 3    1   
[17,] 3    3   
[18,] 3    2   
[19,] 3    3   
[20,] 3    2   
[21,] 2    1   
[22,] 2    3   
[23,] 2    2   
[24,] 2    3   
[25,] 2    2   

`-` 이중에서 (1) 첫번째열 = 두번째열 이면서 (2) 중복을 피하면 된다. 

In [115]:
vec1<-c()
vec2<-c()
for(i in 1:25){
    vec1[i]<- A[i,1]-A[i,2] ## 첫번째열 = 두번째열 임을 파악하기 위해서 두 칼럼을 뺀다. (!=0이 되는 값을 체크하면됨) 
    vec2[i]<- A[i,1]>A[i,2] ## 중복을 피하기 위한 장치 
}

In [110]:
vec1

 [1]  0  2  1  2  1 -2  0 -1  0 -1 -1  1  0  1  0 -2  0 -1  0 -1 -1  1  0  1  0

In [111]:
vec2

 [1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[13] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE
[25] FALSE

In [114]:
(vec1!=0) & (vec2==TRUE)

 [1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[13] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE
[25] FALSE

In [88]:
sum((vec1!=0) & (vec2==TRUE))

[1] 8

### 풀이4 

`-` vec1,vec2를 꼭 for문을 사용해서 구할필요는 없음. 

In [124]:
a=c(1,3,2,3,2)
A=rep(0,(length(a)**2)*2)
dim(A)=c(length(a)**2,2)
k=1
for (i in 1:5){
    for (j in 1:5){
        A[k,]=c(a[i],a[j])
        k=k+1
    }
}
A

      [,1] [,2]
 [1,] 1    1   
 [2,] 1    3   
 [3,] 1    2   
 [4,] 1    3   
 [5,] 1    2   
 [6,] 3    1   
 [7,] 3    3   
 [8,] 3    2   
 [9,] 3    3   
[10,] 3    2   
[11,] 2    1   
[12,] 2    3   
[13,] 2    2   
[14,] 2    3   
[15,] 2    2   
[16,] 3    1   
[17,] 3    3   
[18,] 3    2   
[19,] 3    3   
[20,] 3    2   
[21,] 2    1   
[22,] 2    3   
[23,] 2    2   
[24,] 2    3   
[25,] 2    2   

In [126]:
A[,1]-A[,2] # vec1 

 [1]  0 -2 -1 -2 -1  2  0  1  0  1  1 -1  0 -1  0  2  0  1  0  1  1 -1  0 -1  0

In [113]:
A[,1]>A[,2] # vec2

 [1] FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE
[13] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE
[25] FALSE

In [127]:
(A[,1]-A[,2] != 0) & (A[,1]>A[,2])

 [1] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE
[13] FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE FALSE FALSE FALSE
[25] FALSE

In [129]:
((A[,1]-A[,2] != 0) & (A[,1]>A[,2])) %>% sum

[1] 8

### 풀이5

`-` 생각해보니까 단순히 첫번째 열이 두번째 열보다 큰지만 체크해도 될 것 같다.  

In [130]:
a=c(1,3,2,3,2)
A=rep(0,(length(a)**2)*2)
dim(A)=c(length(a)**2,2)
k=1
for (i in 1:5){
    for (j in 1:5){
        A[k,]=c(a[i],a[j])
        k=k+1
    }
}
A

      [,1] [,2]
 [1,] 1    1   
 [2,] 1    3   
 [3,] 1    2   
 [4,] 1    3   
 [5,] 1    2   
 [6,] 3    1   
 [7,] 3    3   
 [8,] 3    2   
 [9,] 3    3   
[10,] 3    2   
[11,] 2    1   
[12,] 2    3   
[13,] 2    2   
[14,] 2    3   
[15,] 2    2   
[16,] 3    1   
[17,] 3    3   
[18,] 3    2   
[19,] 3    3   
[20,] 3    2   
[21,] 2    1   
[22,] 2    3   
[23,] 2    2   
[24,] 2    3   
[25,] 2    2   

In [131]:
sum(A[,1]>A[,2])

[1] 8

### 현재까지 풀이 정리 

`-` 풀이1-2의 코드: 매트릭스를 쓰지 않음 

`-` 풀이3-5의 코드: 매트릭스를 사용 

`-` 현재까지는 풀이2가 가장 간결함. 하지만 간결한 풀이도 중요한데 틀리지 않는것이 가장 중요함. 

`-` 풀이2와 같은 접근법은 디버깅이 어렵다. $\to$ 예외사항을 처리하기 어려움. 

`-` 특히 삼성에서 실시하는 코딩테스트 문제의 경우 예외사항을 잘 처리해야하는 문제가 주로 출제된다. 

`-` 시간이 많다면 2개 이상으로 구현하고 결과를 맞춰보는것도 좋음. 

### 풀이6

`-` 사실 A를 구하기 쉽게 해주는 함수가 R에 존재함. 

In [133]:
A=expand.grid(a,a)
A

   Var1 Var2
1  1    1   
2  3    1   
3  2    1   
4  3    1   
5  2    1   
6  1    3   
7  3    3   
8  2    3   
9  3    3   
10 2    3   
11 1    2   
12 3    2   
13 2    2   
14 3    2   
15 2    2   
16 1    3   
17 3    3   
18 2    3   
19 3    3   
20 2    3   
21 1    2   
22 3    2   
23 2    2   
24 3    2   
25 2    2   

In [135]:
library(tidyverse)

In [136]:
A %>% mutate(C=Var1-Var2) # 

   Var1 Var2 C 
1  1    1     0
2  3    1     2
3  2    1     1
4  3    1     2
5  2    1     1
6  1    3    -2
7  3    3     0
8  2    3    -1
9  3    3     0
10 2    3    -1
11 1    2    -1
12 3    2     1
13 2    2     0
14 3    2     1
15 2    2     0
16 1    3    -2
17 3    3     0
18 2    3    -1
19 3    3     0
20 2    3    -1
21 1    2    -1
22 3    2     1
23 2    2     0
24 3    2     1
25 2    2     0

In [137]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0) 

  Var1 Var2 C
1 3    1    2
2 2    1    1
3 3    1    2
4 2    1    1
5 3    2    1
6 3    2    1
7 3    2    1
8 3    2    1

In [138]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0) %>% count 

  n
1 8

In [139]:
A %>% mutate(C=Var1-Var2) %>% filter(C>0) %>% count %>% as.numeric

[1] 8

### 풀이8 

In [150]:
a<-c(1,3,2,3,2)

In [151]:
a1<-a
a2<-a

In [153]:
dim(a1)

NULL

In [154]:
dim(a2)

NULL

In [156]:
dim(a1)<-c(5,1)

In [155]:
dim(a2)<-c(1,5)

In [157]:
a1

     [,1]
[1,] 1   
[2,] 3   
[3,] 2   
[4,] 3   
[5,] 2   

In [158]:
a2

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2   

In [162]:
a1 %*% a2

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2   
[2,] 3    9    6    9    6   
[3,] 2    6    4    6    4   
[4,] 3    9    6    9    6   
[5,] 2    6    4    6    4   

### 풀이9

In [145]:
a<-c(1,3,2,3,2)

In [140]:
A=outer(a,a)

In [141]:
A 

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    3    2    3    2   
[2,] 3    9    6    9    6   
[3,] 2    6    4    6    4   
[4,] 3    9    6    9    6   
[5,] 2    6    4    6    4   

In [142]:
sum(!(A[upper.tri(A)] %in% c(1,4,9))) 

[1] 8