# (노트) numpy 축 연산 
> 완성

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

In [1]:
import numpy as np 

### 2차원 

`-` 연습용배열 

In [4]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

a2는 $2 \times 3$ 행렬이다. 

In [16]:
a2.shape

(2, 3)

`-` 예제1

`axis=0 `으로 연산하면 (2,3)중 첫번째 차원이 삭제된다. 
- 따라서 결과는 길이가 $3$ 인 벡터가 나옴
- 삭제된 차원값 = 2 $\to$ 결과의 각 원소는 2개의 숫자를 더한 것임 

In [5]:
np.sum(a2,axis=0)

array([5, 7, 9])

`-` 예제2

`axis=1` 으로 연산하면 (2,3)중 두번째 차원이 삭제된다. 
- 따라서 결과는 길이가 2인 벡터가 나옴 
- 삭제된 차원값 = 3 $\to$ 결과의 각 원소는 3개의 숫자를 더한 것임 

In [6]:
np.sum(a2,axis=1)

array([ 6, 15])

### 3차원



`-` 연습용배열

In [17]:
a3=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]],[[21,22,23],[24,25,26]],[[31,32,33],[34,35,36]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]],

       [[31, 32, 33],
        [34, 35, 36]]])

a3의 차원은 $4\times 2 \times 3$ 

In [18]:
a3.shape

(4, 2, 3)

`-` 예제3

`axis=0` 으로 연산하면 (4,2,3) 중 첫번째 차원이 삭제된다. 
- 따라서 결과는 (2,3) array
- 삭제된 차원값 = 4 $\to$ 결과의 각 원소는 4개의 숫자를 더한 값임
---
```
### 원래 array
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]],

       [[31, 32, 33],
        [34, 35, 36]]])
```
---

| | | |
|---|---|---|
|1+?| 2+?| 3+? |
|4+?| 5+?| 6+? |

$$\downarrow$$

| | | |
|---|---|---|
|1+11+21+31| 2+12+22+32| 3+13+23+33 |
|4+14+24+34| 5+15+25+35| 6+16+26+36 |

In [20]:
np.sum(a3,axis=0)

array([[64, 68, 72],
       [76, 80, 84]])

`-` 예제4 

`axis=1` 으로 연산하면 (4,2,3) 중 두번째 차원이 삭제된다. 
- 따라서 결과는 (4,3) array
- 삭제된 차원값 = 2 $\to$ 결과의 각 원소는 2개의 숫자를 더한 값임 

---
```
### 원래 array
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]],

       [[31, 32, 33],
        [34, 35, 36]]])
```
---

||||
|--|--|--|
|1+4|2+5|3+6|
|11+14|12+15|13+16|
|21+24|22+25|23+26|
|31+34|32+35|33+36|

$$\downarrow$$ 

||||
|--|--|--|
|1+4|2+5|3+6|
|11+14|12+15|13+16|
|21+24|22+25|23+26|
|31+34|32+35|33+36|

In [21]:
np.sum(a3,axis=1)

array([[ 5,  7,  9],
       [25, 27, 29],
       [45, 47, 49],
       [65, 67, 69]])

`-` 예제5

`axis=2`로 연산하면 (4,2,3) 중 세번째차원이 삭제된다. 

- 따라서 결과는 (4,2) array
- 삭제된 차원값 =3 $\to$ 결과의 각 원소는 3가지 숫자를 더한 값임
---
```
### 원래 array
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]],

       [[31, 32, 33],
        [34, 35, 36]]])
```
---

| | |
|---|---|
|1+?|4+?|
|11+?|14+?|
|21+?|24+?|
|31+?|34+?| 

$$\downarrow$$


| | |
|---|---|
|1+2+3|4+5+6|
|11+12+13|14+15+16|
|21+22+23|24+25+26|
|31+32+33|34+35+36|


In [22]:
np.sum(a3,axis=2)

array([[  6,  15],
       [ 36,  45],
       [ 66,  75],
       [ 96, 105]])

`-` 예제6 

`axis=(0,1)`로 연산하면 (4,2,3) 에서 1,2차원이 삭제된다. 
- 따라서 결과는 길이3인 벡터 
- 삭제된 차원값 = (4,2) $\to$ 각 원소는 8개의 숫자를 더한 값임 

---
```
### 원래 array
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]],

       [[31, 32, 33],
        [34, 35, 36]]])
```

In [23]:
np.sum(a3,axis=(0,1))

array([140, 148, 156])

`-` 예제7

`axis=(0,2)`로 연산하면 (4,2,3) 에서 1,3차원이 삭제된다. 
- 따라서 결과는 길이2인 벡터 
- 삭제된 차원값 = (4,3) $\to$ 각 원소는 12개의 숫자를 더한 값임 

---
```
### 원래 array
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]],

       [[31, 32, 33],
        [34, 35, 36]]])
```

In [24]:
np.sum(a3,axis=(0,2))

array([204, 240])

`-` 예제8

`axis=(1,2)`로 연산하면 (4,2,3) 에서 2,3차원이 삭제된다. 
- 따라서 결과는 길이4인 벡터 
- 삭제된 차원값 = (2,3) $\to$ 각 원소는 6개의 숫자를 더한 값임 

---
```
### 원래 array
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]],

       [[31, 32, 33],
        [34, 35, 36]]])
```

In [25]:
np.sum(a3,axis=(1,2))

array([ 21,  81, 141, 201])