In [1]:
#hide
options(jupyter.plot_scale=3)
options(jupyter.display_mimetypes=c("text/html"))
options(jupyter.rich_display=FALSE)
options(repr.plot.width=6,repr.plot.height=6,repr.plot.res=300)
options(max.print=1000)

# R입문 - 카드뽑기
> 숫자 카드 게임  

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [R]

### 숫자 카드 게임 (2019 국가 교육기관 코딩테스트) 

숫자 카드 게임은 여러개의 숫자중에서 가장 높은 숫자가 쓰인 카드를 한장 뽑는 게임이다. 

단, 게임의 룰을 지키며 카드를 뽑아야 하고 룰은 다음과 같다. 

- 숫자가 쓰인 카드들이 N$\times $M 형태로 놓여 있다. 
- 먼저 뽑고자 하는 카드가 포함되어 있는 행을 선택한다. 
- 그 다음 선택된 행에 포함된 카드들 중에서 가장 숫자가 낮은 카드를 뽑아야 한다. 
- 따라서 처음에 카드를 골라낼 행을 선택할때, 이후에 해당 행에서 가장 숫자가 낮은 카드를 뽑을 것을 고려하여 최종적으로 가장 높은 숫자의 카드를 뽑을 수 있도록 전략을 세워야 한다. 

`-` 예시1

```
입력
3 1 2 
4 1 4 
2 2 2 

출력 
2
```

`-` 예시2

```
입력
7 3 1 8 
3 3 3 4 

출력
3
```

(풀이) 

(전략회의)

In [2]:
a1=c(3,1,2) 
a2=c(4,1,4)
a3=c(2,2,2)

우리는 일단 아래와 같은 모양을 만들어야함 

```
3 1 2
4 1 4 
2 2 2 
```

a1,a2,a3을 각각 row-vector 로 해석하고 bind 하면된다. 

In [3]:
A = rbind(a1,a2,a3)

In [4]:
A

   [,1] [,2] [,3]
a1 3    1    2   
a2 4    1    4   
a3 2    2    2   

In [5]:
A= rbind(c(3,1,2),c(4,1,4),c(2,2,2))

입력이 A일경우 출력이 2가 나와야한다. 

전략: 
1. A의 각 행(row)을 돌아가면서 가장 작은 숫자를 찾아 기록한다. 
2. 기록한 숫자들을 모아서 벡터로 만든다. 
3. 벡터의 최대값을 구한다. 

할수있어야 하는것 

- A의 1번째 행, 2번째행, 3번째행을 순서대로 뽑을수 있어야 한다. 

(실질적풀이)

In [6]:
A= rbind(c(3,1,2),c(4,1,4),c(2,2,2))

In [7]:
vec<-c()
for (i in 1:3) vec[i]<- min(A[i,])

In [8]:
max(vec)

[1] 2

`-` 입력이 아래와 같은 경우 

```
7 3 1 8 
3 3 3 4 
```

In [9]:
A=rbind(c(7,3,1,8),c(3,3,3,4)) 

In [10]:
vec<-c()
for (i in 1:2) vec[i]<- min(A[i,])

In [11]:
max(vec)

[1] 3

### 숙제

입력구조가 
```
3 4 5 1 
7 7 7 2 
8 1 8 2
3 3 4 5 
```

출력을 구하는 코드를 작성하시오. 

(숙제풀이) tidyverse를 이용 

In [16]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.3     ✔ dplyr   1.0.7
✔ tidyr   1.1.3     ✔ stringr 1.4.0
✔ readr   1.4.0     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()



In [17]:
A=rbind(c(3,4,5,1),c(7,7,7,2), c(8,1,8,2), c(3,3,4,5))

In [18]:
A

     [,1] [,2] [,3] [,4]
[1,] 3    4    5    1   
[2,] 7    7    7    2   
[3,] 8    1    8    2   
[4,] 3    3    4    5   

step1. apply를 적용하여 각각의 row에 min함수를 취한다. 

In [19]:
apply(A,1,min) # A=입력매트릭스, 1=입력매트릭스의 각 row에 어떠한 함수를 적용 

[1] 1 2 1 3

In [20]:
A %>% apply(1,min)

[1] 1 2 1 3

step2. 그 결과에서 max를 취한다. 

In [21]:
max(apply(A,1,min))

[1] 3

In [22]:
A %>% apply(1,min) %>% max 

[1] 3

### 카드뽑기 풀이에서 우리가 얻을 것

#### 매트릭스를 선언하는 방법 

`-` 방법1: 벡터를 만들고 그것을 row-vector로 해석 $\to$ bind 

In [23]:
rbind(c(1,2,3,4),c(2,2,3,4))

     [,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 2    2    3    4   

`-` 방법2: 벡터를 만들고 그것을 col-vector로 해석 $\to$ bind 

In [24]:
cbind(c(1,2,3,4),c(2,2,3,4))

     [,1] [,2]
[1,] 1    2   
[2,] 2    2   
[3,] 3    3   
[4,] 4    4   

`-` 일단 이정도만.. 

#### 매트릭스의 원소를 뽑는 방법 

`-` 아래와 같은 매트릭스가 있다고 하자. 

In [25]:
A=rbind(c(1,2,3,4),c(5,6,7,8),c(9,10,11,12))
A

     [,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12  

`-` 1열을 뽑고싶다. 

In [26]:
A[,1]

[1] 1 5 9

`-` 1,4열을 뽑고싶다. 

In [27]:
A[,c(1,4)]

     [,1] [,2]
[1,] 1     4  
[2,] 5     8  
[3,] 9    12  

`-` 2행을 뽑고싶다. 

In [28]:
A[2,]

[1] 5 6 7 8

`-` 1,2행을 뽑고싶다. 

In [29]:
A[c(1,2),]

     [,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8   

`-` 2행3열의 원소 즉 (2,3)에 위치한 원소를 뽑고싶다. 

In [30]:
A[2,3]

[1] 7

`-` 일단 이정도만.. 

#### 매트릭스를 왜 써야하는가? 

`-` 바둑판구조의 자료형의 표현하기 위해서 = 자료를 바둑판 구조로 저장하기 위해서 

`-` 자료를 바둑판(2d-array), 나아가 큐브형태(3d-array)로 저장하면 여러가지 이점이 있다.  

`-` 결국 벡터(1d-array)를 쓰는 이유와 같음. 자료를 일자로 배열하여 저장하면 자료를 관리하기 편하거나 계산상의 이점이 있는 경우가 많은데 매트릭스 역시 그러하다. 

(예시) 벡터의 계산상 이점: 초항이 1이고 공차가 2인 등차수열을 100개 만들어라. 

In [31]:
a<-c()
for (n in 1:100) a[n]<- 2*n-1 
print(a)

  [1]   1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
 [19]  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
 [37]  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 [55] 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 [73] 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 [91] 181 183 185 187 189 191 193 195 197 199


위와 같은 간단한 코드도 결국 벡터형태로 자료를 저장하고 관리하기 때문에 for를 쓸 수 있는 것

혹은 아래와 같이 구할 수도 있는데 (브로드캐스팅) 이 역시 벡터라는 개념이 있기에 가능함 

In [32]:
n=1:100
2*n-1

  [1]   1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
 [19]  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
 [37]  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 [55] 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 [73] 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 [91] 181 183 185 187 189 191 193 195 197 199

이는 벡터를 이용하여 2*n-1 이라는 단순한 수식을 벡터버전으로 확장해석한것이다. 계산상 이점을 극대화함. (수식적으로 간단 + 구현이 간단 + 빠름!!) 

#### apply 함수

`-` 우선 아래를 기억하자. 

```
apply(매트릭스,1,특정함수) 
```

를 쓰면 어떠한 특정함수가 각각의 row에 적용되어서 결과가 array로 저장된다. 

`-` 여기에서 특정함수는 "벡터입력-스칼라출력" 이라 생각하자. 즉 벡터입력-스칼라출력인 함수만 apply가 가능하다고 생각하자. (사실그렇지는 않음) 예를들면 아래와 같다. 

In [33]:
sum(c(1,2,3,4))

[1] 10

In [34]:
mean(c(1,2,3,4))

[1] 2.5

`-` 아래와 같은 함수는 벡터입력-벡터출력 이므로 조건에 해당하지 않는다. 

In [35]:
sqrt(c(1,2,3,4))

[1] 1.000000 1.414214 1.732051 2.000000

`-` 이제 매트릭스 A에 다양한 함수를 적용해보자. 

In [36]:
A

     [,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12  

In [37]:
apply(A,1,sum)

[1] 10 26 42

In [38]:
apply(A,1,mean)

[1]  2.5  6.5 10.5

In [39]:
apply(A,1,min)

[1] 1 5 9

In [40]:
apply(A,1,max)

[1]  4  8 12

사용자가 정의한 함수도 가능하다. 

In [41]:
f = function(a) (min(a)+1)**2-3

In [42]:
apply(A,1,f)

[1]  1 33 97

`-` 숫자1을 2로 바꾸면 특정함수가 각각의 col에 적용되어서 결과가 array로 저장된다. 

In [43]:
A

     [,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12  

In [44]:
apply(A,2,sum)

[1] 15 18 21 24

In [45]:
apply(A,2,mean)

[1] 5 6 7 8

In [46]:
apply(A,2,min)

[1] 1 2 3 4

In [47]:
apply(A,2,max)

[1]  9 10 11 12

In [48]:
apply(A,2,f)

[1]  1  6 13 22

#### %>% 연산자 ($\star\star\star$)

`-` 진짜 중요해요 

`-` 왜냐하면 너무 편해요 

`-` 아래는 같은 코드이다. 

In [49]:
sum(1:10)

[1] 55

In [50]:
1:10 %>% sum()

[1] 55

In [51]:
1:10 %>% sum

[1] 55

`-` 아래도 같은 코드이다. 

In [52]:
myfun = function(x,y) x**2+y

In [53]:
myfun(2,3)

[1] 7

In [54]:
2 %>% myfun(3)

[1] 7

In [55]:
myfun(3,2)

[1] 11

In [56]:
3 %>% myfun(2)

[1] 11

`-` 아래도 같은 코드이다. 

In [57]:
myfun2 = function(x,y,z) x**2 + y*z

In [58]:
myfun2(2,1,1)

[1] 5

In [59]:
2 %>% myfun2(1,1)

[1] 5

`-` 왜 이러한 일을 해야하는가? (합성함수 처리에 유리)

In [60]:
2:5 %>% log %>% sqrt %>% sum %>% myfun2(1,1) %>% sqrt

[1] 4.440805

In [61]:
sqrt(myfun2(sum(sqrt(log(2:5))),1,1))

[1] 4.440805

In [62]:
2:5 %>% log %>% myfun(3) %>% sqrt %>% sum %>% myfun2(1,1) %>% sqrt

[1] 8.558202

In [63]:
sqrt(myfun2(sum(sqrt(myfun(log(2:5),3))),1,1))

[1] 8.558202

`-` 아래의 개념차이

- $h(g(f(x)))$
- $x \to f \to g \to h$

### 시간비교

`-` 시간비교하는 방법 

In [64]:
t1=Sys.time()

In [65]:
t2=Sys.time()

In [66]:
t2-t1

Time difference of 0.1889238 secs

`-` 큰 매트릭스 만듬 

In [67]:
A=sample(1:9,size=100*2000000,replace=TRUE)

In [68]:
dim(A)<-c(2000000,100)
A 

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 2    5    2    9    7    7    6    9    2    6     ⋯     5     4    
 [2,] 9    3    3    2    1    7    9    4    6    9     ⋯     9     3    
 [3,] 6    6    6    4    8    4    3    8    8    9     ⋯     6     6    
 [4,] 5    8    4    6    6    2    2    1    8    7     ⋯     5     3    
 [5,] 8    4    9    1    8    2    5    4    2    1     ⋯     8     8    
 [6,] 1    5    8    4    8    7    7    8    7    7     ⋯     9     5    
 [7,] 3    8    2    7    1    5    5    3    8    9     ⋯     7     5    
 [8,] 2    9    3    5    2    4    5    7    7    9     ⋯     7     9    
 [9,] 1    3    2    9    1    7    3    2    1    7     ⋯     1     1    
[10,] 2    5    6    1    1    8    6    7    5    3     ⋯     7     2    
[11,] 6    8    7    1    6    2    9    2    3    6     ⋯     4     8    
[12,] 7    5    8    4    3    7    7    9    7    8     ⋯     9     6    
[13,] 6    1    1    2   

In [69]:
t1=Sys.time()
A %>% apply(1,min) %>% max 
t2=Sys.time()
t2-t1

[1] 2

Time difference of 4.945072 secs

In [70]:
t1=Sys.time()
vec<-c()
for(i in 1:2000000) vec[i]<-min(A[i,])
max(vec)
t2=Sys.time()
t2-t1

[1] 2

Time difference of 3.016647 secs

`-` for가 좀 더 빠르지만 코드는 apply가 더 간결해보인다. 

`-` for는 2000000을 계산하는 코드고 추가해야하지만 (변수가 많고 지저분하다) apply는 그렇지 않음 