In [20]:
import tensorflow as tf
import numpy as np

In [21]:
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### 텐서

`-` 수학에서 텐서: 다차원 배열 (0차원은 스칼라, 1차원은 벡터, 2차원은 매트릭스, 3차원이상은 텐서로 부른다) 

`-` 텐서플로우에서의 텐서: 여러가지 불편한 제약을 가진 다차원배열

`-` 일단 다차원 배열에 초점을 맞추자 (불편한 제약은 나중에 생각하자) 

#### 예비학습: 중첩리스트 

In [618]:
lst1 = [1,2]
lst2 = [[1,2],[3,4]]
lst3 = [[[1,2],[3,4]],[[5,6],[7,8]]]

In [620]:
lst1

[1, 2]

In [622]:
lst2

[[1, 2], [3, 4]]

In [623]:
lst3

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [625]:
lst3[0][1][0]

3

#### 선언

`-` 스칼라 

In [515]:
tf.constant(3) # 스칼라

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [560]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

`-` 벡터 

In [561]:
tf.constant([1,2,3,4]) # 벡터

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

`-` 매트릭스 

In [518]:
tf.constant([[1,2],[3,4]]) # 매트릭스

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [563]:
tf.constant([[1],[2],[3],[4]]) # 4*1 매트릭스 = column vector 

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [564]:
tf.constant([[1,2,3,4]]) # 1*4 매트릭스 = row vector

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

`-` 텐서

In [528]:
tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]]) # 텐서 

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

#### 타입

In [750]:
type(tf.constant(1))

tensorflow.python.framework.ops.EagerTensor

#### 인덱싱 

`-` 벡터의 인덱싱 

In [572]:
_vector = tf.constant([1,2,3,4])
_vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [573]:
_vector[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [566]:
_vector[1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

`-` 매트릭스의 인덱싱 

In [574]:
_matrix = tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [576]:
_matrix[0] # first row 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [578]:
_matrix[0,:] # first row 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [581]:
_matrix[:,0] # first col 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

`-` 텐서의 인덱싱 

In [604]:
_tensor = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
_tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [605]:
_tensor[0,:,:] # _tensor[0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [603]:
_tensor[:,0,:] # _tensor[:][0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6]], dtype=int32)>

In [606]:
_tensor[:,:,0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [5, 7]], dtype=int32)>

#### 텐서는 불편하다 

`-` 불편한 제약 
- 텐서의 모든 원소는 같은 dtype을 가져야 한다. 
- 텐서는 한번 생성되면 불변이다. 
- 텐서끼리의 연산에서 자료형이 다르면 형변환이 되지 않는다. 

`-` 텐서의 모든 원소는 같은 dtype를 가진다. 

In [485]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

`-` 텐서는 한번 생성되면 불변이다. (assingment 불가능) 

In [489]:
a= tf.constant([1,2,3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [490]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [492]:
a[0]=111

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

`-` 텐서의 연산에서 자료형이 다르면 연산이 불가능하다. 

In [494]:
tf.constant([1,2,3])+tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [495]:
tf.constant([1.0,2.0,3.0])+tf.constant([1.0,2.0,3.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 6.], dtype=float32)>

In [496]:
tf.constant([1,2,3])+tf.constant([1.0,2.0,3.0])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

`-` 심지어 같은 float형도 dtype이 다른경우 연산이 불가능 

In [497]:
tf.constant([1.0,2.0,3.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [499]:
tf.constant([1.0,2.0,3.0],dtype=tf.float64)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [500]:
tf.constant([1.0,2.0,3.0]) + tf.constant([1.0,2.0,3.0],dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]

In [547]:
tf.add(tf.constant([1,2,3]),tf.constant([1,2,3])) # 벡터+벡터 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [546]:
tf.add(tf.constant([1,2,3]),tf.constant(1)) # 벡터+스칼라

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

#### 텐서 $\to$ 넘파이 

In [552]:
a = tf.constant([[[1, 2],[3, 4],[5, 6]],[[1, 2],[3, 4],[5, 6]]])
a

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)>

In [555]:
np.array(a) # 방법1

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)

In [556]:
a.numpy() # 방법2

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)

#### 텐서의연산

In [636]:
a = tf.constant([[1, 2],[3, 4]])
b = tf.constant([[1, 0],[0, 2]]) # Could have also said `tf.ones([2,2])`

`-` 더하기

In [647]:
a,b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>)

In [639]:
tf.add(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 6]], dtype=int32)>

In [640]:
a+b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 6]], dtype=int32)>

`-` 곱하기 (elementwise)

In [648]:
a,b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>)

In [641]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 8]], dtype=int32)>

In [642]:
a*b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 8]], dtype=int32)>

`-` 행렬곱

In [649]:
a,b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>)

In [643]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [3, 8]], dtype=int32)>

In [644]:
a@b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [3, 8]], dtype=int32)>

`-` 트랜스포즈 

In [646]:
a,tf.transpose(a)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 3],
        [2, 4]], dtype=int32)>)

In [651]:
b,tf.transpose(b)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>)

`-` 역행렬 

In [666]:
tf.linalg.inv(a) # a 가 인트형이라서 나는 에러.. 

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixInverse}}; Op<name=MatrixInverse; signature=input:T -> output:T; attr=adjoint:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixInverse]

In [670]:
a=tf.constant([[1.0,2.0],[3.0,4.0]]) # a의 타입을 바꾸는 방법 따윈 없음. 새로 선언해야함. (텐서는 불변이므로) 
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2. ,  1. ],
       [ 1.5, -0.5]], dtype=float32)>

In [674]:
a@tf.linalg.inv(a) # 진짜 역행렬인지 확인

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

`-` 그러고보니까 `tf.linalg.` + `Tab` 을 눌러보니 쓸만한것들이 꽤 보임 $\to$ 필요하면 그때그때 찾아쓰면 되겠다 

In [679]:
tf.linalg.det(a)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [682]:
tf.linalg.trace(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

`-` 단순한 집계함수들 

In [729]:
a=tf.constant([[1.0,2.0],[3.0,4.0]])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [731]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [732]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [734]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [735]:
tf.reduce_sum((a-tf.reduce_mean(a))**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

`-` 행렬곱 고급

In [807]:
_I = tf.constant([[1.0,0.0],[0.0,1.0]])
_I

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

(상황1) (2,2) matrix @ (2,) vector 

In [814]:
_x = tf.constant([1.0,2.0])
_x # length 2 vector 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [819]:
_I @ _x

InvalidArgumentError: In[0] and In[1] has different ndims: [2,2] vs. [2] [Op:MatMul]

In [818]:
_x @ _I

InvalidArgumentError: In[0] and In[1] has different ndims: [2] vs. [2,2] [Op:MatMul]

(상황2)

In [811]:
_x = tf.constant([[1.0,2.0]])
_I @ _x

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,2], In[1]: [1,2] [Op:MatMul]

#### 형태변환

`-` 일반적인 reshape

In [721]:
_vector = tf.constant([1,2,3,4])  # 1*4 matrix
_vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [722]:
tf.reshape(_vector,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [723]:
tf.reshape(_vector,(4,1))

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [724]:
tf.reshape(_vector,(1,4))

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [748]:
tf.reshape(_vector,(1,4,1))

<tf.Tensor: shape=(1, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]]], dtype=int32)>

`-` -1와 함께하는 reshape (1)

In [826]:
_matrix = tf.constant([[1,2,3,4],[5,6,7,8]])
_matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [831]:
tf.reshape(_matrix,(1,8))

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8]], dtype=int32)>

In [832]:
tf.reshape(_matrix,(1,-1))

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8]], dtype=int32)>

In [833]:
tf.reshape(_matrix,(8,1))

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int32)>

In [834]:
tf.reshape(_matrix,(8,-1))

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int32)>

`-` -1과 함께 사용하는 reshape (2)

In [848]:
_tensor = tf.reshape(tf.constant(list(range(24))),[2,3,4])
_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [847]:
tf.reshape(_tensor,(12,-1))

<tf.Tensor: shape=(12, 2), dtype=int32, numpy=
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]], dtype=int32)>

In [849]:
tf.reshape(_tensor,(4,2,-1))

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]], dtype=int32)>

In [850]:
tf.reshape(_tensor,(-1))

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)>

#### 선언고급 

`-` 1만 포함된 텐서 

In [741]:
tf.ones((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [743]:
tf.ones([3,4]) # 이렇게 많이 쓰는것 같아요.. 괄호가 덜헷갈려서 그런가?

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

`-` 0만 포함된 텐서 

In [746]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

`-` range

In [775]:
tf.range(1,10) # 1에서 시작, 10에서 끝 (미포함) 

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [779]:
tf.range(1,10,3) # 1에서 시작, 10에서 끝 (미포함), 간격=3 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 7], dtype=int32)>

`-` linspace

In [756]:
tf.linspace(1,10,5) # 1에서 시작, 10에서 끝, 총 5개 

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])>

In [758]:
tf.linspace(2,5,5) # 2에서 시작, 5에서 끝, 총 5개 

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([2.  , 2.75, 3.5 , 4.25, 5.  ])>

In [766]:
tf.linspace([1,2],[10,5],5)

<tf.Tensor: shape=(5, 2), dtype=float64, numpy=
array([[ 1.  ,  2.  ],
       [ 3.25,  2.75],
       [ 5.5 ,  3.5 ],
       [ 7.75,  4.25],
       [10.  ,  5.  ]])>

In [768]:
tf.linspace([1,2],[10,5],5,axis=0)

<tf.Tensor: shape=(5, 2), dtype=float64, numpy=
array([[ 1.  ,  2.  ],
       [ 3.25,  2.75],
       [ 5.5 ,  3.5 ],
       [ 7.75,  4.25],
       [10.  ,  5.  ]])>

In [770]:
tf.linspace([1,2],[10,5],5,axis=1)

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[ 1.  ,  3.25,  5.5 ,  7.75, 10.  ],
       [ 2.  ,  2.75,  3.5 ,  4.25,  5.  ]])>

`-` 랜덤

In [780]:
tf.random.normal([10])

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 0.50885606, -0.5746844 , -0.8302203 , -0.23642251, -0.49897522,
        0.28917256, -0.47365862,  0.8249964 ,  1.2388225 ,  1.0043577 ],
      dtype=float32)>

In [783]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.51027644, -0.2602889 , -1.3138688 ],
       [ 0.5325183 , -1.6331427 ,  0.58964497],
       [ 0.33641338, -0.5991571 ,  1.540079  ]], dtype=float32)>

In [782]:
tf.random.uniform([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.65442157, 0.8139168 , 0.3262663 ],
       [0.08073592, 0.21870852, 0.54493797],
       [0.49900568, 0.6591847 , 0.5448785 ]], dtype=float32)>

`-` 각자 선호하는 다른방식으로 만들고 tf.constant로 변환하기

(예제) 리스트 $\to$ tf.Tensor

In [796]:
tf.constant([1]*10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)>

(예제) range $\to$ np.array $\to$ tf.Tensfor

In [795]:
tf.constant(np.array(range(24)).reshape(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

(예제) 단위행렬 

#### tf.concat 

`-` (2,2) concat (2,2) -> (4,2) 
- 첫번째축이 변하네? (axis=0)

In [909]:
a= tf.constant([[1,2],[3,4]])
b= -tf.constant([[1,2],[3,4]])

In [901]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]], dtype=int32)>

`-` (2,2) concat (2,2) -> (2,4) 
- 두번째축이 변하네? (axis=1)

In [908]:
a= tf.constant([[1,2],[3,4]])
b= -tf.constant([[1,2],[3,4]])

In [904]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]], dtype=int32)>

`-` (1,2) concat (1,2) -> (2,2) 
- 첫번째축이 변하네? (axis=0)

In [905]:
a= tf.constant([[1,2]])
b= -tf.constant([[1,2]])

In [906]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [-1, -2]], dtype=int32)>

`-` (1,2) concat (1,2) -> (1,4) 
- 두번째축이 변하네? (axis=1)

In [910]:
a= tf.constant([[1,2]])
b= -tf.constant([[1,2]])

In [911]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 1,  2, -1, -2]], dtype=int32)>

`-` (2,1) concat (2,1) -> (4,1)
- 첫번째축이 변하네? (axis=0)

In [912]:
a= tf.constant([[1],[2]])
b= -tf.constant([[1],[2]])

In [914]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[ 1],
       [ 2],
       [-1],
       [-2]], dtype=int32)>

`-` (2,1) concat (2,1) -> (2,2)
- 두번째축이 변하네? (axis=1)

In [915]:
a= tf.constant([[1],[2]])
b= -tf.constant([[1],[2]])

In [917]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1, -1],
       [ 2, -2]], dtype=int32)>

`-` (2,3,4,5) concat (2,3,4,5) -> (2,3,8,5) 
- 세번째축이 변하네? (axis=2)

In [937]:
a=tf.constant(np.array(range(2*3*4*5)).reshape(2,3,4,5))
b=-a

In [945]:
tf.concat([a,b],axis=2)

<tf.Tensor: shape=(2, 3, 8, 5), dtype=int64, numpy=
array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19],
         [   0,   -1,   -2,   -3,   -4],
         [  -5,   -6,   -7,   -8,   -9],
         [ -10,  -11,  -12,  -13,  -14],
         [ -15,  -16,  -17,  -18,  -19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39],
         [ -20,  -21,  -22,  -23,  -24],
         [ -25,  -26,  -27,  -28,  -29],
         [ -30,  -31,  -32,  -33,  -34],
         [ -35,  -36,  -37,  -38,  -39]],

        [[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59],
         [ -40,  -41,  -42,  -43,  -44],
         [ -45,  -46,  -47,  -48,  -49],
         [ -50,  -51,  -52,  -53,  -54],
 

`-` 신기한거 보여줄게요

In [952]:
a=tf.constant(np.array(range(2*3*4*5)).reshape(2,3,4,5))
b=-a

In [954]:
tf.concat([a,b],axis=-3)
# 1번째축 = axis 0 = axis -4 
# 2번째축 = axis 1 = axis -3 
# 3번째축 = axis 2 = axis -2
# 4번째축 = axis 3 = axis -1

<tf.Tensor: shape=(2, 6, 4, 5), dtype=int64, numpy=
array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39]],

        [[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59]],

        [[   0,   -1,   -2,   -3,   -4],
         [  -5,   -6,   -7,   -8,   -9],
         [ -10,  -11,  -12,  -13,  -14],
         [ -15,  -16,  -17,  -18,  -19]],

        [[ -20,  -21,  -22,  -23,  -24],
         [ -25,  -26,  -27,  -28,  -29],
         [ -30,  -31,  -32,  -33,  -34],
         [ -35,  -36,  -37,  -38,  -39]],

        [[ -40,  -41,  -42,  -43,  -44],
         [ -45,  -46,  -47,  -48,  -49],
         [ -50,  -51,  -52,  -53,  -

`-` (4,) concat (4,) -> (8,)
- 첫번째축이 변하네

In [949]:
a= tf.constant([1,2,3,4])
b= -a 

In [950]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 1,  2,  3,  4, -1, -2, -3, -4], dtype=int32)>

`-` (4,) concat (4,) -> (4,2) 
- 사실상 (4,1) concat (4,1) -> (4,2) 으로 해석가능하지 않겠어? // 안된다!

In [930]:
a= tf.constant([1,2,3,4])
b= -a 

In [934]:
tf.concat([a,b],axis=1)

InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat

- concat은 dim을 증가시키면서 결합할순없다. 

#### tf.stack 

`-` stack은 dim을 항상 증가시키는 방향으로 결합한다. 

`-` (3,) stack (3,)  

In [975]:
a = tf.constant([1,2,3])
b = tf.constant([3,4,5])

In [976]:
tf.stack([a,b])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

- 오.. 
- a,b를 (1,3) 으로 해석했군 
- 그런데 누가 a,b rowvector라고 했어? 

In [977]:
tf.stack([a,b],axis=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4],
       [3, 5]], dtype=int32)>

- a,b를 (3,1)로 해석하자 

`-` (2,3,4,5) stack (2,3,4,5) -> (?,?,?,?,?) 

In [978]:
a=tf.constant(np.array(range(2*3*4*5)).reshape(2,3,4,5))
b=-a

**case1:** (2,3,4,5) 를 (1,2,3,4,5) 로 해석 
- 최종차원은 ( ,2,3,4,5) stack ( ,2,3,4,5) = (2,2,3,4,5) // 0번째 축이 변하네요 

In [981]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int64, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[  60,   61,   62,   63,   64],
          [  65,   66,   67,   68,   69],
          [  70,   71,   72,   73,   74],
          [  75,   76,   77,   78,   79]],

         [[  80,   81,   82,   83,   84],
          [  85,   86,   87,   88,   89],
          [  90,   91,   92,   93,   94],
          [  95,   96,   97,   98,   99]],

         [[ 100,  101,  102,  103,  104],
          [ 105,  106,  107,  108,  109],
         

**case2:** (2,3,4,5) 를 (2,1,3,4,5) 로 해석 
- 최종차원은 (2, ,3,4,5) stack (2, ,3,4,5) = (2,2,3,4,5) // 1번째 축이 변하네요 

In [986]:
tf.stack([a,b],axis=1) 

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int64, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
         

**case3:** (2,3,4,5) 를 (2,3,1,4,5) 로 해석 
- 최종차원은 (2,3, ,4,5) stack (2,3, ,4,5) = (2,3,2,4,5) // 3번째 축이 변하네요 

In [987]:
tf.stack([a,b],axis=2) 

<tf.Tensor: shape=(2, 3, 2, 4, 5), dtype=int64, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]]],


        [[[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]]],


        [[[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
       

**case4:** (2,3,4,5) 를 (2,3,4,1,5) 로 해석 
- 최종차원은 (2,3,4, ,5) stack (2,3,4, ,5) = (2,3,2,2,5) // 4번째 축이 변하네요 // 끝에서 2번째 축이 변한다 

In [988]:
tf.stack([a,b],axis=-2) 

<tf.Tensor: shape=(2, 3, 4, 2, 5), dtype=int64, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   0,   -1,   -2,   -3,   -4]],

         [[   5,    6,    7,    8,    9],
          [  -5,   -6,   -7,   -8,   -9]],

         [[  10,   11,   12,   13,   14],
          [ -10,  -11,  -12,  -13,  -14]],

         [[  15,   16,   17,   18,   19],
          [ -15,  -16,  -17,  -18,  -19]]],


        [[[  20,   21,   22,   23,   24],
          [ -20,  -21,  -22,  -23,  -24]],

         [[  25,   26,   27,   28,   29],
          [ -25,  -26,  -27,  -28,  -29]],

         [[  30,   31,   32,   33,   34],
          [ -30,  -31,  -32,  -33,  -34]],

         [[  35,   36,   37,   38,   39],
          [ -35,  -36,  -37,  -38,  -39]]],


        [[[  40,   41,   42,   43,   44],
          [ -40,  -41,  -42,  -43,  -44]],

         [[  45,   46,   47,   48,   49],
          [ -45,  -46,  -47,  -48,  -49]],

         [[  50,   51,   52,   53,   54],
          [ -50,  -51,  -52,  -53,  -54

**case5:** (2,3,4,5) 를 (2,3,4,5,1) 로 해석 
- 최종차원은 (2,3,4,5, ) stack (2,3,4,5, ) = (2,3,4,5,2) // 5번째 축이 변하네요 // 마지막 축이 변한다 

In [989]:
tf.stack([a,b],axis=-1) 

<tf.Tensor: shape=(2, 3, 4, 5, 2), dtype=int64, numpy=
array([[[[[   0,    0],
          [   1,   -1],
          [   2,   -2],
          [   3,   -3],
          [   4,   -4]],

         [[   5,   -5],
          [   6,   -6],
          [   7,   -7],
          [   8,   -8],
          [   9,   -9]],

         [[  10,  -10],
          [  11,  -11],
          [  12,  -12],
          [  13,  -13],
          [  14,  -14]],

         [[  15,  -15],
          [  16,  -16],
          [  17,  -17],
          [  18,  -18],
          [  19,  -19]]],


        [[[  20,  -20],
          [  21,  -21],
          [  22,  -22],
          [  23,  -23],
          [  24,  -24]],

         [[  25,  -25],
          [  26,  -26],
          [  27,  -27],
          [  28,  -28],
          [  29,  -29]],

         [[  30,  -30],
          [  31,  -31],
          [  32,  -32],
          [  33,  -33],
          [  34,  -34]],

         [[  35,  -35],
          [  36,  -36],
          [  37,  -37],
          [  38, 

#### tf.einsum

### 미분 

`-` 예제 

In [427]:
x = tf.Variable(2.0)
with tf.GradientTape() as tape:
    y = x**2

In [428]:
dy_dx = tape.gradient(y, x)

In [429]:
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

`-` 예제2

In [362]:
# import tensorflow as tf
# gpus = tf.config.experimental.list_physical_devices('GPU')
# for gpu in gpus:
#     tf.config.experimental.set_memory_growth(gpu, True)

In [476]:
tf.random.set_seed(43052)
_x= tf.constant([20.1, 22.2, 22.7, 23.3, 24.4, 25.1, 26.2, 27.3, 28.4, 30.4],dtype=tf.float64) 
X= tf.transpose(tf.concat([[tf.constant([1.0]*10,dtype=tf.float64)],[_x]],0))
beta_true= tf.constant([10.2,2.2],shape=(2,1),dtype=tf.float64)
epsilon= tf.random.normal([10,1],dtype=tf.float64) 
y= X@beta_ture + epsilon 

In [477]:
X = tf.Variable(X)
#beta = tf.Variable(tf.linalg.inv(tf.transpose(X)@X)@tf.transpose(X)@y)
beta = tf.Variable(beta_true)
#beta = tf.Variable(tf.constant([10.2,2.2],shape=(2,1),dtype=tf.float64)) #tf.Variable(beta)
epsilon= tf.Variable(epsilon) 
y = tf.Variable(y)

In [478]:
beta

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[10.2],
       [ 2.2]])>

In [479]:
with tf.GradientTape(persistent=True) as tape: #with tf.GradientTape(persistent=True) as tape:
    loss = tf.transpose(y-X@beta)@(y-X@beta)

In [480]:
tape.gradient(loss,beta)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[ -3.55753624],
       [-76.87306574]])>

$$\frac{\partial}{\partial \boldsymbol{\beta}}loss = -2{\bf X}^\top {\bf y}+ 2{\bf X}^\top{\bf X} {\boldsymbol \beta}$$

In [282]:
my_vars = {
    'beta': beta
}

grad = tape.gradient(loss, my_vars)
grad

{'beta': <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[0.],
        [0.]], dtype=float32)>}