# (노트) 파이썬 - 리스트

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [파이썬]

### list

#### 선언

`-` 리스트의 선언 

In [90]:
a=[11,22]

In [91]:
a

[11, 22]

In [92]:
type(a)

list

`-` 비어있는 리스트의 선언 

In [93]:
a=[] # 방법1
a

[]

In [94]:
a=list() # 방법2
a

[]

#### 연산

`-` 더하기연산: 벡터덧셈으로 정의되지 않음 

In [95]:
a=[11,12]
b=[12,13]

(우리의 예상)

- $a=(11,12)$
- $b=(12,13)$
- $a+b=(23,25)$

In [96]:
a+b

[11, 12, 12, 13]

- 우리의 예상과 다른 결과가 나타남 $\to$ 파이썬은 R처럼 좋은 계산기능이 자동으로 내장되어있지 않음 

`-` 브로드캐스팅과 같이 R에서 당연하게 사용하였던 기능을 사용할 수 없음. 

In [97]:
a=[1,2,3]
b=3 
a+b

TypeError: can only concatenate list (not "int") to list

`-` 뺄샘은 정의되지 않음 

In [98]:
a=[1,2]
b=[1,2]
a-b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

`-` 곱하기는 정의가능 

In [99]:
a=[1,2]

In [100]:
2*a # a+a 

[1, 2, 1, 2]

`-` 나눗셈은 정의되지 않음 

In [101]:
a=[1,2,1,2] 
a/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

`-` list에서는 더하기와 곱하기를 조금 다르게 해석한다. 원소의 `추가`와 `반복추가`의 개념으로 해석함. 

In [102]:
a=[1,2]
b=[11,22,33]

In [103]:
2*a+3*b

[1, 2, 1, 2, 11, 22, 33, 11, 22, 33, 11, 22, 33]

In [104]:
a+[33]+[345]

[1, 2, 33, 345]

`-` 더하기와 곱하기는 `추가`와 `반복추가`를 의미하지만 그렇다고 뺄셈과 나눗셈이 삭제를 의미하는건 아님. 

In [105]:
a=[1,2,3]
a-[3] # 이런건 없다

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [106]:
a=[1,2,1,2]
a/2 # 이런건 없다

TypeError: unsupported operand type(s) for /: 'list' and 'int'

`-` 더하기와 곱하기 추가와 반복추가의 기능을 가지고 있어서 은근히 편할때가 있긴 있음. 그런데 일반적인 벡터연산을 하고싶을 경우도 있음. 

(예제1)

In [107]:
a=[1,2]
b=[3,4] 

a+b = [4,6] 이 되도록 할려면?

(풀이1)

list끼리는 수치연산이 불가능하지만, list의 원소끼리는 가능할 수 있음. 

In [108]:
a[0]+b[0] # a의 첫번째 원소를 추출, b의 첫번째 원소를 추출, 둘을 더함 

4

In [109]:
a[1]+b[1] 

6

In [110]:
[a[0]+b[0], a[1]+b[1]]

[4, 6]

풀이가 가능한 이유? a,b는 리스트이지만 a[0], a[1], b[0], b[1]은 인트형임. 인트형은 + 연산이 가능했음.

In [111]:
type(a[0])

int

(풀이2)

numpy 패키지 (파이썬의 여러 수치연산을 담당하는 라이브러리) 활용 
- 이러한 벡터연산은 누구나 필요로 하는 연산임. 
- 내가 아니더라도 누군가가 프로그래밍화 시켜놓을 것임. 
- 그 누군가가 자신이 만든 코드를 잘 정리하여 무료로 배포했을 수 있음. (패키지를 배포한다고 표현함) 
- 그 패키지를 우리는 가져와서 쓰기만 하면된다. 

패지키를 설치하는 방법 
- `pip install numpy` 
- `conda install -c conda-forge numpy` 

In [117]:
import numpy # 설치한 패키지를 쓰겠다고 선언함

In [118]:
a=[1,2]
b=[3,4]

In [119]:
aa=numpy.array(a) ## aa는 리스트가 아니라 넘파이 어레이, numpy.array()는 numpy패키지에서 제공하는 array함수를 쓰겠다는 의미
bb=numpy.array(b) ## bb는 리스트가 아니라 넘파이 어레이, numpy.array()는 numpy패키지에서 제공하는 array함수를 쓰겠다는 의미

In [120]:
aa+bb

array([4, 6])

이런것도 가능함 

In [121]:
aa*bb 

array([3, 8])

In [122]:
aa*bb+aa 

array([ 4, 10])

(풀이3) 

In [123]:
import numpy as np # 설치한 패키지를 쓰겠다고 선언함, 그런데 numpy 말고 np라는 이름으로 쓰겠음. 

In [124]:
np.array(a)+np.array(b)

array([4, 6])

#### 인덱싱

`-` str형과 동일한 내용

### list 고급

#### 콘테이너형 객체 + 가변객체 

`-` 리스트의 원소는 int, float 따위만 가능한 것이 아니다.

In [125]:
lst=[1,3.14,True,'a',[1,2],(1,2),
      {'name':'guebin','age':38},{1,2,3}]

각 원소의 type을 알아보자. 

In [126]:
type(lst[0])

int

In [127]:
type(lst[1])

float

In [128]:
type(lst[2])

bool

In [129]:
type(lst[3])

str

In [130]:
type(lst[4])

list

In [131]:
type(lst[5])

tuple

In [132]:
type(lst[6])

dict

In [133]:
type(lst[7])

set

`-` 리스트 원소를 수정할 수 있다. 

In [134]:
a=[1,2,3]
a

[1, 2, 3]

In [135]:
a[0]

1

In [136]:
a[0]=111

In [137]:
a

[111, 2, 3]

`-` 원소수정은 당연한 기능같은데 이것이 불가능한 경우도 있다. 

(가능한경우)

In [138]:
a=['g','u','e','b','i','n']
a

['g', 'u', 'e', 'b', 'i', 'n']

In [139]:
a[0]

'g'

In [140]:
a[0]='G'

In [141]:
a

['G', 'u', 'e', 'b', 'i', 'n']

(불가능한경우) 스트링에서는 원소수정이 되지 않음. 

In [142]:
a='guebin'
a

'guebin'

In [143]:
a[0]

'g'

In [144]:
a[0]='G'

TypeError: 'str' object does not support item assignment

`-` 리스트 원소 삭제 

(예제)

아래와 같이 문자열로 된 리스트를 선언하자. 

In [145]:
a= ['G','u','e','b','i','n']
a

['G', 'u', 'e', 'b', 'i', 'n']

사실 더 쉽게 할 수 있음. 

In [146]:
a= 'Guebin'
a=list(a)
a

['G', 'u', 'e', 'b', 'i', 'n']

첫번째 원소를 삭제하고 싶다면? 

In [147]:
del a[0]

In [148]:
a

['u', 'e', 'b', 'i', 'n']

이 상태에서 다시 첫번째 원소를 삭제하면? 

In [149]:
del a[0]

In [150]:
a

['e', 'b', 'i', 'n']

`-` 리스트 원소 추가

(예제) 비어있는 리스트를 만들고 원소 0,1,2를 차례로 추가하여 보자. 

(풀이1) 

In [151]:
a=[]
a

[]

In [152]:
a=a+[0]
a

[0]

In [153]:
a=a+[1]
a

[0, 1]

In [154]:
a=a+[2]
a

[0, 1, 2]

(풀이2) 

In [155]:
a=[]
a

[]

In [156]:
a += [0]
a

[0]

In [157]:
a += [1]
a

[0, 1]

In [158]:
a += [2]
a

[0, 1, 2]

(풀이3) 리스트 특화기능(=메소드)를 이용

In [159]:
a=[]
a

[]

In [160]:
a.append(0)
a

[0]

In [161]:
a.append(1)
a

[0, 1]

In [162]:
a.append(2)
a

[0, 1, 2]

`-` `a+[4]`와  `a.append(4)`의 차이점은? 

(관찰1)

In [163]:
a=[1,2,3]
a+[4] ## 리스트 a와 리스트 [4]의 연산결과를 알려줘

[1, 2, 3, 4]

In [164]:
a ## a는 그대로임. 변화없음. 

[1, 2, 3]

(관찰2)

In [165]:
a=[1,2,3]
a.append(4)

In [166]:
a # a가 변화함. 

[1, 2, 3, 4]

비슷해보이지만 약간의 미묘한 차이점이 있음. 

`a.append(4)`: `a`를 append하라. $\rightarrow$ `a`가 변함. 

`a+[4]`: `a`와 `[4]`를 add하라. 

#### 메소드 (리스트 자료형에 특화된 특수한 함수들)

**(append)**

In [167]:
a.append?

Signature: a.append(object, /)
Docstring: Append object to the end of the list.
Type:      builtin_function_or_method


In [168]:
a=[1,2,3]
a.append(4)
a

[1, 2, 3, 4]

**(clear)**

In [169]:
a.clear?

Signature: a.clear()
Docstring: Remove all items from list.
Type:      builtin_function_or_method


In [170]:
a=[1,2,3]
a.clear()
a

[]

**(copy)**

In [171]:
a.copy?

Signature: a.copy()
Docstring: Return a shallow copy of the list.
Type:      builtin_function_or_method


In [172]:
a=[1,2,3]
b=a.copy()
b

[1, 2, 3]

**(count)**

In [173]:
a.count?

Signature: a.count(value, /)
Docstring: Return number of occurrences of value.
Type:      builtin_function_or_method


In [174]:
a=[1,1,2,3.14,3.14]
a.count(3.14)

2

**(extend)**

In [175]:
a.extend?

Signature: a.extend(iterable, /)
Docstring: Extend list by appending elements from the iterable.
Type:      builtin_function_or_method


In [176]:
a=[1,2,3]
b=[1,2,3,4,5,6]
a.extend(b)
a

[1, 2, 3, 1, 2, 3, 4, 5, 6]

**(index)**

In [177]:
a.index?

Signature: a.index(value, start=0, stop=9223372036854775807, /)
Docstring:
Return first index of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method


In [178]:
a=[1,2,3,3,4,4,5,6]
a.index(5)

6

**(insert)**

In [179]:
a.insert?

Signature: a.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method


In [180]:
a=[1,2,3]
a.insert(0,88)
a

[88, 1, 2, 3]

**(pop)**

In [181]:
a.pop?

Signature: a.pop(index=-1, /)
Docstring:
Remove and return item at index (default last).

Raises IndexError if list is empty or index is out of range.
Type:      builtin_function_or_method


In [182]:
a=[1,2,3,4]
a.pop()
a

[1, 2, 3]

In [183]:
a.pop()
a

[1, 2]

In [184]:
a.pop()
a

[1]

In [185]:
a.pop()
a

[]

**(remove)**

In [186]:
a.remove?

Signature: a.remove(value, /)
Docstring:
Remove first occurrence of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method


In [187]:
a=[1,2,3,44]
a.remove(44)

In [188]:
a

[1, 2, 3]

**(reverse)**

In [189]:
a.reverse?

Signature: a.reverse()
Docstring: Reverse *IN PLACE*.
Type:      builtin_function_or_method


In [190]:
a=[1,2,3]
a.reverse()
a

[3, 2, 1]

**(sort)**

In [191]:
a.sort?

Signature: a.sort(*, key=None, reverse=False)
Docstring:
Sort the list in ascending order and return None.

The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
order of two equal elements is maintained).

If a key function is given, apply it once to each list item and sort them,
ascending or descending, according to their function values.

The reverse flag can be set to sort in descending order.
Type:      builtin_function_or_method


In [192]:
a=[1,3,2,4]
a.sort()
a

[1, 2, 3, 4]

#### 중첩리스트 

In [193]:
A=[[1,2,3],[4,5,6],[7,8,9]]
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

`-` A는 아래와 같은 매트릭스로 생각할 수 있다. 

${\bf A} = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$

`-` ${\bf A}$에서 (1,1)의 원소를 뽑고싶다! = 1을 뽑고싶음 

In [194]:
A[0,0] 

TypeError: list indices must be integers or slices, not tuple

- 실패 

In [195]:
A[0][0]

1

- 성공 

`-` 성공의 이유분석 

In [196]:
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [197]:
A[0]

[1, 2, 3]

In [198]:
A[0][0]

1

`-` ${\bf A}$에서 (2,3)위치의 원소를 뽑아보자. $\to$ 파이썬 인덱스로 치면 (1,2) 

In [199]:
A[1][2]

6

`-` 매트릭스는 아니지만 매트릭스 같아!

> 1차원 배열을 다차원 배열로 확장할 수 있는 기본아이디어를 제공함 

#### 리스트컴프리헨션 ($\star\star\star$)

`-` 리스트컴프리헨션을 이해하기 전에 for문에 대하여 알아보자. 

[예비학습] `for`문 벼락치기

프로그램 안에서 반복해서 무엇인가를 하고싶다? $\rightarrow$ `for`

In [200]:
for i in [0,1,2,3]: ## 반복실행계획
    print(i) ## 반복실행내용 (주의: 4칸 띄어쓰기를 해야 오류가 나지 않음)

0
1
2
3


In [201]:
for i in [0,1,2,4]: 
    print(i)

0
1
2
4


In [202]:
i=0
print(i)
i=1
print(i)
i=2


print(i)
i=4
print(i)

0
1
2
4


In [203]:
sumi=0
for i in [0,1,2,4]: ## 반복실행계획
    sumi=sumi+i 

In [204]:
sumi

7

In [205]:
sumi=0
i=0
sumi=sumi+i
i=1
sumi=sumi+i
i=2
sumi=sumi+i
i=4
sumi=sumi+i

In [206]:
sumi

7

예비학습 끝! 

`-` 예제: $2^0,2^1,2^2,2^3,2^4,2^5$를 계산해보자. 

(풀이1) 직접입력방식

In [207]:
x=[2**0,2**1,2**2,2**3,2**4,2**5]

In [208]:
x

[1, 2, 4, 8, 16, 32]

- 진짜 나쁜코드; $2^0,\dots,2^{100}$까지 계산하라고 하면? 

(풀이2) for를 이용

In [209]:
x=[]
for i in [0,1,2,3,4,5]:
    x.append(2**i)

In [210]:
x

[1, 2, 4, 8, 16, 32]

- 그럭저럭 괜찮은 풀이 

(풀이3) for를 이용

In [211]:
x=[]
for i in [0,1,2,3,4,5]:
    x=x+[2**i]

In [212]:
x

[1, 2, 4, 8, 16, 32]

- 그럭저럭 괜찮은 풀이 

(풀이4) for를 이용

In [213]:
x=[]
for i in [0,1,2,3,4,5]:
    x+=[2**i] ### 암기법: x=x+[2**i] 에서 중복되는것을 제거하고 순서를 바꾼다... 

In [214]:
x

[1, 2, 4, 8, 16, 32]

- 그럭저럭 괜찮은 풀이 

(풀이5) 리스트컴프리헨션을 이용

In [215]:
x=[2**i for i in [0,1,2,3,4,5]]

In [216]:
x

[1, 2, 4, 8, 16, 32]

`-` 리스트컴프리헨션 문법의 암기방법 

- 조건제시법을 연상하라. 
- $\big\{2^0,2^1,2^2,2^3,2^4,2^5\big\}=\big\{2^i: i=0,1,\dots, 5 \big\}$

`-` 리스트 컴프리헨션이란? 
- 리스트를 매우 효율적으로 만드는 테크닉 
- `for`문에 비하여 가지고 있는 장점: (1) 코드가 간단하다. (2) 빠르다. 

`-` 예제: 리스트 컴프리핸션을 이용하여 아래와 같은 리스트를 만들어라.

In [217]:
['SSSS','PPPP','AAAA','MMMM']

['SSSS', 'PPPP', 'AAAA', 'MMMM']

(풀이)

In [218]:
[i*4 for i in 'SPAM']

['SSSS', 'PPPP', 'AAAA', 'MMMM']

`-` 예제: 리스트 컴프리헨션을 이용하여 아래와 같은 리스트를 만들어라. 

In [219]:
['X1','X2','X3','Y1','Y2','Y3']

['X1', 'X2', 'X3', 'Y1', 'Y2', 'Y3']

(풀이)

In [220]:
[i+j for i in 'XY' for j in '123']

['X1', 'X2', 'X3', 'Y1', 'Y2', 'Y3']

`-` 예제: 리스트 컴프리헨션을 이용하여 통계1...통계5, 수학1...수학5반을 만들어라. 

(풀이)

In [221]:
[i+j for i in ['stat','math'] for j in '12345']

['stat1',
 'stat2',
 'stat3',
 'stat4',
 'stat5',
 'math1',
 'math2',
 'math3',
 'math4',
 'math5']

- $\{"xy": x \in \{stat,math\}, y \in \{1,2,3,4,5\}\}$

(풀이) for문을 쓰려면 좀 복잡해진다. 

In [222]:
for i in ['stat','math']:
    for j in '12345':
        print(i+j)

stat1
stat2
stat3
stat4
stat5
math1
math2
math3
math4
math5


`-` 예제: 'jbnu'를 이용하여 아래와 같은 리스트를 만들어라. 

In [223]:
['j','b','n','u']

['j', 'b', 'n', 'u']

(풀이)

In [224]:
[x for x in 'jbnu']

['j', 'b', 'n', 'u']

(다른풀이) 물론아래가 가능한건 나도 알아.. 

In [225]:
list('jbnu')

['j', 'b', 'n', 'u']

`-` 예제: x에는 무엇이 있을까?

(경우1)

In [226]:
x=1
lst=[]
for x in 'jbnu': 
    lst += x
lst

['j', 'b', 'n', 'u']

In [227]:
x # 확인

'u'

(경우2)

In [228]:
x=1 
lst= [x for x in 'jbnu']
lst 

['j', 'b', 'n', 'u']

In [229]:
x # 확인

1

- 진짜 미묘하게 다르죠? 

`-` 예제: [X1,X2,...,X100]와 같은 리스트를 만들어보라. 

(풀이) 

In [230]:
['X'+str(i) for i in [1,2,3,4]] #이걸 4가 아니라 100까지 써야한단 말이지..

['X1', 'X2', 'X3', 'X4']

In [231]:
['X'+str(i) for i in 1:100] # 와 진짜.. 이게 안되네

SyntaxError: invalid syntax (<ipython-input-231-0a41394296d6>, line 1)

[예비학습]

In [232]:
range(0,10) 

range(0, 10)

- 이게뭐야..?

In [233]:
_a = range(0,10)
_a?

Type:        range
String form: range(0, 10)
Length:      10
Docstring:  
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).


- 우리가 아는 범위에서는 모르겠다.. 뭐 이상한게 있나보다.. 

In [234]:
list(range(0,10)) # 0은 포함 10은 미포함 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

- 이게 중요한것임. 하여튼 range(0,10)를 리스트화! 시키면 이런식으로 바뀐다. 

In [235]:
list(range(10)) # 0은 생략가능 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [236]:
list(range(1,10,2)) # 0은 포함, 10은 미포함, step= 2

[1, 3, 5, 7, 9]

예비학습 끝 

In [237]:
['X'+str(i) for i in list(range(1,11))] ## 출력결과가 너무 기니까 101대신에 11로 바꾸자

['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10']

(풀이2)

In [238]:
['X'+str(i) for i in range(1,11)] ## 굳이 리스트화 시키지 않아도 동작한다. 

['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10']

(딴생각) 생각해보니까 for문 뒤에 올수 있는 것이 무엇인지 생각하는것도 흥미로움 

In [239]:
for i in '1234': 
    print(i)

1
2
3
4


In [240]:
for i in [1,2,3,4]:
    print(i)

1
2
3
4


In [241]:
for i in (1,2,3,4): # (1,2,3,4)는 튜플 
    print(i) 

1
2
3
4


In [242]:
for i in {1,2,3,4}: # {1,2,3,4}는 set 
    print(i)

1
2
3
4


In [243]:
for i in {'1번':'이재명','2번':'윤석열'}: # 딕셔너리
    print(i)

1번
2번
