# (노트) tf.constant, tnp

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [데이터과학]

In [107]:
import tensorflow as tf
import numpy as np

In [108]:
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### tf.constant 

`-` 수학에서 텐서: 다차원 배열 (0차원은 스칼라, 1차원은 벡터, 2차원은 매트릭스, 3차원이상은 텐서로 부른다) 

`-` 텐서플로우에서의 텐서: 여러가지 불편한 제약을 가진 다차원배열

`-` 일단 다차원 배열에 초점을 맞추자 (불편한 제약은 나중에 생각하자) 

#### 예비학습: 중첩리스트 

`-` 예제: 그냥 리스트 

In [109]:
lst = [1,2] 
lst

[1, 2]

In [110]:
lst[0]

1

In [111]:
lst[1]

2

`-` 예제: 중첩리스트 

In [112]:
lst = [[1,2],[3,4]]
lst

[[1, 2], [3, 4]]

In [113]:
lst[0]

[1, 2]

In [114]:
lst[0][0]

1

In [115]:
lst[1]

[3, 4]

In [116]:
lst[1][0]

3

이런 행렬 느낌이다. (실제로는 행렬은 아닌데)
```
1 2 
3 4 
```
이때 각 원소는 [0][0], [0][1], [1][0], [1][1] 로 접근가능하다. 

In [117]:
print(lst[0][0])
print(lst[0][1])
print(lst[1][0])
print(lst[1][1])

1
2
3
4


`-` 예제: (4,1) 벡터

In [118]:
lst= [[1,2],[2,3],[3,4],[4,5]]  # (4,2) 매트릭스로 생각가능 
lst 

[[1, 2], [2, 3], [3, 4], [4, 5]]

In [119]:
lst = [[1],[2],[3],[4]]  # (4,1) 매트릭스로 생각가능 --> 길이가 4인 col-vector로 생각가능
lst 

[[1], [2], [3], [4]]

`-` 예제: (1,4) 벡터

In [120]:
lst = [[1,2,3,4],[5,6,7,8]] # (2,4) 매트릭스로 생각가능 
lst

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [121]:
lst = [[1,2,3,4]] # (1,4) 매트릭스로 생각가능 --> 길이가 4인 row-vector로 생각가능 
lst 

[[1, 2, 3, 4]]

`-` 예제: (2,2,2) array

In [122]:
lst = [[[1,2],[3,4]],[[5,6],[7,8]]]
lst 

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [123]:
print(lst[0][0][0])
print(lst[0][0][1])
print(lst[0][1][0])
print(lst[0][1][1])
print(lst[1][0][0])
print(lst[1][0][1])
print(lst[1][1][0])
print(lst[1][1][1])

1
2
3
4
5
6
7
8


#### 선언

`-` 스칼라 

In [124]:
tf.constant(3) # 스칼라

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [125]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

`-` 벡터 

In [126]:
tf.constant([1,2,3,4]) # 벡터

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

`-` 매트릭스 

In [127]:
tf.constant([[1,2],[3,4]]) # 매트릭스

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [128]:
tf.constant([[1],[2],[3],[4]]) # 4*1 매트릭스 = column vector 

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [129]:
tf.constant([[1,2,3,4]]) # 1*4 매트릭스 = row vector

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

`-` 텐서

In [130]:
tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]]) # 텐서 

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

#### 타입

In [131]:
type(tf.constant(1))

tensorflow.python.framework.ops.EagerTensor

#### 인덱싱 

`-` 벡터의 인덱싱 

In [132]:
_vector = tf.constant([1,2,3,4])
_vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [133]:
_vector[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [134]:
_vector[1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

`-` 매트릭스의 인덱싱 

In [135]:
_matrix = tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [136]:
_matrix[0] # first row 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [137]:
_matrix[0,:] # first row 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [138]:
_matrix[:,0] # first col 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

`-` 텐서의 인덱싱 

In [139]:
_tensor = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
_tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [140]:
_tensor[0,:,:] # _tensor[0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [141]:
_tensor[:,0,:] # _tensor[:][0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6]], dtype=int32)>

In [142]:
_tensor[:,:,0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [5, 7]], dtype=int32)>

#### tf.constant는 불편하다. 

`-` 불편한 제약 
- 텐서의 모든 원소는 같은 dtype을 가져야 한다. (이건 뭐 사실 그렇게 까지 제약은 아님)
- 텐서는 한번 생성되면 불변이다.  
- 텐서끼리의 연산에서 자료형이 다르면 형변환이 되지 않는다. 

`-` 텐서의 모든 원소는 같은 dtype를 가진다. 

In [143]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

`-` 텐서는 한번 생성되면 불변이다. (assingment 불가능) 

In [144]:
a= tf.constant([1,2,3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [145]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [146]:
a[0]=111

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

`-` 텐서의 연산에서 자료형이 다르면 연산이 불가능하다. 

In [147]:
tf.constant([1,2,3])+tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [148]:
tf.constant([1.0,2.0,3.0])+tf.constant([1.0,2.0,3.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 6.], dtype=float32)>

In [149]:
tf.constant([1,2,3])+tf.constant([1.0,2.0,3.0])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

`-` 심지어 같은 float형도 dtype이 다른경우 연산이 불가능 

In [150]:
tf.constant([1.0,2.0,3.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [151]:
tf.constant([1.0,2.0,3.0],dtype=tf.float64)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [152]:
tf.constant([1.0,2.0,3.0]) + tf.constant([1.0,2.0,3.0],dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]

In [153]:
tf.add(tf.constant([1,2,3]),tf.constant([1,2,3])) # 벡터+벡터 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [154]:
tf.add(tf.constant([1,2,3]),tf.constant(1)) # 벡터+스칼라

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

#### tf.constant $\to$ 넘파이 

In [155]:
a = tf.constant([[[1, 2],[3, 4],[5, 6]],[[1, 2],[3, 4],[5, 6]]])
a

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)>

In [156]:
np.array(a) # 방법1

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)

In [157]:
a.numpy() # 방법2

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)

#### 연산

In [158]:
a = tf.constant([[1, 2],[3, 4]])
b = tf.constant([[1, 0],[0, 2]]) # Could have also said `tf.ones([2,2])`

`-` 더하기

In [159]:
a,b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>)

In [160]:
tf.add(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 6]], dtype=int32)>

In [161]:
a+b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 6]], dtype=int32)>

`-` 곱하기 (elementwise)

In [162]:
a,b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>)

In [163]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 8]], dtype=int32)>

In [164]:
a*b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 8]], dtype=int32)>

`-` 행렬곱

In [165]:
a,b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>)

In [166]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [3, 8]], dtype=int32)>

In [167]:
a@b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [3, 8]], dtype=int32)>

`-` 트랜스포즈 

In [168]:
a,tf.transpose(a)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 3],
        [2, 4]], dtype=int32)>)

In [169]:
b,tf.transpose(b)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>)

`-` 역행렬 

In [170]:
tf.linalg.inv(a) # a 가 인트형이라서 나는 에러.. 

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixInverse}}; Op<name=MatrixInverse; signature=input:T -> output:T; attr=adjoint:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixInverse]

In [171]:
a=tf.constant([[1.0,2.0],[3.0,4.0]]) # a의 타입을 바꾸는 방법 따윈 없음. 새로 선언해야함. (텐서는 불변이므로) 
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2. ,  1. ],
       [ 1.5, -0.5]], dtype=float32)>

In [172]:
a@tf.linalg.inv(a) # 진짜 역행렬인지 확인

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

`-` 그러고보니까 `tf.linalg.` + `Tab` 을 눌러보니 쓸만한것들이 꽤 보임 $\to$ 필요하면 그때그때 찾아쓰면 되겠다 

In [173]:
tf.linalg.det(a)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [174]:
tf.linalg.trace(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

`-` 단순한 집계함수들 

In [175]:
a=tf.constant([[1.0,2.0],[3.0,4.0]])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [176]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [177]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [178]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [179]:
tf.reduce_sum((a-tf.reduce_mean(a))**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

`-` 행렬곱 고급

In [180]:
_I = tf.constant([[1.0,0.0],[0.0,1.0]])
_I

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

(상황1) (2,2) matrix @ (2,) vector 

In [181]:
_x = tf.constant([1.0,2.0])
_x # length 2 vector 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [182]:
_I @ _x

InvalidArgumentError: In[0] and In[1] has different ndims: [2,2] vs. [2] [Op:MatMul]

In [188]:
_x @ _I # 혹시 이렇게 하면되나? (_x가 row벡터인가?)

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,1], In[1]: [2,2] [Op:MatMul]

(상황2) (2,2) matrix @ (1,2) matrix 

In [184]:
_x = tf.constant([[1.0,2.0]])
_I @ _x

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,2], In[1]: [1,2] [Op:MatMul]

(상황3) (2,2) matrix @ (2,1) matrix 

In [189]:
_x = tf.constant([[1.0],[2.0]])
_I @ _x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

#### 형태변환

`-` 일반적인 reshape

In [190]:
_vector = tf.constant([1,2,3,4])  # 1*4 matrix
_vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [191]:
tf.reshape(_vector,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [192]:
tf.reshape(_vector,(4,1))

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [193]:
tf.reshape(_vector,(1,4))

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [194]:
tf.reshape(_vector,(1,4,1))

<tf.Tensor: shape=(1, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]]], dtype=int32)>

`-` -1와 함께하는 reshape (1)

In [195]:
_matrix = tf.constant([[1,2,3,4],[5,6,7,8]])
_matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [196]:
tf.reshape(_matrix,(1,8))

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8]], dtype=int32)>

In [197]:
tf.reshape(_matrix,(1,-1))

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8]], dtype=int32)>

In [198]:
tf.reshape(_matrix,(8,1))

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int32)>

In [199]:
tf.reshape(_matrix,(8,-1))

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int32)>

`-` -1과 함께 사용하는 reshape (2)

In [200]:
_tensor = tf.reshape(tf.constant(list(range(24))),[2,3,4])
_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [201]:
tf.reshape(_tensor,(12,-1))

<tf.Tensor: shape=(12, 2), dtype=int32, numpy=
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]], dtype=int32)>

In [202]:
tf.reshape(_tensor,(4,2,-1))

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]], dtype=int32)>

In [203]:
tf.reshape(_tensor,(-1))

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)>

#### 선언고급 

`-` 1만 포함된 텐서 

In [204]:
tf.ones((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [205]:
tf.ones([3,4]) # 이렇게 많이 쓰는것 같아요.. 괄호가 덜헷갈려서 그런가?

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

`-` 0만 포함된 텐서 

In [206]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

`-` range

In [207]:
tf.range(1,10) # 1에서 시작, 10에서 끝 (미포함) 

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [208]:
tf.range(1,10,3) # 1에서 시작, 10에서 끝 (미포함), 간격=3 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 7], dtype=int32)>

`-` linspace

In [209]:
tf.linspace(1,10,5) # 1에서 시작, 10에서 끝, 총 5개 

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])>

In [210]:
tf.linspace(2,5,5) # 2에서 시작, 5에서 끝, 총 5개 

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([2.  , 2.75, 3.5 , 4.25, 5.  ])>

In [211]:
tf.linspace([1,2],[10,5],5)

<tf.Tensor: shape=(5, 2), dtype=float64, numpy=
array([[ 1.  ,  2.  ],
       [ 3.25,  2.75],
       [ 5.5 ,  3.5 ],
       [ 7.75,  4.25],
       [10.  ,  5.  ]])>

In [212]:
tf.linspace([1,2],[10,5],5,axis=0)

<tf.Tensor: shape=(5, 2), dtype=float64, numpy=
array([[ 1.  ,  2.  ],
       [ 3.25,  2.75],
       [ 5.5 ,  3.5 ],
       [ 7.75,  4.25],
       [10.  ,  5.  ]])>

In [213]:
tf.linspace([1,2],[10,5],5,axis=1)

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[ 1.  ,  3.25,  5.5 ,  7.75, 10.  ],
       [ 2.  ,  2.75,  3.5 ,  4.25,  5.  ]])>

`-` 랜덤

In [214]:
tf.random.normal([10])

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.91207266,  0.4553366 , -0.625696  ,  0.13458338, -0.590419  ,
        1.3888592 , -0.34752023, -1.5480285 , -0.5614436 , -0.625263  ],
      dtype=float32)>

In [215]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.7860687 ,  0.426065  , -1.6084508 ],
       [-1.3761368 , -1.1805011 , -1.4238403 ],
       [ 0.61376315, -1.8956203 ,  0.32558846]], dtype=float32)>

In [216]:
tf.random.uniform([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.78784823, 0.9053154 , 0.2893002 ],
       [0.59846234, 0.40294218, 0.3080392 ],
       [0.49561286, 0.3228103 , 0.3395319 ]], dtype=float32)>

`-` 각자 선호하는 다른방식으로 만들고 tf.constant로 변환하기

(예제) 리스트 $\to$ tf.Tensor

In [217]:
tf.constant([1]*10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)>

(예제) range $\to$ np.array $\to$ tf.Tensfor

In [218]:
tf.constant(np.array(range(24)).reshape(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

(예제) 단위행렬 

#### tf.concat 

`-` (2,2) concat (2,2) -> (4,2) 
- 첫번째축이 변하네? (axis=0)

In [219]:
a= tf.constant([[1,2],[3,4]])
b= -tf.constant([[1,2],[3,4]])

In [220]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]], dtype=int32)>

`-` (2,2) concat (2,2) -> (2,4) 
- 두번째축이 변하네? (axis=1)

In [221]:
a= tf.constant([[1,2],[3,4]])
b= -tf.constant([[1,2],[3,4]])

In [222]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]], dtype=int32)>

`-` (1,2) concat (1,2) -> (2,2) 
- 첫번째축이 변하네? (axis=0)

In [223]:
a= tf.constant([[1,2]])
b= -tf.constant([[1,2]])

In [224]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [-1, -2]], dtype=int32)>

`-` (1,2) concat (1,2) -> (1,4) 
- 두번째축이 변하네? (axis=1)

In [225]:
a= tf.constant([[1,2]])
b= -tf.constant([[1,2]])

In [226]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 1,  2, -1, -2]], dtype=int32)>

`-` (2,1) concat (2,1) -> (4,1)
- 첫번째축이 변하네? (axis=0)

In [227]:
a= tf.constant([[1],[2]])
b= -tf.constant([[1],[2]])

In [228]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[ 1],
       [ 2],
       [-1],
       [-2]], dtype=int32)>

`-` (2,1) concat (2,1) -> (2,2)
- 두번째축이 변하네? (axis=1)

In [229]:
a= tf.constant([[1],[2]])
b= -tf.constant([[1],[2]])

In [230]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1, -1],
       [ 2, -2]], dtype=int32)>

`-` (2,3,4,5) concat (2,3,4,5) -> (2,3,8,5) 
- 세번째축이 변하네? (axis=2)

In [231]:
a=tf.constant(np.array(range(2*3*4*5)).reshape(2,3,4,5))
b=-a

In [232]:
tf.concat([a,b],axis=2)

<tf.Tensor: shape=(2, 3, 8, 5), dtype=int64, numpy=
array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19],
         [   0,   -1,   -2,   -3,   -4],
         [  -5,   -6,   -7,   -8,   -9],
         [ -10,  -11,  -12,  -13,  -14],
         [ -15,  -16,  -17,  -18,  -19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39],
         [ -20,  -21,  -22,  -23,  -24],
         [ -25,  -26,  -27,  -28,  -29],
         [ -30,  -31,  -32,  -33,  -34],
         [ -35,  -36,  -37,  -38,  -39]],

        [[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59],
         [ -40,  -41,  -42,  -43,  -44],
         [ -45,  -46,  -47,  -48,  -49],
         [ -50,  -51,  -52,  -53,  -54],
 

`-` 신기한거 보여줄게요

In [233]:
a=tf.constant(np.array(range(2*3*4*5)).reshape(2,3,4,5))
b=-a

In [234]:
tf.concat([a,b],axis=-3)
# 1번째축 = axis 0 = axis -4 
# 2번째축 = axis 1 = axis -3 
# 3번째축 = axis 2 = axis -2
# 4번째축 = axis 3 = axis -1

<tf.Tensor: shape=(2, 6, 4, 5), dtype=int64, numpy=
array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39]],

        [[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59]],

        [[   0,   -1,   -2,   -3,   -4],
         [  -5,   -6,   -7,   -8,   -9],
         [ -10,  -11,  -12,  -13,  -14],
         [ -15,  -16,  -17,  -18,  -19]],

        [[ -20,  -21,  -22,  -23,  -24],
         [ -25,  -26,  -27,  -28,  -29],
         [ -30,  -31,  -32,  -33,  -34],
         [ -35,  -36,  -37,  -38,  -39]],

        [[ -40,  -41,  -42,  -43,  -44],
         [ -45,  -46,  -47,  -48,  -49],
         [ -50,  -51,  -52,  -53,  -

`-` (4,) concat (4,) -> (8,)
- 첫번째축이 변하네

In [235]:
a= tf.constant([1,2,3,4])
b= -a 

In [236]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 1,  2,  3,  4, -1, -2, -3, -4], dtype=int32)>

`-` (4,) concat (4,) -> (4,2) 
- 사실상 (4,1) concat (4,1) -> (4,2) 으로 해석가능하지 않겠어? // 안된다!

In [237]:
a= tf.constant([1,2,3,4])
b= -a 

In [238]:
tf.concat([a,b],axis=1)

InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat

- concat은 dim을 증가시키면서 결합할순없다. 

#### tf.stack 

`-` stack은 dim을 항상 증가시키는 방향으로 결합한다. 

`-` (3,) stack (3,)  

In [239]:
a = tf.constant([1,2,3])
b = tf.constant([3,4,5])

In [240]:
tf.stack([a,b])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

- 오.. 
- a,b를 (1,3) 으로 해석했군 
- 그런데 누가 a,b rowvector라고 했어? 

In [241]:
tf.stack([a,b],axis=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4],
       [3, 5]], dtype=int32)>

- a,b를 (3,1)로 해석하자 

`-` (2,3,4,5) stack (2,3,4,5) -> (?,?,?,?,?) 

In [242]:
a=tf.constant(np.array(range(2*3*4*5)).reshape(2,3,4,5))
b=-a

**case1:** (2,3,4,5) 를 (1,2,3,4,5) 로 해석 
- 최종차원은 ( ,2,3,4,5) stack ( ,2,3,4,5) = (2,2,3,4,5) // 0번째 축이 변하네요 

In [243]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int64, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[  60,   61,   62,   63,   64],
          [  65,   66,   67,   68,   69],
          [  70,   71,   72,   73,   74],
          [  75,   76,   77,   78,   79]],

         [[  80,   81,   82,   83,   84],
          [  85,   86,   87,   88,   89],
          [  90,   91,   92,   93,   94],
          [  95,   96,   97,   98,   99]],

         [[ 100,  101,  102,  103,  104],
          [ 105,  106,  107,  108,  109],
         

**case2:** (2,3,4,5) 를 (2,1,3,4,5) 로 해석 
- 최종차원은 (2, ,3,4,5) stack (2, ,3,4,5) = (2,2,3,4,5) // 1번째 축이 변하네요 

In [244]:
tf.stack([a,b],axis=1) 

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int64, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
         

**case3:** (2,3,4,5) 를 (2,3,1,4,5) 로 해석 
- 최종차원은 (2,3, ,4,5) stack (2,3, ,4,5) = (2,3,2,4,5) // 3번째 축이 변하네요 

In [245]:
tf.stack([a,b],axis=2) 

<tf.Tensor: shape=(2, 3, 2, 4, 5), dtype=int64, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]]],


        [[[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]]],


        [[[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
       

**case4:** (2,3,4,5) 를 (2,3,4,1,5) 로 해석 
- 최종차원은 (2,3,4, ,5) stack (2,3,4, ,5) = (2,3,2,2,5) // 4번째 축이 변하네요 // 끝에서 2번째 축이 변한다 

In [246]:
tf.stack([a,b],axis=-2) 

<tf.Tensor: shape=(2, 3, 4, 2, 5), dtype=int64, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   0,   -1,   -2,   -3,   -4]],

         [[   5,    6,    7,    8,    9],
          [  -5,   -6,   -7,   -8,   -9]],

         [[  10,   11,   12,   13,   14],
          [ -10,  -11,  -12,  -13,  -14]],

         [[  15,   16,   17,   18,   19],
          [ -15,  -16,  -17,  -18,  -19]]],


        [[[  20,   21,   22,   23,   24],
          [ -20,  -21,  -22,  -23,  -24]],

         [[  25,   26,   27,   28,   29],
          [ -25,  -26,  -27,  -28,  -29]],

         [[  30,   31,   32,   33,   34],
          [ -30,  -31,  -32,  -33,  -34]],

         [[  35,   36,   37,   38,   39],
          [ -35,  -36,  -37,  -38,  -39]]],


        [[[  40,   41,   42,   43,   44],
          [ -40,  -41,  -42,  -43,  -44]],

         [[  45,   46,   47,   48,   49],
          [ -45,  -46,  -47,  -48,  -49]],

         [[  50,   51,   52,   53,   54],
          [ -50,  -51,  -52,  -53,  -54

**case5:** (2,3,4,5) 를 (2,3,4,5,1) 로 해석 
- 최종차원은 (2,3,4,5, ) stack (2,3,4,5, ) = (2,3,4,5,2) // 5번째 축이 변하네요 // 마지막 축이 변한다 

In [247]:
tf.stack([a,b],axis=-1) 

<tf.Tensor: shape=(2, 3, 4, 5, 2), dtype=int64, numpy=
array([[[[[   0,    0],
          [   1,   -1],
          [   2,   -2],
          [   3,   -3],
          [   4,   -4]],

         [[   5,   -5],
          [   6,   -6],
          [   7,   -7],
          [   8,   -8],
          [   9,   -9]],

         [[  10,  -10],
          [  11,  -11],
          [  12,  -12],
          [  13,  -13],
          [  14,  -14]],

         [[  15,  -15],
          [  16,  -16],
          [  17,  -17],
          [  18,  -18],
          [  19,  -19]]],


        [[[  20,  -20],
          [  21,  -21],
          [  22,  -22],
          [  23,  -23],
          [  24,  -24]],

         [[  25,  -25],
          [  26,  -26],
          [  27,  -27],
          [  28,  -28],
          [  29,  -29]],

         [[  30,  -30],
          [  31,  -31],
          [  32,  -32],
          [  33,  -33],
          [  34,  -34]],

         [[  35,  -35],
          [  36,  -36],
          [  37,  -37],
          [  38, 

#### tf.einsum

### tnp

`-` tf.constant 는 솔직히 너무 쓰기 힘들다.

`-` 넘파이와 비교

(불만1)

In [248]:
tf.constant([1,2,3,4]).reshape(2,2)

AttributeError: 
        'EagerTensor' object has no attribute 'reshape'.
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()

In [249]:
np.array([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

(불만2)

In [250]:
tf.constant([1,2,3,4])+tf.constant([1.0,2.0,3.0,4.0])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

In [251]:
np.array([1,2,3,4])+ np.array([1.0,2.0,3.0,4.0])

array([2., 4., 6., 8.])

(불만3)

In [252]:
np.array([[1,2],[3,4]]).transpose()

array([[1, 3],
       [2, 4]])

In [253]:
np.array([[1,2],[3,4]]).T

array([[1, 3],
       [2, 4]])

In [254]:
np.transpose(np.array([[1,2],[3,4]]))

array([[1, 3],
       [2, 4]])

In [255]:
tf.constant([[1,2],[3,4]]).transpose()

AttributeError: 
        'EagerTensor' object has no attribute 'transpose'.
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()

In [256]:
tf.constant([[1,2],[3,4]]).T

AttributeError: 
        'EagerTensor' object has no attribute 'T'.
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()

In [257]:
tf.transpose(tf.constant([[1,2],[3,4]]))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

(불만4)

In [258]:
np.array([1,2,3,4]).max()

4

In [259]:
tf.reduce_max(tf.constant([1,2,3,4]))

<tf.Tensor: shape=(), dtype=int32, numpy=4>

... 저 이런거 하루 종일 생각해낼수도 있어요 

#### tnp 사용방법 (불만해결방법)

In [260]:
import tensorflow.experimental.numpy as tnp # 앞으로 텐서플로에서 np 대신에 tnp를 사용하면 넘파이에 익숙한 문법을 모두 쓸 수 있고 
tnp.experimental_enable_numpy_behavior()  # 생성된 tf.constant 자료형은 넘파이와 유사하게 동작한다. 

#### 선언, 선언고급

In [261]:
tnp.array([1,2,3,4])

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [262]:
tnp.diag([1,2,3])

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])>

#### 타입

In [263]:
type(tnp.array([1,2,3]))

tensorflow.python.framework.ops.EagerTensor

#### tf.constant로 만들어도 마치 넘파이인듯 쓰는 기능들

`-` reshape, transpose, T 

In [264]:
tf.constant([1,2,3,4]).reshape(2,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [265]:
tf.constant([1,2,3,4]).reshape(2,2).transpose()

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [266]:
tf.constant([1,2,3,4]).reshape(2,2).T

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

`-` max 

In [267]:
tf.constant([1,2,3,4]).reshape(2,2).T.max()

<tf.Tensor: shape=(), dtype=int32, numpy=4>

`-` dtype이 다를텐데?!

In [268]:
tf.constant([1,2,3,4])+tf.constant([1.0,2.0,3.0,4.0]) # 이건 감동임

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([2., 4., 6., 8.])>

`-` (2,2) @ (2,) 연산? 

넘파이에서는 (2,)를 대충 상황에 맞춰서 row-vector 혹은 col-vector 로 생각함 

In [291]:
np.array([11,22]) @ np.array([[1,0],[0,1]])

array([11, 22])

In [292]:
np.array([[1,0],[0,1]]) @ np.array([11,22])

array([11, 22])

넘파이가 된다면 나도된다? 

In [296]:
tf.constant([11,22]) @ tf.constant([[1,0],[0,1]]) 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([11, 22], dtype=int32)>

In [297]:
tf.constant([[1,0],[0,1]]) @ tf.constant([11,22])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([11, 22], dtype=int32)>

row-vector, col-vector를 명시하면 명시하는대로 잘 출려된다. 

In [300]:
tf.constant([[11,22]]) @ tf.constant([[1,0],[0,1]]) 

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[11, 22]], dtype=int32)>

In [301]:
tf.constant([[1,0],[0,1]]) @ tf.constant([[11],[22]])

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[11],
       [22]], dtype=int32)>

잘못명시하면 계산불가능 

In [304]:
tf.constant([[11],[22]]) @ tf.constant([[1,0],[0,1]]) # (2,1) @ (2,2) 

ValueError: Matrix size-incompatible: In[0]: [2,1], In[1]: [2,2] [Op:MatMul]

In [305]:
tf.constant([[1,0],[0,1]]) @ tf.constant([[11,22]]) # (2,2) @ (1,2) 

ValueError: Matrix size-incompatible: In[0]: [2,2], In[1]: [1,2] [Op:MatMul]

#### 그렇지만 tnp.array = np.array 는 아님 

In [306]:
a=tnp.array([1,2,3])
a

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [307]:
a[0]

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [308]:
a[0]=22

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment