# (노트) tf.constant, tnp, tf.variable

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [데이터과학]

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.config.experimental.list_physical_devices('GPU')

2022-03-13 22:16:23.156202: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### tf.constant 

`-` 수학에서 텐서: 다차원 배열 (0차원은 스칼라, 1차원은 벡터, 2차원은 매트릭스, 3차원이상은 텐서로 부른다) 

`-` 텐서플로우에서의 텐서: 여러가지 불편한 제약을 가진 다차원배열

`-` 일단 다차원 배열에 초점을 맞추자 (불편한 제약은 나중에 생각하자) 

#### 예비학습: 중첩리스트 

In [3]:
lst1 = [1,2]
lst2 = [[1,2],[3,4]]
lst3 = [[[1,2],[3,4]],[[5,6],[7,8]]]

In [4]:
lst1

[1, 2]

In [5]:
lst2

[[1, 2], [3, 4]]

In [6]:
lst3

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [7]:
lst3[0][1][0]

3

#### 선언

`-` 스칼라 

In [8]:
tf.constant(3) # 스칼라

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [9]:
tf.constant(3.14)

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

`-` 벡터 

In [10]:
tf.constant([1,2,3,4]) # 벡터

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

`-` 매트릭스 

In [11]:
tf.constant([[1,2],[3,4]]) # 매트릭스

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [12]:
tf.constant([[1],[2],[3],[4]]) # 4*1 매트릭스 = column vector 

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [13]:
tf.constant([[1,2,3,4]]) # 1*4 매트릭스 = row vector

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

`-` 텐서

In [14]:
tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]]) # 텐서 

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

#### 타입

In [15]:
type(tf.constant(1))

tensorflow.python.framework.ops.EagerTensor

#### 인덱싱 

`-` 벡터의 인덱싱 

In [16]:
_vector = tf.constant([1,2,3,4])
_vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [17]:
_vector[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [18]:
_vector[1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

`-` 매트릭스의 인덱싱 

In [19]:
_matrix = tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [20]:
_matrix[0] # first row 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [21]:
_matrix[0,:] # first row 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [22]:
_matrix[:,0] # first col 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

`-` 텐서의 인덱싱 

In [23]:
_tensor = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
_tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [24]:
_tensor[0,:,:] # _tensor[0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [25]:
_tensor[:,0,:] # _tensor[:][0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6]], dtype=int32)>

In [26]:
_tensor[:,:,0]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [5, 7]], dtype=int32)>

#### tf.constant는 불편하다. 

`-` 불편한 제약 
- 텐서의 모든 원소는 같은 dtype을 가져야 한다. (이건 뭐 사실 그렇게 까지 제약은 아님)
- 텐서는 한번 생성되면 불변이다.  
- 텐서끼리의 연산에서 자료형이 다르면 형변환이 되지 않는다. 

`-` 텐서의 모든 원소는 같은 dtype를 가진다. 

In [27]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

`-` 텐서는 한번 생성되면 불변이다. (assingment 불가능) 

In [28]:
a= tf.constant([1,2,3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [29]:
a[0]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [30]:
a[0]=111

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

`-` 텐서의 연산에서 자료형이 다르면 연산이 불가능하다. 

In [ ]:
tf.constant([1,2,3])+tf.constant([1,2,3])

In [31]:
tf.constant([1.0,2.0,3.0])+tf.constant([1.0,2.0,3.0])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 4., 6.], dtype=float32)>

In [32]:
tf.constant([1,2,3])+tf.constant([1.0,2.0,3.0])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

`-` 심지어 같은 float형도 dtype이 다른경우 연산이 불가능 

In [ ]:
tf.constant([1.0,2.0,3.0])

In [ ]:
tf.constant([1.0,2.0,3.0],dtype=tf.float64)

In [ ]:
tf.constant([1.0,2.0,3.0]) + tf.constant([1.0,2.0,3.0],dtype=tf.float64)

In [33]:
tf.add(tf.constant([1,2,3]),tf.constant([1,2,3])) # 벡터+벡터 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [34]:
tf.add(tf.constant([1,2,3]),tf.constant(1)) # 벡터+스칼라

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

#### tf.constant $\to$ 넘파이 

In [35]:
a = tf.constant([[[1, 2],[3, 4],[5, 6]],[[1, 2],[3, 4],[5, 6]]])
a

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)>

In [36]:
np.array(a) # 방법1

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)

In [37]:
a.numpy() # 방법2

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)

#### 연산

In [38]:
a = tf.constant([[1, 2],[3, 4]])
b = tf.constant([[1, 0],[0, 2]]) # Could have also said `tf.ones([2,2])`

`-` 더하기

In [39]:
a,b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>)

In [40]:
tf.add(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 6]], dtype=int32)>

In [41]:
a+b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 6]], dtype=int32)>

`-` 곱하기 (elementwise)

In [42]:
a,b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>)

In [43]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 8]], dtype=int32)>

In [44]:
a*b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 8]], dtype=int32)>

`-` 행렬곱

In [45]:
a,b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>)

In [46]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [3, 8]], dtype=int32)>

In [47]:
a@b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [3, 8]], dtype=int32)>

`-` 트랜스포즈 

In [48]:
a,tf.transpose(a)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 3],
        [2, 4]], dtype=int32)>)

In [49]:
b,tf.transpose(b)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 0],
        [0, 2]], dtype=int32)>)

`-` 역행렬 

In [50]:
tf.linalg.inv(a) # a 가 인트형이라서 나는 에러.. 

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixInverse}}; Op<name=MatrixInverse; signature=input:T -> output:T; attr=adjoint:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixInverse]

In [52]:
a=tf.constant([[1.0,2.0],[3.0,4.0]]) # a의 타입을 바꾸는 방법 따윈 없음. 새로 선언해야함. (텐서는 불변이므로) 
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2. ,  1. ],
       [ 1.5, -0.5]], dtype=float32)>

In [53]:
a@tf.linalg.inv(a) # 진짜 역행렬인지 확인

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

`-` 그러고보니까 `tf.linalg.` + `Tab` 을 눌러보니 쓸만한것들이 꽤 보임 $\to$ 필요하면 그때그때 찾아쓰면 되겠다 

In [54]:
tf.linalg.det(a)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [55]:
tf.linalg.trace(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

`-` 단순한 집계함수들 

In [56]:
a=tf.constant([[1.0,2.0],[3.0,4.0]])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [57]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [58]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [59]:
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [60]:
tf.reduce_sum((a-tf.reduce_mean(a))**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

`-` 행렬곱 고급

In [61]:
_I = tf.constant([[1.0,0.0],[0.0,1.0]])
_I

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

(상황1) (2,2) matrix @ (2,) vector 

In [62]:
_x = tf.constant([1.0,2.0])
_x # length 2 vector 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [63]:
_I @ _x

InvalidArgumentError: In[0] and In[1] has different ndims: [2,2] vs. [2] [Op:MatMul]

In [64]:
_x @ _I

InvalidArgumentError: In[0] and In[1] has different ndims: [2] vs. [2,2] [Op:MatMul]

(상황2)

In [65]:
_x = tf.constant([[1.0,2.0]])
_I @ _x

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,2], In[1]: [1,2] [Op:MatMul]

#### 형태변환

`-` 일반적인 reshape

In [66]:
_vector = tf.constant([1,2,3,4])  # 1*4 matrix
_vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [67]:
tf.reshape(_vector,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [68]:
tf.reshape(_vector,(4,1))

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [69]:
tf.reshape(_vector,(1,4))

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

In [70]:
tf.reshape(_vector,(1,4,1))

<tf.Tensor: shape=(1, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]]], dtype=int32)>

`-` -1와 함께하는 reshape (1)

In [71]:
_matrix = tf.constant([[1,2,3,4],[5,6,7,8]])
_matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [72]:
tf.reshape(_matrix,(1,8))

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8]], dtype=int32)>

In [73]:
tf.reshape(_matrix,(1,-1))

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8]], dtype=int32)>

In [74]:
tf.reshape(_matrix,(8,1))

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int32)>

In [75]:
tf.reshape(_matrix,(8,-1))

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]], dtype=int32)>

`-` -1과 함께 사용하는 reshape (2)

In [76]:
_tensor = tf.reshape(tf.constant(list(range(24))),[2,3,4])
_tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [77]:
tf.reshape(_tensor,(12,-1))

<tf.Tensor: shape=(12, 2), dtype=int32, numpy=
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]], dtype=int32)>

In [78]:
tf.reshape(_tensor,(4,2,-1))

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]], dtype=int32)>

In [79]:
tf.reshape(_tensor,(-1))

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23], dtype=int32)>

#### 선언고급 

`-` 1만 포함된 텐서 

In [80]:
tf.ones((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [81]:
tf.ones([3,4]) # 이렇게 많이 쓰는것 같아요.. 괄호가 덜헷갈려서 그런가?

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

`-` 0만 포함된 텐서 

In [82]:
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

`-` range

In [83]:
tf.range(1,10) # 1에서 시작, 10에서 끝 (미포함) 

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [84]:
tf.range(1,10,3) # 1에서 시작, 10에서 끝 (미포함), 간격=3 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 7], dtype=int32)>

`-` linspace

In [85]:
tf.linspace(1,10,5) # 1에서 시작, 10에서 끝, 총 5개 

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])>

In [86]:
tf.linspace(2,5,5) # 2에서 시작, 5에서 끝, 총 5개 

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([2.  , 2.75, 3.5 , 4.25, 5.  ])>

In [87]:
tf.linspace([1,2],[10,5],5)

<tf.Tensor: shape=(5, 2), dtype=float64, numpy=
array([[ 1.  ,  2.  ],
       [ 3.25,  2.75],
       [ 5.5 ,  3.5 ],
       [ 7.75,  4.25],
       [10.  ,  5.  ]])>

In [88]:
tf.linspace([1,2],[10,5],5,axis=0)

<tf.Tensor: shape=(5, 2), dtype=float64, numpy=
array([[ 1.  ,  2.  ],
       [ 3.25,  2.75],
       [ 5.5 ,  3.5 ],
       [ 7.75,  4.25],
       [10.  ,  5.  ]])>

In [89]:
tf.linspace([1,2],[10,5],5,axis=1)

<tf.Tensor: shape=(2, 5), dtype=float64, numpy=
array([[ 1.  ,  3.25,  5.5 ,  7.75, 10.  ],
       [ 2.  ,  2.75,  3.5 ,  4.25,  5.  ]])>

`-` 랜덤

In [90]:
tf.random.normal([10])

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.21191281, -0.09523091, -0.5312206 , -0.32049605,  0.9571035 ,
        0.41285414,  1.1231737 ,  1.3968489 , -0.5419953 ,  0.34586024],
      dtype=float32)>

In [91]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.72437006, -0.20378877,  1.2660425 ],
       [ 0.2847317 ,  0.23916264,  0.6108841 ],
       [-0.2158736 , -1.7517151 , -0.80852485]], dtype=float32)>

In [92]:
tf.random.uniform([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.10655355, 0.32047832, 0.79253376],
       [0.37487423, 0.41997838, 0.7606356 ],
       [0.94742894, 0.02878726, 0.06079328]], dtype=float32)>

`-` 각자 선호하는 다른방식으로 만들고 tf.constant로 변환하기

(예제) 리스트 $\to$ tf.Tensor

In [93]:
tf.constant([1]*10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)>

(예제) range $\to$ np.array $\to$ tf.Tensfor

In [94]:
tf.constant(np.array(range(24)).reshape(2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

(예제) 단위행렬 

#### tf.concat 

`-` (2,2) concat (2,2) -> (4,2) 
- 첫번째축이 변하네? (axis=0)

In [95]:
a= tf.constant([[1,2],[3,4]])
b= -tf.constant([[1,2],[3,4]])

In [96]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]], dtype=int32)>

`-` (2,2) concat (2,2) -> (2,4) 
- 두번째축이 변하네? (axis=1)

In [97]:
a= tf.constant([[1,2],[3,4]])
b= -tf.constant([[1,2],[3,4]])

In [98]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]], dtype=int32)>

`-` (1,2) concat (1,2) -> (2,2) 
- 첫번째축이 변하네? (axis=0)

In [99]:
a= tf.constant([[1,2]])
b= -tf.constant([[1,2]])

In [100]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [-1, -2]], dtype=int32)>

`-` (1,2) concat (1,2) -> (1,4) 
- 두번째축이 변하네? (axis=1)

In [101]:
a= tf.constant([[1,2]])
b= -tf.constant([[1,2]])

In [102]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 1,  2, -1, -2]], dtype=int32)>

`-` (2,1) concat (2,1) -> (4,1)
- 첫번째축이 변하네? (axis=0)

In [103]:
a= tf.constant([[1],[2]])
b= -tf.constant([[1],[2]])

In [104]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[ 1],
       [ 2],
       [-1],
       [-2]], dtype=int32)>

`-` (2,1) concat (2,1) -> (2,2)
- 두번째축이 변하네? (axis=1)

In [105]:
a= tf.constant([[1],[2]])
b= -tf.constant([[1],[2]])

In [106]:
tf.concat([a,b],axis=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1, -1],
       [ 2, -2]], dtype=int32)>

`-` (2,3,4,5) concat (2,3,4,5) -> (2,3,8,5) 
- 세번째축이 변하네? (axis=2)

In [107]:
a=tf.constant(np.array(range(2*3*4*5)).reshape(2,3,4,5))
b=-a

In [108]:
tf.concat([a,b],axis=2)

<tf.Tensor: shape=(2, 3, 8, 5), dtype=int64, numpy=
array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19],
         [   0,   -1,   -2,   -3,   -4],
         [  -5,   -6,   -7,   -8,   -9],
         [ -10,  -11,  -12,  -13,  -14],
         [ -15,  -16,  -17,  -18,  -19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39],
         [ -20,  -21,  -22,  -23,  -24],
         [ -25,  -26,  -27,  -28,  -29],
         [ -30,  -31,  -32,  -33,  -34],
         [ -35,  -36,  -37,  -38,  -39]],

        [[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59],
         [ -40,  -41,  -42,  -43,  -44],
         [ -45,  -46,  -47,  -48,  -49],
         [ -50,  -51,  -52,  -53,  -54],
 

`-` 신기한거 보여줄게요

In [109]:
a=tf.constant(np.array(range(2*3*4*5)).reshape(2,3,4,5))
b=-a

In [110]:
tf.concat([a,b],axis=-3)
# 1번째축 = axis 0 = axis -4 
# 2번째축 = axis 1 = axis -3 
# 3번째축 = axis 2 = axis -2
# 4번째축 = axis 3 = axis -1

<tf.Tensor: shape=(2, 6, 4, 5), dtype=int64, numpy=
array([[[[   0,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9],
         [  10,   11,   12,   13,   14],
         [  15,   16,   17,   18,   19]],

        [[  20,   21,   22,   23,   24],
         [  25,   26,   27,   28,   29],
         [  30,   31,   32,   33,   34],
         [  35,   36,   37,   38,   39]],

        [[  40,   41,   42,   43,   44],
         [  45,   46,   47,   48,   49],
         [  50,   51,   52,   53,   54],
         [  55,   56,   57,   58,   59]],

        [[   0,   -1,   -2,   -3,   -4],
         [  -5,   -6,   -7,   -8,   -9],
         [ -10,  -11,  -12,  -13,  -14],
         [ -15,  -16,  -17,  -18,  -19]],

        [[ -20,  -21,  -22,  -23,  -24],
         [ -25,  -26,  -27,  -28,  -29],
         [ -30,  -31,  -32,  -33,  -34],
         [ -35,  -36,  -37,  -38,  -39]],

        [[ -40,  -41,  -42,  -43,  -44],
         [ -45,  -46,  -47,  -48,  -49],
         [ -50,  -51,  -52,  -53,  -

`-` (4,) concat (4,) -> (8,)
- 첫번째축이 변하네

In [111]:
a= tf.constant([1,2,3,4])
b= -a 

In [112]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 1,  2,  3,  4, -1, -2, -3, -4], dtype=int32)>

`-` (4,) concat (4,) -> (4,2) 
- 사실상 (4,1) concat (4,1) -> (4,2) 으로 해석가능하지 않겠어? // 안된다!

In [113]:
a= tf.constant([1,2,3,4])
b= -a 

In [114]:
tf.concat([a,b],axis=1)

InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat

- concat은 dim을 증가시키면서 결합할순없다. 

#### tf.stack 

`-` stack은 dim을 항상 증가시키는 방향으로 결합한다. 

`-` (3,) stack (3,)  

In [115]:
a = tf.constant([1,2,3])
b = tf.constant([3,4,5])

In [116]:
tf.stack([a,b])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

- 오.. 
- a,b를 (1,3) 으로 해석했군 
- 그런데 누가 a,b rowvector라고 했어? 

In [117]:
tf.stack([a,b],axis=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4],
       [3, 5]], dtype=int32)>

- a,b를 (3,1)로 해석하자 

`-` (2,3,4,5) stack (2,3,4,5) -> (?,?,?,?,?) 

In [118]:
a=tf.constant(np.array(range(2*3*4*5)).reshape(2,3,4,5))
b=-a

**case1:** (2,3,4,5) 를 (1,2,3,4,5) 로 해석 
- 최종차원은 ( ,2,3,4,5) stack ( ,2,3,4,5) = (2,2,3,4,5) // 0번째 축이 변하네요 

In [119]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int64, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[  60,   61,   62,   63,   64],
          [  65,   66,   67,   68,   69],
          [  70,   71,   72,   73,   74],
          [  75,   76,   77,   78,   79]],

         [[  80,   81,   82,   83,   84],
          [  85,   86,   87,   88,   89],
          [  90,   91,   92,   93,   94],
          [  95,   96,   97,   98,   99]],

         [[ 100,  101,  102,  103,  104],
          [ 105,  106,  107,  108,  109],
         

**case2:** (2,3,4,5) 를 (2,1,3,4,5) 로 해석 
- 최종차원은 (2, ,3,4,5) stack (2, ,3,4,5) = (2,2,3,4,5) // 1번째 축이 변하네요 

In [120]:
tf.stack([a,b],axis=1) 

<tf.Tensor: shape=(2, 2, 3, 4, 5), dtype=int64, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]]],


        [[[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
         

**case3:** (2,3,4,5) 를 (2,3,1,4,5) 로 해석 
- 최종차원은 (2,3, ,4,5) stack (2,3, ,4,5) = (2,3,2,4,5) // 3번째 축이 변하네요 

In [121]:
tf.stack([a,b],axis=2) 

<tf.Tensor: shape=(2, 3, 2, 4, 5), dtype=int64, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   5,    6,    7,    8,    9],
          [  10,   11,   12,   13,   14],
          [  15,   16,   17,   18,   19]],

         [[   0,   -1,   -2,   -3,   -4],
          [  -5,   -6,   -7,   -8,   -9],
          [ -10,  -11,  -12,  -13,  -14],
          [ -15,  -16,  -17,  -18,  -19]]],


        [[[  20,   21,   22,   23,   24],
          [  25,   26,   27,   28,   29],
          [  30,   31,   32,   33,   34],
          [  35,   36,   37,   38,   39]],

         [[ -20,  -21,  -22,  -23,  -24],
          [ -25,  -26,  -27,  -28,  -29],
          [ -30,  -31,  -32,  -33,  -34],
          [ -35,  -36,  -37,  -38,  -39]]],


        [[[  40,   41,   42,   43,   44],
          [  45,   46,   47,   48,   49],
          [  50,   51,   52,   53,   54],
          [  55,   56,   57,   58,   59]],

         [[ -40,  -41,  -42,  -43,  -44],
          [ -45,  -46,  -47,  -48,  -49],
       

**case4:** (2,3,4,5) 를 (2,3,4,1,5) 로 해석 
- 최종차원은 (2,3,4, ,5) stack (2,3,4, ,5) = (2,3,2,2,5) // 4번째 축이 변하네요 // 끝에서 2번째 축이 변한다 

In [122]:
tf.stack([a,b],axis=-2) 

<tf.Tensor: shape=(2, 3, 4, 2, 5), dtype=int64, numpy=
array([[[[[   0,    1,    2,    3,    4],
          [   0,   -1,   -2,   -3,   -4]],

         [[   5,    6,    7,    8,    9],
          [  -5,   -6,   -7,   -8,   -9]],

         [[  10,   11,   12,   13,   14],
          [ -10,  -11,  -12,  -13,  -14]],

         [[  15,   16,   17,   18,   19],
          [ -15,  -16,  -17,  -18,  -19]]],


        [[[  20,   21,   22,   23,   24],
          [ -20,  -21,  -22,  -23,  -24]],

         [[  25,   26,   27,   28,   29],
          [ -25,  -26,  -27,  -28,  -29]],

         [[  30,   31,   32,   33,   34],
          [ -30,  -31,  -32,  -33,  -34]],

         [[  35,   36,   37,   38,   39],
          [ -35,  -36,  -37,  -38,  -39]]],


        [[[  40,   41,   42,   43,   44],
          [ -40,  -41,  -42,  -43,  -44]],

         [[  45,   46,   47,   48,   49],
          [ -45,  -46,  -47,  -48,  -49]],

         [[  50,   51,   52,   53,   54],
          [ -50,  -51,  -52,  -53,  -54

**case5:** (2,3,4,5) 를 (2,3,4,5,1) 로 해석 
- 최종차원은 (2,3,4,5, ) stack (2,3,4,5, ) = (2,3,4,5,2) // 5번째 축이 변하네요 // 마지막 축이 변한다 

In [123]:
tf.stack([a,b],axis=-1) 

<tf.Tensor: shape=(2, 3, 4, 5, 2), dtype=int64, numpy=
array([[[[[   0,    0],
          [   1,   -1],
          [   2,   -2],
          [   3,   -3],
          [   4,   -4]],

         [[   5,   -5],
          [   6,   -6],
          [   7,   -7],
          [   8,   -8],
          [   9,   -9]],

         [[  10,  -10],
          [  11,  -11],
          [  12,  -12],
          [  13,  -13],
          [  14,  -14]],

         [[  15,  -15],
          [  16,  -16],
          [  17,  -17],
          [  18,  -18],
          [  19,  -19]]],


        [[[  20,  -20],
          [  21,  -21],
          [  22,  -22],
          [  23,  -23],
          [  24,  -24]],

         [[  25,  -25],
          [  26,  -26],
          [  27,  -27],
          [  28,  -28],
          [  29,  -29]],

         [[  30,  -30],
          [  31,  -31],
          [  32,  -32],
          [  33,  -33],
          [  34,  -34]],

         [[  35,  -35],
          [  36,  -36],
          [  37,  -37],
          [  38, 

#### tf.einsum

### tnp

`-` tf.constant 는 솔직히 너무 쓰기 힘들다.

`-` 넘파이와 비교

(불만1)

In [124]:
tf.constant([1,2,3,4]).reshape(2,2)

AttributeError: 
        'EagerTensor' object has no attribute 'reshape'.
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()

In [125]:
np.array([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

(불만2)

In [126]:
tf.constant([1,2,3,4])+tf.constant([1.0,2.0,3.0,4.0])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

In [127]:
np.array([1,2,3,4])+ np.array([1.0,2.0,3.0,4.0])

array([2., 4., 6., 8.])

(불만3)

In [128]:
np.array([[1,2],[3,4]]).transpose()

array([[1, 3],
       [2, 4]])

In [129]:
np.array([[1,2],[3,4]]).T

array([[1, 3],
       [2, 4]])

In [130]:
np.transpose(np.array([[1,2],[3,4]]))

array([[1, 3],
       [2, 4]])

In [131]:
tf.constant([[1,2],[3,4]]).transpose()

AttributeError: 
        'EagerTensor' object has no attribute 'transpose'.
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()

In [132]:
tf.constant([[1,2],[3,4]]).T

AttributeError: 
        'EagerTensor' object has no attribute 'T'.
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()

In [133]:
tf.transpose(tf.constant([[1,2],[3,4]]))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

(불만4)

In [134]:
np.array([1,2,3,4]).max()

4

In [135]:
tf.reduce_max(tf.constant([1,2,3,4]))

<tf.Tensor: shape=(), dtype=int32, numpy=4>

... 저 이런거 하루 종일 생각해낼수도 있어요 

#### tnp 사용방법 (불만해결방법)

In [136]:
import tensorflow.experimental.numpy as tnp # 앞으로 텐서플로에서 np 대신에 tnp를 사용하면 넘파이에 익숙한 문법을 모두 쓸 수 있고 
tnp.experimental_enable_numpy_behavior()  # 생성된 tf.constant 자료형은 넘파이와 유사하게 동작한다. 

#### 선언, 선언고급

In [138]:
tnp.array([1,2,3,4])

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [139]:
tnp.diag([1,2,3])

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])>

#### 타입

In [140]:
type(tnp.array([1,2,3]))

tensorflow.python.framework.ops.EagerTensor

#### tf.contant로 만들어도 마치 넘파이인듯 쓰는 기능들

In [145]:
tf.constant([1,2,3,4]).reshape(2,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [146]:
tf.constant([1,2,3,4]).reshape(2,2).transpose()

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [147]:
tf.constant([1,2,3,4]).reshape(2,2).T

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [148]:
tf.constant([1,2,3,4]).reshape(2,2).T.max()

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [149]:
tf.constant([1,2,3,4])+tf.constant([1.0,2.0,3.0,4.0]) # 이건 감동임

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([2., 4., 6., 8.])>

#### 그렇지만 np.array는 아님 

In [152]:
a=tnp.array([1,2,3])
a

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [154]:
a[0]

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [155]:
a[0]=22

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

### tf.Variable

#### 선언 

`-` tf.Variable()로 선언

In [156]:
tf.Variable([1,2,3,4])

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

`-` tf.constant() 선언후 변환 

In [157]:
a=tf.constant([1,2,3,4])
a=tf.Variable(a) 
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

#### 타입

In [158]:
type(tf.Variable(1))

tensorflow.python.ops.resource_variable_ops.ResourceVariable

#### 인덱싱 

In [159]:
a=tf.Variable([1,2,3,4])
a[:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

#### tf.Variable $\to$ 넘파이 

In [160]:
tf.Variable([1,2,3,4]).numpy()

array([1, 2, 3, 4], dtype=int32)

#### tf.Variable 도 불편하다. 

In [161]:
tf.Variable([1,2,3])+tf.Variable([1.0,2.0,3.0]) # 이거 원래 실행못함. 그런데 여기서 실행되는 이유는 tnp덕임

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 6.])>

#### 연산 

In [162]:
tf.Variable([1,2,3])+tf.Variable([1,2,3]) # 연산가능

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [164]:
_tmp = tf.Variable([1,2,3])+tf.Variable([1,2,3]) 
type(_tmp) #그런데 연산결과는 tf.constant 이다? 

tensorflow.python.framework.ops.EagerTensor

#### 형태변환 

In [165]:
_tmp = tf.reshape(tf.Variable([1,2,3,4]),[2,2])
_tmp

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [166]:
type(_tmp) # 또 연산결과는 tf.constant가 되었음 

tensorflow.python.framework.ops.EagerTensor

#### 선언고급 

In [167]:
a=tf.Variable(np.diag([1,2,3]))
a

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int64, numpy=
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])>

#### tf.concat 

In [168]:
a=tf.Variable([1,2])
b=tf.Variable([3,4])
c=tf.concat([a,b],axis=0)
c

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

#### tf.stack

In [169]:
a=tf.Variable([1,2])
b=tf.Variable([3,4])
c=tf.stack([a,b],axis=0)
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [170]:
a=tf.Variable([1,2,3,4])

#### 심지어 tf.Variable()로 만들어진 오브젝트는 tnp의 효과(은총)도 받지 못함

In [171]:
tf.Variable([1,2,3,4]).reshape(2,2)

AttributeError: 'ResourceVariable' object has no attribute 'reshape'