# (노트) 판다스 인덱싱, pandas indexing

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [시각화2022]

## imports

In [11]:
import pandas as pd
import numpy as np
import rpy2 
%load_ext rpy2.ipython

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


## df 인덱싱공부 1단계: 인덱싱의 4가지 컨셉

### 데이터프레임 준비

`-` 데이터준비

In [12]:
np.random.seed(43052)
att = np.random.choice(np.arange(10,21)*5,200)
rep = np.random.choice(np.arange(5,21)*5,200)
mid = np.random.choice(np.arange(0,21)*5,200)
fin = np.random.choice(np.arange(0,21)*5,200)
dct = {'att':att,'rep':rep,'mid':mid,'fin':fin}
df = pd.DataFrame(dct)
df

,att,rep,mid,fin
0,65,45,0,10
1,95,30,60,10
2,65,85,15,20
3,55,35,35,5
4,80,60,55,70
...,...,...,...,...
195,55,70,40,95
196,65,85,25,85
197,85,85,100,10
198,80,65,35,60


`-` 앞으로 df는 이러한 형태를 가정한다. 즉 column이름은 문자열, row이름은 0부터 시작하는 정수 

`-` 아래와 같은 형태는 일단 생각하지 말자.

In [13]:
_df = pd.DataFrame({'att':[60,65,80,90],'rep':[50,100,90,100]},index=['규빈','영미','성준','혜미'])
_df

,att,rep
규빈,60,50
영미,65,100
성준,80,90
혜미,90,100


### df의 4가지 컨셉

`-` 원소에 접근하는 4가지(6가지?) 방법: `.`, `[]`, `.iloc[]`, `.loc[]` (+ `.iloc[,]`, `loc[,]`)

### 컨셉1: 클래스 느낌 

`-` 컨셉1: df는 인스턴스이다. 그리고 df.att, df.rep, df.mid, df.fin 이라는 속성이 있다. 

`-` 예시1

In [14]:
df.att # df.rep, df.mid, df.fin

0      65
1      95
2      65
3      55
4      80
       ..
195    55
196    65
197    85
198    80
199    50
Name: att, Length: 200, dtype: int64

`-` 언제유용? columns의 이름을 대충 알고 있을 경우 자동완성 이용가능 

### 컨셉2: 딕셔너리 + $\alpha$ 느낌 

`-` 컨셉2: df는 컬럼이름이 key, 컬럼데이터가 value인 dictionary (즉 df는 dct $+\alpha$ 로 이해해도 무방)

`-` 예시1: dct가 가능하면 df도 가능하다. 

In [15]:
dct['att'], df['att'] # dct가 되는 것이면 df도 된다

(array([ 65,  95,  65,  55,  80,  75,  65,  60,  95,  90,  55,  95,  95,
         50,  50,  95,  50,  65,  70,  90,  80,  55,  65,  70,  85,  90,
        100,  80,  80,  55,  75,  80,  95,  95, 100, 100,  80,  70,  85,
        100,  95,  75,  70,  50, 100,  75,  85,  80,  95,  65,  90,  65,
         80,  95,  65,  90,  95, 100,  50,  90,  50,  80,  50,  70,  65,
         60,  50,  60,  70,  75,  50,  85,  80,  55,  85,  65,  85,  60,
         95,  85,  60, 100, 100,  55,  70,  70,  55, 100,  85, 100,  60,
         65,  65,  75,  50,  75, 100,  90,  55,  75,  60,  85,  60,  70,
         80,  65,  85, 100,  65,  85,  85,  85, 100,  95,  95,  55,  85,
         75,  95,  85,  95, 100,  95,  95, 100,  55,  60,  85,  75,  55,
         70,  80,  90,  90,  60,  90,  75,  60,  55,  70,  75,  90,  50,
         55,  90,  75,  90,  85, 100,  55,  70,  90,  55, 100,  50, 100,
         70,  85,  55,  75,  65,  70,  60, 100,  75,  90,  95,  90,  95,
         55,  95,  65,  65,  90, 100,  70, 100,  50

`-` 예시2: dct가 가능하면 df도 가능하다(2)

In [16]:
dct.get('att'), df.get('att')

(array([ 65,  95,  65,  55,  80,  75,  65,  60,  95,  90,  55,  95,  95,
         50,  50,  95,  50,  65,  70,  90,  80,  55,  65,  70,  85,  90,
        100,  80,  80,  55,  75,  80,  95,  95, 100, 100,  80,  70,  85,
        100,  95,  75,  70,  50, 100,  75,  85,  80,  95,  65,  90,  65,
         80,  95,  65,  90,  95, 100,  50,  90,  50,  80,  50,  70,  65,
         60,  50,  60,  70,  75,  50,  85,  80,  55,  85,  65,  85,  60,
         95,  85,  60, 100, 100,  55,  70,  70,  55, 100,  85, 100,  60,
         65,  65,  75,  50,  75, 100,  90,  55,  75,  60,  85,  60,  70,
         80,  65,  85, 100,  65,  85,  85,  85, 100,  95,  95,  55,  85,
         75,  95,  85,  95, 100,  95,  95, 100,  55,  60,  85,  75,  55,
         70,  80,  90,  90,  60,  90,  75,  60,  55,  70,  75,  90,  50,
         55,  90,  75,  90,  85, 100,  55,  70,  90,  55, 100,  50, 100,
         70,  85,  55,  75,  65,  70,  60, 100,  75,  90,  95,  90,  95,
         55,  95,  65,  65,  90, 100,  70, 100,  50

`-` 예시3: dct에서 불가능하지만 df에서 가능한것도 있다 

In [17]:
dct.get(['att','rep'])

TypeError: unhashable type: 'list'

In [18]:
df.get(['att','rep'])

,att,rep
0,65,45
1,95,30
2,65,85
3,55,35
4,80,60
...,...,...
195,55,70
196,65,85
197,85,85
198,80,65


`-` 예시4: dct에서 불가능하지만 df에서 가능한 것도 있다(2)

In [19]:
dct[['att','rep']]

TypeError: unhashable type: 'list'

In [20]:
df[['att','rep']]

,att,rep
0,65,45
1,95,30
2,65,85
3,55,35
4,80,60
...,...,...
195,55,70
196,65,85
197,85,85
198,80,65


`-` 예시5: 생각해보니까 컬럼이름은 이런식으로 파악할 수 있겠네? 

In [21]:
dct.keys(), df.keys()

(dict_keys(['att', 'rep', 'mid', 'fin']),
 Index(['att', 'rep', 'mid', 'fin'], dtype='object'))

### 컨셉3: 넘파이느낌 

`-` 컨셉3: `df.iloc`은 넘파이 어레이처럼 생각가능하다. 

`-` 컨셉1,2로는 column인덱싱만 가능했는데 컨셉3은 row인덱싱도 가능하다. 

#### `#` row indexing

In [22]:
arr = np.stack([att,rep,mid,fin],axis=1)

`-` 예시1: 단일레이블 

In [23]:
arr[0,:] # first row 
arr[0,]
arr[0]

array([65, 45,  0, 10])

In [24]:
df.iloc[0,:] # first row 
df.iloc[0,]
df.iloc[0]

att    65
rep    45
mid     0
fin    10
Name: 0, dtype: int64

`-` 예시2: 레이블의 리스트 

In [25]:
arr[[0,1,2],:] 
arr[[0,1,2],]
arr[[0,1,2]]

array([[65, 45,  0, 10],
       [95, 30, 60, 10],
       [65, 85, 15, 20]])

In [26]:
df.iloc[[0,1,2],:]
df.iloc[[0,1,2],]
df.iloc[[0,1,2]]

,att,rep,mid,fin
0,65,45,0,10
1,95,30,60,10
2,65,85,15,20


`-` 예시3: 슬라이싱 (끝점포함X) 

In [27]:
arr[0:3,:] # 끝점포함X
arr[0:3,]
arr[0:3]

array([[65, 45,  0, 10],
       [95, 30, 60, 10],
       [65, 85, 15, 20]])

In [28]:
df.iloc[0:3,:]
df.iloc[0:3,]
df.iloc[0:3]

,att,rep,mid,fin
0,65,45,0,10
1,95,30,60,10
2,65,85,15,20


#### `#` col indexing

`-` 예시1: 단일레이블 

In [29]:
df.iloc[:,0] # df.iloc[,0] 혹은 df.iloc[0] 불가..
# arr[:,0] 

0      65
1      95
2      65
3      55
4      80
       ..
195    55
196    65
197    85
198    80
199    50
Name: att, Length: 200, dtype: int64

`-` 예시2: 레이블의 리스트 

In [30]:
df.iloc[:,[0,2]] # df.iloc[,[0,1]] 혹은 df.iloc[[0,1]] 불가.. 
#arr[:,[0,2]]

,att,mid
0,65,0
1,95,60
2,65,15
3,55,35
4,80,55
...,...,...
195,55,40
196,65,25
197,85,100
198,80,35


`-` 예시3: 슬라이싱 (끝점포함X) 

In [31]:
df.iloc[:,0:2] # df.iloc[,0:2] 혹은 df.iloc[[0:2]] 불가..
# arr[:,0:2]

,att,rep
0,65,45
1,95,30
2,65,85
3,55,35
4,80,60
...,...,...
195,55,70
196,65,85
197,85,85
198,80,65


#### `#` row + col indexing 

`-` 예시1

In [32]:
df.iloc[0:2,[0,2]]
#arr[0:2,[0,2]]

,att,mid
0,65,0
1,95,60


### 컨셉4: 데이터프레임느낌 

`-` 컨셉4: 새로운느낌.. (R에 익숙하면 dataframe 혹은 티블느낌이라고 보면 됩니다)

In [35]:
%%R 
#library(tidyverse)
mpg[1:5,c('model','year')]

# A tibble: 5 × 2
  model  year
  <chr> <int>
1 a4     1999
2 a4     1999
3 a4     2008
4 a4     2008
5 a4     1999


#### `#` row indexing 

`-` 예시1: 단일레이블 

In [36]:
df.loc[0,:]
#df.loc[0,]
#df.loc[0]

att    65
rep    45
mid     0
fin    10
Name: 0, dtype: int64

`-` 예시2: 레이블의 리스트

In [37]:
df.loc[[0,1],:]
#df.loc[[0,1],]
#df.loc[[0,1]]

,att,rep,mid,fin
0,65,45,0,10
1,95,30,60,10


`-` 예시3: 슬라이싱 (끝점포함O)

In [38]:
df.loc[0:2,:] # 이 슬라이싱은 끝점을 포함한다!!
#df.loc[0:2,]
#df.loc[0:2]

,att,rep,mid,fin
0,65,45,0,10
1,95,30,60,10
2,65,85,15,20


#### `#` col indexing

`-` 예시1: 단일레이블 

In [39]:
df.loc[:,'att'] # 문자열 

0      65
1      95
2      65
3      55
4      80
       ..
195    55
196    65
197    85
198    80
199    50
Name: att, Length: 200, dtype: int64

`-` 예시2: 레이블의 리스트

In [40]:
df.loc[:,['att','mid']] # 문자열의 리스트 

,att,mid
0,65,0
1,95,60
2,65,15
3,55,35
4,80,55
...,...,...
195,55,40
196,65,25
197,85,100
198,80,35


`-` 예시3: 슬라이싱 (끝점포함O)

In [41]:
df.loc[:,'att':'mid'] # 문자열의 슬라이싱?.. 이게 뭐야??

,att,rep,mid
0,65,45,0
1,95,30,60
2,65,85,15
3,55,35,35
4,80,60,55
...,...,...,...
195,55,70,40
196,65,85,25
197,85,85,100
198,80,65,35


#### `#` row + col indexing 

`-` 예시1

In [42]:
df.loc[3:5,'att':'mid']

,att,rep,mid
3,55,35,35
4,80,60,55
5,75,40,75


### 컨셉1~4 정리 

`-` 표를 만들어 볼까..?

||`.`| `[]` | `.iloc` | `.loc`| 
|:-:|:-:|:-:|:-:|:-:|
|col선택가능?|O|O|O|O|
|row선택가능?|X|X|O|O|
|리턴값|ser|ser or df | ser or df | ser or df|
|단일레이블 입력가능?|O|O|O|O|
|레이블리스트 입력가능?|X|O|O|O|
|슬라이싱 입력가능?|X|X|O|O|

`-` col 이름을 알아야하는 경우 
- `.` : 앞글자만 대충 알아도 자동완성 가능 
- `[]`: 정확한 col 이름을 알아야 함
- `.loc`: 보통 정확한 col 이름을 알아야 하지만 슬라이싱 이용시 양 끝의 컬럼이름만 알면 무방 
- `.iloc`: 정확한 col 이름을 몰라도 번호로 인덱싱 가능

## df 인덱싱공부 2단계

### 정수가 아닌 row인덱스

### pd.Series 활용

In [43]:
ser = pd.Series(np.linspace(0,1,10))
ser

0    0.000000
1    0.111111
2    0.222222
3    0.333333
4    0.444444
5    0.555556
6    0.666667
7    0.777778
8    0.888889
9    1.000000
dtype: float64

In [44]:
ser[[0,2]]

0    0.000000
2    0.222222
dtype: float64

### 컬럼이름 바꾸고 싶을 경우

In [45]:
lambda s: s.replace('.','_').replace(' ','_')

<function __main__.<lambda>(s)>

In [46]:
df.columns = map(lambda s: s.replace('.','_').replace(' ','_'), df.columns)

In [47]:
df

,att,rep,mid,fin
0,65,45,0,10
1,95,30,60,10
2,65,85,15,20
3,55,35,35,5
4,80,60,55,70
...,...,...,...,...
195,55,70,40,95
196,65,85,25,85
197,85,85,100,10
198,80,65,35,60


## df 인덱싱공부 3단계

### bool indexing

### map을 활용한 indexing

### lambda를 활용한 indexing