# (노트) 파이썬 자료형

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- categories: [파이썬]

### 자료형의 구분 

`-` 차원에 따른 분류: 0차원 자료형, 1차원 자료형, 2차원 자료형 
- 명확한건 아님 

`-` 내장자료형, 특정패키지에서 지원하는 자료형 

### 0차원 자료형의 소개

`-` 하나의 값을 저장할 수 있는 자료형. 


`-` int, float, bool이 있음 

In [1]:
a=100

In [2]:
type(a)

int

In [3]:
a=1.2*3
a

3.5999999999999996

In [4]:
type(a)

float

In [5]:
a=True ## a=1로 생각해도 .. 
b=False ## b=0으로 생각해도 .. 

In [6]:
type(a)

bool

`-` 저거 3개만 있는건 아님 

In [7]:
a=1+2j
b=2-2j
c=a+b

In [8]:
type(c)

complex

- 잘 쓰지 않음 

### 0차원 자료형의 변환 

`-` float $\to$ int 

In [9]:
a=3.6234

In [10]:
b=int(a)

In [11]:
b

3

`-` int $\to$ float 

In [12]:
a=3

In [13]:
a

3

In [14]:
float(a)

3.0

`-` bool $\to$ int, bool $\to$ float (이게 가능하지 않을것 같지만 사실 가능함) 

In [15]:
int(True)

1

In [16]:
float(False)

0.0

`-` bool $\to$ int 혹은 bool $\to$ float이 가능한 이유는 대부분 프로그램언어에서 True는 1로, False는 0으로 생각하기 때문 

In [17]:
True+1

2

In [18]:
False * 3.14

0.0

`-` "이런건 변환 못하겠지?" 싶은것도 바꿔줌. 

In [19]:
bool(-3.14)

True

- 이런걸 쓸 일이 있을까?? 

`-` 변환이 항상 성공하는 것은 아님 (규칙은 잘 모르겠음) 

In [20]:
float(3+0j)

TypeError: can't convert complex to float

`-` 묵시적 형변환 (약간 눈치주는 느낌) 
- explicit: 온풍기좀 키자.. 
- implicit: 좀 춥지 않아? (온풍기좀 틀자는 이야기) 

In [21]:
True*1

1

- 1을 곱해야하는데.. 너 계속 bool형태로 있을거야? 

In [22]:
1*1.0

1.0

- 1.0을 곱해야하는데.. 너 계속 int형으로 있을거야? 

### 1차원 자료형의 소개

`-` 기본적인 1차원 자료형은 리스트와 튜플이 있다. 

In [85]:
a=[1,2,3] ## 리스트 
a

[1, 2, 3]

In [86]:
b=(1,2,3) ## 튜플
b

(1, 2, 3)

`-` 리스트와 튜플 모두 원소로 접근하기 위해서는 `[]`를 사용한다. (R과 동일) 

In [87]:
a[0]

1

In [88]:
a[1]

2

In [89]:
a[2]

3

In [90]:
b[0]

1

In [91]:
b[1]

2

In [92]:
b[2]

3

`-` 리스트는 원소의 값을 바꿀 수 있지만 튜플은 바꿀 수 없다. 

In [69]:
a

[1, 2, 3]

In [70]:
a[0]=100

In [74]:
a

[100, 2, 3]

In [75]:
b

(1, 2, 3)

In [76]:
b[0]=100

TypeError: 'tuple' object does not support item assignment

`-` 문자열도 1차원자료형으로 생각한다. (조금 의외임) 

In [93]:
a='guebin'

In [94]:
a[0]

'g'

In [95]:
a[1]

'u'

`-` 그밖에 집합, 딕셔너리와 같은 1차원 자료형도 있다. (우리는 다루지 않을 것임) 

In [111]:
s={1,2,3,4}

In [112]:
s

{1, 2, 3, 4}

In [113]:
d={'a':123,'b':234,'c':233}

In [114]:
d

{'a': 123, 'b': 234, 'c': 233}

### 리스트공부 1단계 

`-` 리스트의 선언 

In [121]:
a=[1,2,3] 
a

[1, 2, 3]

In [122]:
type(a)

list

`-` 비어있는 리스트를 만들려면? 

In [152]:
a=list() ## 방법1
a

[]

In [153]:
a=[] ## 방법2
a

[]

`-` 리스트에서 `+`의 의미

In [155]:
a=[1,2,3]
b=[4,5,6] 
a+b 

[1, 2, 3, 4, 5, 6]

- 충격.. 리스트에서 + 기호를 쓰면 우리가 상식적으로 생각하는 벡터연산이 수행되지 않음.

In [250]:
[1,2,3]+[4,5]

[1, 2, 3, 4, 5]

`-` 리스트에서 `*`의 의미

In [251]:
a=[1,2,3]
a+a

[1, 2, 3, 1, 2, 3]

In [253]:
a*2 # a+a = a*2 

[1, 2, 3, 1, 2, 3]

In [255]:
[1]*10

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

`-` 예제: 빈리스트를 만들고 [1], [2], [3] 을 각각 더하여 원소를 추가해보자. 

In [261]:
a=[]
a

[]

In [262]:
a=a+[1]
a

[1]

In [263]:
a=a+[2]
a

[1, 2]

In [264]:
a=a+[3]
a

[1, 2, 3]

### 리스트공부 2단계 

`-` 리스트에서 원소를 추가하는 또 다른 방법 

In [270]:
a=[]
a

[]

In [271]:
a.append(1)
a

[1]

In [272]:
a.append(2)
a

[1, 2]

In [273]:
a.append(3)
a

[1, 2, 3]

`-` `a.append(1)` 라는 문법은 너무 낯설다 $\to$ 당연해요.. 

- 파이썬 특징: 모든 변수명 뒤에 .을 붙이면 그 변수에 특화된 새로운 기능을 쓸 수 있다. (파이썬에서 변수는 단순히 정보가 담긴 그릇을 의미하는것이 아니다, 기능이 있다) 
- 장점: 초보자라도 눈치껏 문법을 배우기 편하다. 
- 단점: 처음에 너무 이해하기 난해함. 

`-` 마음의 눈 
- `a.f() := f(a)` 로 생각하면 편리함 
- `a.f(2) := f(a,2)`로 생각하면 편리함 
- 이러한 점에서 R의 `%>%` 연산자와 유사하다고 생각할 수 있음. (약간 다르긴해요) 

`-` 리스트 특화기능(=특화함수=메소드)

(append)

In [187]:
a.append?

Signature: a.append(object, /)
Docstring: Append object to the end of the list.
Type:      builtin_function_or_method


In [188]:
a=[1,2,3]
a.append(4)
a

[1, 2, 3, 4]

(clear)

In [189]:
a.clear?

Signature: a.clear()
Docstring: Remove all items from list.
Type:      builtin_function_or_method


In [190]:
a=[1,2,3]
a.clear()
a

[]

(copy)

In [168]:
a.copy?

Signature: a.copy()
Docstring: Return a shallow copy of the list.
Type:      builtin_function_or_method


In [191]:
a=[1,2,3]
b=a.copy()
b

[1, 2, 3]

(count)

In [169]:
a.count?

Signature: a.count(value, /)
Docstring: Return number of occurrences of value.
Type:      builtin_function_or_method


In [201]:
a=[1,2,3,3,4,4]
a.count(5)

0

(extend)

In [170]:
a.extend?

Signature: a.extend(iterable, /)
Docstring: Extend list by appending elements from the iterable.
Type:      builtin_function_or_method


In [209]:
a=[1,2,3]
b=[1,2,3,4]
a.extend(b)
a

[1, 2, 3, 1, 2, 3, 4]

(index)

In [171]:
a.index?

Signature: a.index(value, start=0, stop=9223372036854775807, /)
Docstring:
Return first index of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method


In [213]:
a=[1,2,3,3,4,4,5,5,5,6]
a.index(3)

2

(insert)

In [173]:
a.insert?

Signature: a.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method


In [217]:
a=[1,2,3]
a.insert(0,88)
a

[88, 1, 2, 3]

(pop)

In [174]:
a.pop?

Signature: a.pop(index=-1, /)
Docstring:
Remove and return item at index (default last).

Raises IndexError if list is empty or index is out of range.
Type:      builtin_function_or_method


In [219]:
a=[1,2,3,4]
a.pop()

4

In [220]:
a

[1, 2, 3]

In [222]:
a.pop()

3

In [223]:
a

[1, 2]

In [224]:
a.pop(0)

1

In [225]:
a

[2]

(remove)

In [227]:
a.remove?

Signature: a.remove(value, /)
Docstring:
Remove first occurrence of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method


In [232]:
a=[1,2,2,3]
a.remove(2)

In [233]:
a

[1, 2, 3]

In [234]:
a.remove(2)

In [235]:
a

[1, 3]

(reverse)

In [176]:
a.reverse?

Signature: a.reverse()
Docstring: Reverse *IN PLACE*.
Type:      builtin_function_or_method


In [237]:
a=[1,2,3,4]
a.reverse()
a

[4, 3, 2, 1]

(sort)

In [241]:
a.sort?

Signature: a.sort(*, key=None, reverse=False)
Docstring:
Sort the list in ascending order and return None.

The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
order of two equal elements is maintained).

If a key function is given, apply it once to each list item and sort them,
ascending or descending, according to their function values.

The reverse flag can be set to sort in descending order.
Type:      builtin_function_or_method


In [242]:
a=[1,3,2,4]
a.sort()
a

[1, 2, 3, 4]

In [244]:
a=[1,3,2,4]
a.sort(reverse=True)
a

[4, 3, 2, 1]

### 리스트공부 3단계 

#### 리스트의 뺄셈과 나눗셈 

`-` 리스트의 뺄셈: 이런건 없다 

In [1]:
a=[1,2,3,4]
a-[1]

TypeError: unsupported operand type(s) for -: 'list' and 'list'

`-` 리스트의 나눗셈: 이런건 없다. 

In [2]:
a=[1,2,3,1,2,3]
a/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

#### a.append(4) vs a+[4] 의 차이점? 

`-` a+[4]: a는 변화하지 않음 

In [4]:
a=[1,2,3] 
a+[4]

[1, 2, 3, 4]

In [5]:
a

[1, 2, 3]

`-` a.append(4): a자체가 변화함 

In [6]:
a=[1,2,3]
a.append(4)
a

[1, 2, 3, 4]

`-` 보통 메소드를 이용하면 오브젝트 `a`자체가 변화할때가 많다. 

In [7]:
a=[1,2,3]
a.reverse()
a

[3, 2, 1]

`-` 그런데 모든 메소드가 a를 변화시키는 것은 아니다. (명확한 기준은 없지만 의미상 왠지 a를 변화시킬 필요가 없을것 같은게 있어요..) 

In [10]:
a=[1,2,2,3,4]
a.count(2)

2

In [11]:
a

[1, 2, 2, 3, 4]

- 숫자세는 함수를 적용하는데 굳이 a를 바꿀필요가? 

#### len은 list에서 원소의 숫자를 리턴한다. 

In [17]:
a=[1,2,3]
len(a)

3

In [20]:
a=[]
len(a)

0

In [21]:
a=[3]
len(a)

1

`-` 아래는 동작하지 않음

In [22]:
a=[1,2,3]
a.len()

AttributeError: 'list' object has no attribute 'len'

#### [3]과 3은 다르다. 

`-` 다른점1: [3]은 1차원, 3은 0차원 자료형. 

In [23]:
a=[3]
len(a)

1

In [24]:
a=3
len(a)

TypeError: object of type 'int' has no len()

`-` 다른점2: `+` 연산 적용시 차이점

In [28]:
a=[3]
a+[4] # [3], [4] 모두 리스트형

[3, 4]

In [29]:
a=[3]
a+4 # [3]은 리스트이지만 4는 리스트가 아니야 

TypeError: can only concatenate list (not "int") to list

In [31]:
a=3 
a+4 # 3,4 모두 인트형 

7

In [32]:
a=3
a+[4] # 3은 인트형인데 [4]는 리스트 

TypeError: unsupported operand type(s) for +: 'int' and 'list'

`-` 다른것도 다른게 많음.. 그냥 [3]이랑 3은 아예 다른거에요.. 

#### 리스트의 원소는 어떠한 형태도 가능하다. 

`-` 예제1

In [12]:
a=[True, 3, 3.14] 
a

[True, 3, 3.14]

In [13]:
type(a[0])

bool

In [14]:
type(a[1])

int

In [15]:
type(a[2])

float

**예제1에 대한 discussion**
- 리스트에 포함된 3개의 원소가 각각 모두 다른 자료형을 가지고 있다. 
- 강제형변환이 되지 않음. (Python의 list는 R의 벡터와 약간 다른느낌, 오히려 R의 list와 가까움) 

`-` 예제2 

In [33]:
a=[[True,3,3.14],True,[3],3,]
a

[[True, 3, 3.14], True, [3], 3]

**예제2에 대한 discussion** 
- 첫번째 원소는 리스트 (1차원)
- 두번째 원소는 bool (0차원)
- 세번째 원소는 길이가 1인 리스트 (1차원) 
- 네번째 원소느 int (0차원) 

#### 중첩리스트

`-` 리스트는 1차원 자료형이다. 그런데 2차원 자료형처럼 쓸 수 있는 트릭이 있다. 

In [35]:
A=[[1,2,3],[4,5,6],[7,8,9]]
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

`-` 위와 같이 하면 A는 거의 아래와 같은 매트릭스처럼 생각하고 원소를 뽑을 수 있다. 

$$ {\bf A}=\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$$

`-` ${\bf A}$에서 (1,1)의 원소를 뽑자 $\to$ 1을 뽑자는 의미. 

In [37]:
A[0,0] ## 파이썬의 인덱스가 0부터 시작하니까 (1,1)에 대응하는 인덱스는 (0,0)

TypeError: list indices must be integers or slices, not tuple

- 실패: 이런문법은 배운적이 없어요 

In [38]:
A[0][0]

1

- 이건 성공함: 이것도 배운적 없는 문법인것 같은데? 

`-` 성공의 이유분석? 

In [45]:
A # A는 [1,2,3], [4,5,6], [7,8,9] 3개의 리스트를 원소로 가짐 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [46]:
A[0] # 첫번쨰 원소인 [1,2,3]이 나옴

[1, 2, 3]

In [47]:
A[0][0] # A[0]의 첫번째 원소인 1이 나옴 

1

- 배운적은 없지만 배운걸 응용해서 코드를 차근차근 뜯어보면 알 수는 있음.

`-` ${\bf A}$에서 (2,3)위치의 원소를 뽑자 $\to$ 파이썬에서는 (1,2)인덱스임

$$ {\bf A}=\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$$

In [49]:
A[1][2]

6

`-` 매트릭스는 아니지만 매트릭스 같아!

> 1차원 배열을 다차원 배열로 확장할 수 있는 아이디어 제공

### 튜플공부 1단계 

`-` 튜플은 ()로 선언한다. 

In [124]:
a=(1,2,3)
a

(1, 2, 3)

In [125]:
type(a)

tuple

`-` +로 튜플과 튜플을 합칠 수 있다. 

In [126]:
a=(1,2,3)
b=(4,5)
a+b

(1, 2, 3, 4, 5)

`-` 비어잇는 튜플을 선언하려면 아래와 같이한다. 

In [128]:
a=tuple()
a

()

In [130]:
a=()
a

()

`-` 원소가 하나인 튜플을 선언하기 위해서는 아래와 같이 한다. 

In [131]:
a=(1,)
a

(1,)

`-` 왜 (1)와 같이 하면 안될까? 

In [136]:
(1)+(2) ## 이거 모호해요, 인트형에 소괄호 친것인지? 튜플을 의도한 것인지 

3

In [134]:
(1,)+(2,)

(1, 2)

`-` 튜플도 리스트와 비슷한 방식으로 원소를 뽑는다. 

In [138]:
a=(1,2,3)
a

(1, 2, 3)

In [139]:
a[0]

1

`-` 그런데 튜플은 원소의 내용을 바꿀 수 없다. 

In [140]:
a[0]=2

TypeError: 'tuple' object does not support item assignment

`-` 예제: 빈튜플을 만들고 (1,), (2,), (3,) 을 각각 더하여 원소를 추가해보자.

In [147]:
a=()
a

()

In [148]:
a=a+(1,)+(2,)+(3,)
a

(1, 2, 3)

### 튜플공부 2단계 

### string 

### 1차원자료형의 변환 

### numpy의 소개

#### 파이썬은 그렇게 좋은 계산기가 아니다. 

`-` 놀라운점1: pi가 없다. 

In [23]:
pi

NameError: name 'pi' is not defined

`-` 놀라운점2: sqrt가 없다.. 

In [24]:
sqrt(2)

NameError: name 'sqrt' is not defined

`-` 사칙연산 빼고 되는게 없는것 같은데? 

In [25]:
log(10)

NameError: name 'log' is not defined

In [26]:
exp(1)

NameError: name 'exp' is not defined

In [27]:
sin(0)

NameError: name 'sin' is not defined

`-` R과 비교하면 진짜 너무 서운함 

#### numpy를 쓰면 파이썬은 좋은 계산기가 된다. 

`-` numpy: python을 좋은 계산기로 만드는 라이브러리
- R의 tidyverse처럼 python에서 여러가지 library가 있는데 그중에서 python에 강력한 계산기능을 부여하는 패키지중 하나가 바로 numpy이다. 
- 사용법: `library(tidyverse)`하는 것처럼 `import numpy` 하면 된다. 그 뒤에 `numpy.`을 앞에 붙이고 기능을 쓰면 된다. 

In [52]:
import numpy 

In [53]:
numpy.sqrt(2) # sqrt함수를 쓸것인데, 그 함수는 우리가 임포트한 numpy에 있음. 

1.4142135623730951

In [54]:
numpy.exp(1) # exp함수를 쓸것인데, 그 함수는 우리가 임포트한 numpy에 있음. 

2.718281828459045

In [55]:
numpy.log(2.718281828459045) # log함수를 쓸것인데, 그 함수는 우리가 임포트한 numpy에 있음. 

1.0

In [56]:
numpy.sin(0) # sin함수를 쓸것인데, 그 함수는 우리가 임포트한 numpy에 있음. 

0.0

`-` 진짜 너무 불편한데? $\to$ 보통은 아래와 같이 많이 쓴다. 

In [57]:
import numpy as np # numpy를 np라는 약어로 부른다는 뜻. 

In [58]:
np.sqrt(2)

1.4142135623730951

In [59]:
np.exp(1)

2.718281828459045

In [60]:
np.log(2.718281828459045)

1.0

### numpy 공부: 1단계 

`-` numpy.ndarray 자료형을 만드는 방법 

In [72]:
a=[1,2,3]
b=np.array(a) 
b

array([1, 2, 3])

`-` 이게 왜 좋은가? 

In [76]:
a+1 ## 리스트는 [1,2,3] + 1 을 수행할 수 없지만 

TypeError: can only concatenate list (not "int") to list

In [77]:
b+1 ## np.ndarray는 할 수 있다. 

array([2, 3, 4])

`-` 막강한 계산기능: 이정도면 거의 R

In [79]:
np.sqrt(b)

array([1.        , 1.41421356, 1.73205081])

In [80]:
np.log(b)

array([0.        , 0.69314718, 1.09861229])

In [81]:
np.sin(b)

array([0.84147098, 0.90929743, 0.14112001])

In [82]:
np.exp(b)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [84]:
(b+1)*2/3

array([1.33333333, 2.        , 2.66666667])