# (노트) 파이썬 자료형 (1) 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [파이썬]

### 파이썬 교재

`-` 전자교재

- https://docs.python.org/3.9/tutorial/index.html
- https://wikidocs.net/book/1
- https://jakevdp.github.io/PythonDataScienceHandbook/

`-` 종이책
- 효율적 개발로 이끄는 파이썬 실천 기술
- Learning python: powerful object-oriented programming

### 주피터노트북, 주피터랩

`-` interactive notebook이 아니다. 

In [1]:
a=1 # line1 
a

1

In [2]:
b=3 # line2 
b

3

In [3]:
a+b # line3

4

`-` 계산결과를 바로 출력해준다. (그런데 마지막만 출력해준다) 

In [146]:
a=1
a # 이게 사실 a를 출력하라는 의미는 아님
b=3
b # 
a+b

4

`-` 주피터랩: 주피터노트북의 확장버전 
- 저는 주피터랩을 더 선호하긴합니다.
- 가끔 주피터노트북을 쓸 때도 있음.
- Colab도 좋아요. 

`-` 마크다운모드, 코드모드

### 자료형 

`-` 파이썬 기본자료형은 int, float, bool, list, tuple, dict, set 등이 있다. 

- 0차원 자료형: int, float, bool 
- 1차원 자료형: list, tuple, dict, set 

### int, float, bool 

`-` `int`형 

In [4]:
a=100

In [5]:
type(a)

int

In [6]:
a?

Type:        int
String form: 100
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4


`-` `float`형

In [7]:
a=1.2*3
a

3.5999999999999996

In [8]:
type(a)

float

In [9]:
a?

Type:        float
String form: 3.5999999999999996
Docstring:   Convert a string or number to a floating point number, if possible.


`-` `bool`형 

In [10]:
a=True ## a=1로 생각해도 .. 
b=False ## b=0으로 생각해도 .. 

In [11]:
type(a)

bool

In [12]:
a?

Type:        bool
String form: True
Docstring:  
bool(x) -> bool

Returns True when the argument x is true, False otherwise.
The builtins True and False are the only two instances of the class bool.
The class bool is a subclass of the class int, and cannot be subclassed.


`-` `complex`형 

In [13]:
a=1+2j
b=2-2j
c=a+b

In [14]:
c?

Type:        complex
String form: (3+0j)
Docstring:  
Create a complex number from a real part and an optional imaginary part.

This is equivalent to (real + imag*1j) where imag defaults to 0.


- 우리는 잘 쓰지 않음. 

`-` 형태변환: float $\to$ int 

In [15]:
a=3.6234

In [16]:
b=int(a) 
b

3

`-` 형태변환: int $\to$ float

In [17]:
a=3
a

3

In [18]:
float(a)

3.0

`-` 형태변환: bool $\to$ int, int $\to$ bool 

In [19]:
int(True)

1

`-` 형태변환: bool $\to$ float, float $\to$ bool

In [20]:
float(False)

0.0

In [21]:
bool(0.00)

False

`-` 형태변환: 이런것도 가능한가? 싶은것도 가능함. 

In [22]:
bool(-3.14)

True

- 저는 이런코드를 의도하고 사용하지 않아요.. 

`-` 형태변환이 항상되는건 아님 

In [23]:
float(3+0j) # 사실상 3+0j = 3 이므로 형변환이 가능할듯 한데 안된다. 

TypeError: can't convert complex to float

`-` 암묵적형변환 (implicit) 
- 눈치껏? 변환하는 느낌

(예비학습) implicit의 의미 

- 추운날씨 -> 보일러좀 틀자! (explicit) / 오늘 좀 추운것 같지 않아? (implicit)
- 짜장면 먹을래? -> 싫어 (explicit) / 난 어제 짜장면 먹었는데.. (implicit) 

(예제)

In [24]:
True*1 # 1을 곱할건데 너 계속 True로 있을꺼야?.. 

1

In [25]:
1*1.0 # 1.0을 곱할건데 너 계속 int로 있을꺼야?..

1.0

### str 

`-` 선언 

In [26]:
a='guebin'

In [27]:
a

'guebin'

#### ***연산***

`-` 더하기(+)연산 

In [28]:
a='X'
b='2'

In [29]:
a+b

'X2'

`-` 빼기(-)연산 

In [30]:
a='X2'
b='2'

In [31]:
a-b

TypeError: unsupported operand type(s) for -: 'str' and 'str'

- 이런건 없다.. 

`-` 곱하기(*)연산 

In [32]:
a='X'

In [33]:
a*3 # a*3=a+a+a 이니까? 

'XXX'

아래도 가능하다. 

In [34]:
a='X'

In [35]:
3*a

'XXX'

아래와 같이 쓸수도 있다. 

In [36]:
a='X'
b=3

In [37]:
a*b

'XXX'

아래는 불가능하다. 

In [38]:
a='X'
b='Y'
a*b

TypeError: can't multiply sequence by non-int of type 'str'

`-` 나눗셈(/)연산 

In [39]:
a='XX'

In [40]:
a/2

TypeError: unsupported operand type(s) for /: 'str' and 'int'

- 이런건 없다.. 

#### ***인덱싱***

`-` str은 하나의 벡터에 문자가 하나씩 들어가 있는 형태라고 생각하면 된다. 

In [41]:
a='guebin'

In [42]:
a

'guebin'

- 6개의 칸에 글씨가 하나씩 들어가 있음. 

`-` 대괄호 `[]`안에 숫자를 넣는 방식으로 벡터의 원소를 호출할수 있다. (주의: 인덱스가 0부터 시작함)

In [43]:
a[0] #첫번째 원소

'g'

In [44]:
a[1] #(첫번째 원소가 아니라) 두번째 원소 

'u'

마지막원소는 -1로 호출가능하다. 

In [45]:
a[-1]

'n'

마지막에서 2번째 원소는 -2로 호출가능하다. 

In [46]:
a[-2]

'i'

`-` 요약하면 아래와 같은 방식으로 호출가능함. 

|g|u|e|b|i|n|
|-|-|-|-|-|-|
|0|1|2|3|4|5|
|0|-5|-4|-3|-2|-1|

In [47]:
a[0]

'g'

In [48]:
a[1]

'u'

In [49]:
a[3]

'b'

In [50]:
a[-4]

'e'

`-` `:`을 이용하여 여러개의 원소를 호출할 수 있음. 

In [51]:
a='guebin'

In [52]:
a[0:3] # a[0],a[1],a[2],a[3] 이 아니라 a[0],a[1],a[2] 가 호출된다. 즉 마지막의 3은 호출되지 않는다. 

'gue'

In [53]:
a[1:3] # start = 1 // stop = 3 

'ue'

index=1부터 시작해서 마지막원소까지 호출하려면?

In [54]:
a[5] # 마지막원소 = n

'n'

In [55]:
a[1:5] # 5는 포함되지 않음

'uebi'

In [56]:
a[1:6] # 정답! (그런데 너무 헷갈린다)

'uebin'

안 헷갈리게 하는방법이 없을까?.. 

-index를 사용하면 어떨까?

In [57]:
a[1:-1] # 이건 결국 a[1:5]와 같은것임 (표를 확인)

'uebi'

해결책? 생략한다!! 

In [58]:
a[1:]

'uebin'

`-` 생략의 응용1

In [59]:
a='k-pop'

In [60]:
a[2:6]

'pop'

In [61]:
a[2:]

'pop'

`-` 생략의 응용2

In [62]:
a='k-pop'

In [63]:
a[0:2]

'k-'

In [64]:
a[:2]

'k-'

`-` 생략의 응용3

In [65]:
a='k-pop'

In [66]:
a[0:6]

'k-pop'

In [67]:
a[:]

'k-pop'

#### ***str 메소드 (str 특수기능)***

`-` 파이썬의 변수는 단순히 정보를 담는 그릇이 아니다. 항상 기능이 있다. 

In [68]:
a='ABCD' # a라는 변수는 단순히 정보를 담는 그릇이 아님

In [69]:
a.lower() # a.lower()를 쓰면 a의 모든 문자열을 소문자로 바꾼연산결과를 제공

'abcd'

여기에서 lower()는 문자열에 특화된 기능임. 따라서 당연히 아래는 불가능 

In [70]:
a=3.14
a.lower()

AttributeError: 'float' object has no attribute 'lower'

`-` 자료형에 특화된 기능을 확인하는 방법? `a.` + `tab` 으로 목록 확인가능

In [71]:
a='guebin'

In [72]:
a. # 이상태에서 탭을 누르면 된다. 

SyntaxError: invalid syntax (2820180789.py, line 1)

In [73]:
a.capitalize()

'Guebin'

`-` 문자열에 대한 다른내용들은 추후에..

`-` 마음의눈: `a.f()`형태를 읽는 팁 
- `a.f()`는 `f(a)`로 생각하면 편리함.
- `a.f(2)`는 `f(a,2)`로 생각하면 편리함. 
- 이런점에서 R의 `%>%`연산자와 비슷하다고 생각할 수 있다. (약간 다르긴함) 

`-` 사실 `.`은 좀 더 다양한 상황에서 쓰일수 있다. 위의 경우 `변수이름.함수이름` 의 형태인데 이것외에 
- `패키지이름.함수이름`
- `패키지이름.변수이름` 
- `패키지이름.패키지이름.함수이름` 
- ... 

와 같이 다양한 형태가 가능하다. 근본적인 공통점은 .을 기준으로 `상위개념.하위개념` 으로 이해하는것이 좋다. 

#### ***0차원 vs 1차원***

`-` `len`함수 소개: 원소의 개수를 알려준다. 

In [74]:
a='3.14'

In [75]:
len(a)

4

`-` 0차원변수인 경우는 `len` 함수가 동작하지 않는다. 

In [76]:
a=3.14
len(a)

TypeError: object of type 'float' has no len()

### list

#### ***선언***

`-` 리스트의 선언 

In [77]:
a=[11,22]

In [78]:
a

[11, 22]

In [79]:
type(a)

list

`-` 비어있는 리스트의 선언 

In [80]:
a=[] # 방법1
a

[]

In [81]:
a=list() # 방법2
a

[]

#### ***연산***

`-` 더하기연산

In [82]:
a=[11,12]
b=[12,13]

(우리의 예상)

- $a=(11,12)$
- $b=(12,13)$
- $a+b=(23,25)$

In [83]:
a+b

[11, 12, 12, 13]

- 우리의 예상과 다른 결과가 나타남 $\to$ 파이썬은 R처럼 좋은 계산기능이 자동으로 내장되어있지 않음 

`-` 일반적인 벡터연산을 기대할 수 없음 

In [84]:
a=[1,2,3]
b=3 
a+b

TypeError: can only concatenate list (not "int") to list

`-` 뺄샘은 정의되지 않음 

In [85]:
a=[1,2]
b=[1,2]
a-b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

`-` 곱하기는 정의가능 

In [86]:
a=[1,2]

In [87]:
2*a # a+a 

[1, 2, 1, 2]

`-` list에서는 더하기와 곱하기를 조금 다르게 해석한다. 원소의 `추가`와 `반복추가`의 개념으로 해석함. 

In [88]:
a=[1,2]
b=[11,22,33]

In [89]:
2*a+3*b

[1, 2, 1, 2, 11, 22, 33, 11, 22, 33, 11, 22, 33]

In [90]:
a+[33]+[345]

[1, 2, 33, 345]

`-` 더하기와 곱하기는 `추가`와 `반복추가`를 의미하지만 그렇다고 뺄셈과 나눗셈이 삭제를 의미하는건 아님. 

In [91]:
a=[1,2,3]
a-[3] # 이런건 없다

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [92]:
a=[1,2,1,2]
a/2 # 이런건 없다

TypeError: unsupported operand type(s) for /: 'list' and 'int'

`-` 더하기와 곱하기 추가와 반복추가의 기능을 가지고 있어서 은근히 편할때가 있긴 있음. 그런데 일반적인 벡터연산을 하고싶을 경우도 있음. 

(예제1)

In [93]:
a=[1,2]
b=[3,4] 

a+b = [4,6] 이 되도록 할려면?

(풀이1)

list끼리는 수치연산이 불가능하지만, list의 원소끼리는 가능할 수 있음. 

In [94]:
a[0]+b[0] # a의 첫번째 원소를 추출, b의 첫번째 원소를 추출, 둘을 더함 

4

In [95]:
a[1]+b[1] 

6

In [326]:
[a[0]+b[0], a[1]+b[1]]

[4, 6]

풀이가 가능한 이유? a,b는 리스트이지만 a[0], a[1], b[0], b[1]은 인트형임. 인트형은 + 연산이 가능했음.

In [327]:
type(a[0])

int

(풀이2)

numpy 패키지 (파이썬의 여러 수치연산을 담당하는 라이브러리) 활용 
- 이러한 벡터연산은 누구나 필요로 하는 연산임. 
- 내가 아니더라도 누군가가 프로그래밍화 시켜놓을 것임. 
- 그 누군가가 자신이 만든 코드를 잘 정리하여 무료로 배포했을 수 있음. (패키지를 배포한다고 표현함) 
- 그 패키지를 우리는 가져와서 쓰기만 하면된다. 

패지키를 설치하는 방법 
- `pip install numpy` 
- `conda install -c conda-forge numpy` 

In [96]:
import numpy # 설치한 패키지를 쓰겠다고 선언함

In [98]:
a=[1,2]
b=[3,4]

In [118]:
aa=numpy.array(a) ## aa는 리스트가 아니라 넘파이 어레이, numpy.array()는 numpy패키지에서 제공하는 array함수를 쓰겠다는 의미
bb=numpy.array(b) ## bb는 리스트가 아니라 넘파이 어레이, numpy.array()는 numpy패키지에서 제공하는 array함수를 쓰겠다는 의미

In [115]:
aa+bb

array([4, 6])

이런것도 가능함 

In [116]:
aa*bb 

array([3, 8])

In [117]:
aa*bb+aa 

array([ 4, 10])

(풀이3) 

In [119]:
import numpy as np # 설치한 패키지를 쓰겠다고 선언함, 그런데 numpy 말고 np라는 이름으로 쓰겠음. 

In [121]:
np.array(a)+np.array(b)

array([4, 6])

#### ***인덱싱***

`-` str형과 동일한 내용

### list 고급

`-` `list`의 원소는 꼭 숫자(int,float)만 가능한 것이 아니다. 

In [124]:
lst=[1,3.14,True,'a',[1,2],(1,2),
      {'name':'guebin','age':38},{1,2,3}]

각 원소의 type을 알아보자. 

In [136]:
type(lst[0])

int

In [131]:
type(lst[1])

float

In [153]:
type(lst[2])

bool

In [154]:
type(lst[3])

str

In [156]:
type(lst[4])

list

In [157]:
type(lst[5])

tuple

In [158]:
type(lst[6])

dict

In [132]:
type(lst[7])

set

`-` 리스트 원소를 수정할 수 있다. 

In [170]:
a=[1,2,3]
a

[1, 2, 3]

In [171]:
a[0]

1

In [172]:
a[0]=111

In [173]:
a

[111, 2, 3]

`-` 당연한 기능같은데 이것이 불가능한 경우도 있다. 

(가능한경우)

In [174]:
a=['g','u','e','b','i','n']
a

['g', 'u', 'e', 'b', 'i', 'n']

In [175]:
a[0]

'g'

In [176]:
a[0]='G'

In [177]:
a

['G', 'u', 'e', 'b', 'i', 'n']

(불가능한경우) 스트링에서는 원소수정이 되지 않음. 

In [164]:
a='guebin'
a

'guebin'

In [168]:
a[0]

'g'

In [169]:
a[0]='G'

TypeError: 'str' object does not support item assignment

`-` 리스트는 원소의 삭제도 가능하다. 

아래와 같이 문자열로 된 리스트를 선언하자. 

In [191]:
a= ['G','u','e','b','i','n']
a

['G', 'u', 'e', 'b', 'i', 'n']

사실 더 쉽게 할 수 있음. 

In [192]:
a= 'Guebin'
a=list(a)
a

['G', 'u', 'e', 'b', 'i', 'n']

첫번째 원소를 삭제하고 싶다면? 

In [193]:
del a[0]

In [194]:
a

['u', 'e', 'b', 'i', 'n']

이 상태에서 다시 첫번째 원소를 삭제하면? 

In [195]:
del a[0]

In [196]:
a

['e', 'b', 'i', 'n']

`-` 리스트 원소 추가

(예제) 비어있는 리스트를 만들고 원소 0,1,2를 차례로 추가하여 보자. 

(풀이1) 

In [197]:
a=[]
a

[]

In [198]:
a=a+[0]
a

[0]

In [199]:
a=a+[1]
a

[0, 1]

In [200]:
a=a+[2]
a

[0, 1, 2]

(풀이2) 

In [201]:
a=[]
a

[]

In [202]:
a += [0]
a

[0]

In [203]:
a += [1]
a

[0, 1]

In [204]:
a += [2]
a

[0, 1, 2]

(풀이3) 리스트 특화기능(=메소드)를 이용

In [207]:
a=[]
a

[]

In [208]:
a.append(0)
a

[0]

In [209]:
a.append(1)
a

[0, 1]

In [210]:
a.append(2)
a

[0, 1, 2]

`-` `a+[4]`와  `a.append(4)`의 차이점은? 

(관찰1)

In [215]:
a=[1,2,3]
a+[4] ## 리스트 a와 리스트 [4]의 연산결과를 알려줘

[1, 2, 3, 4]

In [216]:
a ## a는 그대로임. 변화없음. 

[1, 2, 3]

(관찰2)

In [218]:
a=[1,2,3]
a.append(4)

In [220]:
a # a가 변화함. 

[1, 2, 3, 4]

비슷해보이지만 약간의 미묘한 차이점이 있음. 

`a.append(4)`: `a`를 append하라. $\rightarrow$ `a`가 변함. 

`a+[4]`: `a`와 `[4]`를 add하라. 

`-` list와 관련된 메소드 정리 

`a`라는 객체에서 `index`라는 메서드를 썼지만, `a`는 변하지 않음. 

#### [$\ast$] 리스트컴프리헨션 ($\star\star\star$)

***[예비학습]`for`문 벼락치기***

프로그램 안에서 반복해서 무엇인가를 하고싶다? $\rightarrow$ `for`

In [143]:
for i in [0,1,2,3]: ## 반복실행계획
    print(i) ## 반복실행내용

0
1
2
3


In [144]:
for i in [0,1,2,4]: 
    print(i)

0
1
2
4


In [145]:
i=0
print(i)
i=1
print(i)
i=2
print(i)
i=4
print(i)

0
1
2
4


In [146]:
sumi=0
for i in [0,1,2,4]: ## 반복실행계획
    sumi=sumi+i 

In [147]:
sumi

7

In [148]:
sumi=0
i=0
sumi=sumi+i
i=1
sumi=sumi+i
i=2
sumi=sumi+i
i=4
sumi=sumi+i

In [149]:
sumi

7

예비학습 끝! 

[예제] $2^0,2^1,2^2,2^3,2^4,2^5$를 계산해보자. 

(풀이1) - 진짜 나쁜코드; $2^0,\dots,2^{100}$까지 계산하라고 하면? 

In [150]:
x=[2**0,2**1,2**2,2**3,2**4,2**5]

In [151]:
x

[1, 2, 4, 8, 16, 32]

(풀이2) - 그럭저럭 괜찮은 코드; `for`문을 이용했음. (버전1)

In [2]:
x=[]
for i in [0,1,2,3,4,5]:
    x.append(2**i)

In [3]:
x

[1, 2, 4, 8, 16, 32]

(풀이2) - 그럭저럭 괜찮은 코드; `for`문을 이용했음. (버전2) 

In [4]:
x=[]
for i in [0,1,2,3,4,5]:
    x=x+[2**i]

In [5]:
x

[1, 2, 4, 8, 16, 32]

(풀이2) - 그럭저럭 괜찮은 코드; `for`문을 이용했음. (버전3) 

In [6]:
x=[]
for i in [0,1,2,3,4,5]:
    x+=[2**i] ### 암기법: x=x+[2**i] 에서 중복되는것을 제거하고 순서를 바꾼다... 

In [7]:
x

[1, 2, 4, 8, 16, 32]

(풀이3) - 좋은 풀이; `리스트컴프리헨션`을 이용

In [8]:
x=[2**i for i in [0,1,2,3,4,5]]

In [9]:
x

[1, 2, 4, 8, 16, 32]

문법을 암기하는 방법 
- 조건제시법을 연상하라. 
- $\big\{2^0,2^1,2^2,2^3,2^4,2^5\big\}=\big\{2^i: i=0,1,\dots, 5 \big\}$

리스트 컴프리헨션
- 리스트를 매우 효율적으로 만드는 테크닉 
- `for`문에 비하여 가지고 있는 장점: (1) 코드가 간단하다. (2) 빠르다. 

[예제] 리스트 컴프리핸션을 이용하여 아래와 같은 리스트를 만들어라. 

In [10]:
['SSSS','PPPP','AAAA','MMMM']

['SSSS', 'PPPP', 'AAAA', 'MMMM']

(풀이)

In [11]:
[i*4 for i in 'SPAM']

['SSSS', 'PPPP', 'AAAA', 'MMMM']

[예제] 리스트 컴프리헨션을 이용하여 아래와 같은 리스트를 만들어라. 

In [12]:
['X1','X2','X3','Y1','Y2','Y3']

['X1', 'X2', 'X3', 'Y1', 'Y2', 'Y3']

(풀이)

In [13]:
[i+j for i in 'XY' for j in '123']

['X1', 'X2', 'X3', 'Y1', 'Y2', 'Y3']

In [14]:
[i+j for i in ['stat','math'] for j in '12345']

['stat1',
 'stat2',
 'stat3',
 'stat4',
 'stat5',
 'math1',
 'math2',
 'math3',
 'math4',
 'math5']

$\big\{"xy": x \in \{stat,math\}, y \in \{1,2,3,4,5\} \big\}$

In [16]:
for i in ['stat','math']:
    for j in '12345':
        print(i+j)

stat1
stat2
stat3
stat4
stat5
math1
math2
math3
math4
math5


In [166]:
i='stat'
j='1'
print(i+j)

stat1


#### [$\ast$] 리스트의 중첩 ($\star\star\star$)

In [167]:
a=[[11,12,13], 
   [21,22,23], 
   [31,32,33]]

In [168]:
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [169]:
a[0][0]

11

In [170]:
a[0][1]

12

| |0|1|2|
|-|-|-|-|
|0|11|12|13|
|1|21|22|23|
|2|31|32|33|

In [171]:
a[2][1]

32

$\bf A$라는 매트릭스에서 (2,1)의 원소를 뽑아온것같은 느낌을 준다. 

#### 2차원 배열의 느낌!!!

1차원 배열을 사실상 다차원배열로 확장할 수 있는 아이디어를 제공 

### (3) `tuple`

리스트와 비슷하다.

차이점1: [ ] 대신에 ( )를 사용한다. 

차이점2: 불변형이다. (값을 바꿀 수 없음)

In [172]:
a=(4,6,"pencil",3.2+4.6j,[3,4])

In [173]:
a[2]

'pencil'

In [174]:
a[0:3]

(4, 6, 'pencil')

In [175]:
a[2]="Pencil"

TypeError: 'tuple' object does not support item assignment

참고로 리스트는 값이 잘 바뀜

In [176]:
a=[4,6,"pencil",3.2+4.6j,[3,4]]

In [177]:
a

[4, 6, 'pencil', (3.2+4.6j), [3, 4]]

In [178]:
a[2]="PENCIL"

In [179]:
a

[4, 6, 'PENCIL', (3.2+4.6j), [3, 4]]

차이점3: 하나의 원소로 이루어진 튜플을 만들때는 쉼표를 붙여야 함. 

In [180]:
a=[1]

In [181]:
a+[2]

[1, 2]

In [182]:
a=(1,)

In [183]:
a+(2,)

(1, 2)

차이점4: (의미가 명확할때) 튜플의 괄호는 생략가능하다. 

In [184]:
a=1,2

In [185]:
a

(1, 2)

의미가 명확할때 생략해야함 

In [186]:
1,2 + 3,4,5 

(1, 5, 4, 5)

In [187]:
(1,2) + (3,4,5)

(1, 2, 3, 4, 5)

(의문) 튜플은 왜 쓰는가? 

튜플의 특징: 불변성 

실수로 값을 변경하지 않도록 방지할 수 있다?

솔직히 쓸모없음. 

#### [$\ast$] 튜플은 단순히 불변리스트가 아니다. ($\star\star\star$)

**[예제1]**: 튜플언패킹

In [188]:
name,age,sex,height,weight = 'Tom',20,'M',180,70

In [189]:
name

'Tom'

In [190]:
weight

70

**[예제2]**: 

In [191]:
coor=(33.9425,-118.408056)

In [192]:
coor

(33.9425, -118.408056)

In [193]:
lat, long = coor

In [194]:
lat

33.9425

In [195]:
long

-118.408056

**[예제3]**: 임시변수 사용없이 두 변수의 값을 교환 

In [196]:
a=10
b=20

In [197]:
a,b=b,a

In [198]:
a

20

In [199]:
b

10

**[예제4]**: 함수의 입력으로 튜플을 넣을때 

*[예제4의 예비학습]* 함수 벼락치기 

In [2]:
def cal(a,b):
    print(str(a) + '+' + str(b) + '=' + str(a+b))
    print(str(a) + '-' + str(b) + '=' + str(a-b))
    print(str(a) + '*' + str(b) + '=' + str(a*b))
    print(str(a) + '/' + str(b) + '=' + str(a/b))

In [3]:
cal(2,33)

2+33=35
2-33=-31
2*33=66
2/33=0.06060606060606061


벼락치기 끝 

In [11]:
### 우리가 원하는 형태 
input=[3,4]
cal(input)

TypeError: cal() missing 1 required positional argument: 'b'

In [13]:
### 실제 
cal(input[0],input[1])

3+4=7
3-4=-1
3*4=12
3/4=0.75


In [14]:
input=(3,4)

In [15]:
cal(*input) 

3+4=7
3-4=-1
3*4=12
3/4=0.75


**[예제5]** 함수의 입력을 튜플로 넣을때 (2) 

두점 사이의 거리를 구하는 함수를 만들어 보자. 

$x=(x_1,x_2,x_3)$

$y=(y_1,y_2,y_3)$

의 거리를 구하려면 

$\sqrt{(x_1-y_1)^2+(x_2-y_2)^2+(x_3-y_3)^2}$

In [37]:
def distance(x1,x2,x3,y1,y2,y3):
    import math 
    d=(x1-y1)**2+(x2-y2)**2+(x3-y3)**2
    print(math.sqrt(d))

In [40]:
x=(0,0,0)
y=(0,1,1)
distance(*x,*y)

1.4142135623730951


In [41]:
def distance(x,y):
    import math 
    x1,x2,x3=x 
    y1,y2,y3=y
    d=(x1-y1)**2+(x2-y2)**2+(x3-y3)**2
    print(math.sqrt(d))

In [42]:
distance(x,y)

1.4142135623730951


### !!! 함수를 호출할때 인수앞에 *를 붙여 튜플을 언패킹할 수 있다. 

**[예제6]**: 플레이스홀더 

(예비학습) `for`문 

In [43]:
for i in [1,2,3,4]:
    print(i)

1
2
3
4


In [45]:
i=[1,2,3,4][0]
print(i)
i=[1,2,3,4][1]
print(i)
i=[1,2,3,4][2]
print(i)
i=[1,2,3,4][3]
print(i)

1
2
3
4


In [47]:
for i in [1,2,3,[1,2,3]]:
    print(i)

1
2
3
[1, 2, 3]


In [46]:
i=[1,2,3,[1,2,3]][0]
print(i)
i=[1,2,3,[1,2,3]][1]
print(i)
i=[1,2,3,[1,2,3]][2]
print(i)
i=[1,2,3,[1,2,3]][3]
print(i)

1
2
3
[1, 2, 3]


In [48]:
for i in [[1,22],[1,3],[2,14],[7,23]]:
    print(i)

[1, 22]
[1, 3]
[2, 14]
[7, 23]


In [49]:
for i,j in [[1,22],[1,3],[2,14],[7,23]]:
    print(i)

1
1
2
7


In [53]:
i,j=[[1,22],[1,3],[2,14],[7,23]][0]
print(i)
i,j=[[1,22],[1,3],[2,14],[7,23]][1]
print(i)
i,j=[[1,22],[1,3],[2,14],[7,23]][2]
print(i)
i,j=[[1,22],[1,3],[2,14],[7,23]][3]
print(i)

1
1
2
7


예제시작 

In [60]:
idlist=[('guebin', '202112345','M','Korea'), 
        ('iu', '202154321','F','Korea'), 
        ('hodong', '201812321','M','Korea')]

In [61]:
for i in idlist: 
    print(i)

('guebin', '202112345', 'M', 'Korea')
('iu', '202154321', 'F', 'Korea')
('hodong', '201812321', 'M', 'Korea')


In [62]:
for name,studentid,sex,nat in idlist: 
    print(name)

guebin
iu
hodong


In [66]:
for name, _, _, _ in idlist: 
    print(name)

guebin
iu
hodong


### \# 요약 

(1) 스트링, 튜플, 리스트는 모두 시퀀스형이라고 부른다. 

(2) 시컨스형의 카테고리 
- 컨테이너 시퀀스: list, tuple. 
- 균일(flat) 시퀀스: str 
- 가변 시퀀스: list 
- 불면 시퀀스: tuple, str

| | 컨테이너 시퀀스 | flat 시퀀스|
|:-:|:-:|:-:|
|가변 시퀀스|list|-|
|불변 시퀀스|tuple|str|

(3) 시퀀스형은 모두 인덱싱과 슬라이싱이 가능함. 