# (노트) 넘파이 2022

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [파이썬특강]

### import 

In [41]:
import numpy as np

### numpy공부 1단계

#### 선언 

In [42]:
a=np.array([1,2,3]) # list를 선언하고 np.array화 
l=[1,2,3]

#### 기본연산 브로드캐스팅 

In [43]:
a+1

array([2, 3, 4])

In [44]:
l+1

TypeError: can only concatenate list (not "int") to list

In [45]:
a*2

array([2, 4, 6])

In [46]:
l*2

[1, 2, 3, 1, 2, 3]

In [47]:
a/2

array([0.5, 1. , 1.5])

In [48]:
l/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [49]:
a-2

array([-1,  0,  1])

In [50]:
l-2

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [56]:
a**2

array([1, 4, 9])

In [58]:
l**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [62]:
a%2 # %2 = 2로 나눈 나머지를 리턴

array([1, 0, 1])

In [61]:
l%2

TypeError: unsupported operand type(s) for %: 'list' and 'int'

#### 기타수학연산지원 

In [51]:
np.sqrt(a), np.sqrt(l)

(array([1.        , 1.41421356, 1.73205081]),
 array([1.        , 1.41421356, 1.73205081]))

In [52]:
np.log(a), np.log(l)

(array([0.        , 0.69314718, 1.09861229]),
 array([0.        , 0.69314718, 1.09861229]))

In [53]:
np.exp(a), np.exp(l)

(array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([ 2.71828183,  7.3890561 , 20.08553692]))

In [54]:
np.sin(a), np.sin(l)

(array([0.84147098, 0.90929743, 0.14112001]),
 array([0.84147098, 0.90929743, 0.14112001]))

### numpy공부 2단계 

#### 인덱싱 1차원 

`-` 선언 

In [64]:
l=[11,22,33,44,55,66]
a=np.array(l)

`-` 인덱스로 접근 

In [65]:
l[0],l[1],l[2],l[3],l[4],l[5]

(11, 22, 33, 44, 55, 66)

In [66]:
a[0],a[1],a[2],a[3],a[4],a[5]

(11, 22, 33, 44, 55, 66)

`-` `:`이용 (슬라이싱) 

In [67]:
l[2:4] ## index=2에서 출발해서 index=4에서 멈춘다. (4는 포함하지 않음) 

[33, 44]

In [68]:
a[2:4]

array([33, 44])

`-` 정수배열에 의한 인덱싱 

In [69]:
a

array([11, 22, 33, 44, 55, 66])

In [70]:
a[[0,2,4]]

array([11, 33, 55])

`-` 부울값에 의한 인덱싱 

In [71]:
a

array([11, 22, 33, 44, 55, 66])

In [147]:
a[[True,False,True,False,True,False]]

array([11, 33, 55])

응용하면? 

In [73]:
a < 33

array([ True,  True, False, False, False, False])

In [74]:
a[a<33]

array([11, 22])

리스트는 불가능 

In [75]:
l

[11, 22, 33, 44, 55, 66]

In [76]:
l<33 ## 여기서부터 에러남 

TypeError: '<' not supported between instances of 'list' and 'int'

#### 인덱싱 2차원 

`-` 중첩리스트와 2차원 np.array 선언 

In [88]:
A = [[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8],[-5,-6,-7,-8]]
A2 = np.array(A)

In [89]:
A

[[1, 2, 3, 4], [-1, -2, -3, -4], [5, 6, 7, 8], [-5, -6, -7, -8]]

In [90]:
A2

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

`-` A에서 원소인덱싱 

In [136]:
A[0][0] # (1,1)의 원소 

1

In [137]:
A[1][2] # (2,3)의 원소 

-3

In [141]:
A[-1][0] # (4,1)의 원소 

-5

`-` A2에서 원소인덱싱 

In [140]:
A2[0][0] # (1,1)의 원소 

1

In [139]:
A2[1][2] # (2,3)의 원소 

-3

In [142]:
A2[-1][0] # (4,1)의 원소 

-5

`-` 이렇게 해도된다? (넘파이에서 제시하는 신기술, R에서는 기본탑재기능, 이중 list는 불가능) 

In [144]:
A2[0,0] # (1,1)의 원소 

1

In [145]:
A2[1,2] # (2,3)의 원소 

-3

In [146]:
A2[-1,0] # (4,1)의 원소

-5

`-` 슬라이싱!

In [126]:
A2

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

In [127]:
A2[0,:] ## 1행

array([1, 2, 3, 4])

In [128]:
A2[0] ## 1행

array([1, 2, 3, 4])

In [129]:
A2[[0,2],:] # 1,3행 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [130]:
A2[[0,2]] # 1,3 행 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [134]:
A2[:,0] # 1열 

array([ 1, -1,  5, -5])

In [135]:
A2[:,[0,2]] # 1,3열 

array([[ 1,  3],
       [-1, -3],
       [ 5,  7],
       [-5, -7]])

#### 1차원 배열의 선언 

`-` 리스트나 튜플을 선언하고 형변환 

In [148]:
np.array((1,2,3))

array([1, 2, 3])

In [149]:
np.array([1,2,3])

array([1, 2, 3])

`-` range()를 이용하여 만들고 형변환 

In [168]:
np.array(range(12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

`-` np.zeros, np.ones 

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [26]:
np.ones(3)

array([1., 1., 1.])

`-` np.linspace 

In [27]:
np.linspace(0,1,12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

`-` np.arange

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

#### reshape 

`-` reshape: ndarray의 특수한 기능 

In [152]:
l=[11,22,33,44,55,66]
a=np.array(l)

In [153]:
a ## 길이가 6인 벡터

array([11, 22, 33, 44, 55, 66])

In [154]:
a.reshape(2,3)

array([[11, 22, 33],
       [44, 55, 66]])

In [155]:
a ## reshape은 a자체를 변화시키진 않음

array([11, 22, 33, 44, 55, 66])

In [156]:
b = a.reshape(3,2)
b

array([[11, 22],
       [33, 44],
       [55, 66]])

`-` 다시 b를 a처럼 바꾸고싶다면? 

In [161]:
b

array([[11, 22],
       [33, 44],
       [55, 66]])

In [157]:
b.reshape(6)

array([11, 22, 33, 44, 55, 66])

`-` reshape with -1

In [172]:
a=np.array(range(24))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [174]:
a.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [175]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [176]:
a.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [177]:
a.reshape(6,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [179]:
a.reshape(8,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [180]:
a.reshape(12,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [181]:
a=a.reshape(12,-1)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [182]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### 2차원 배열의 선언 

In [190]:
np.zeros((3,3)) # np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [194]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [186]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [193]:
np.diag([1,2,3]) # np.diag((1,2,3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### 랜덤으로 생성 

In [197]:
np.random.randn(10) # 표준정규분포에서 10개 뽑음

array([-0.31950873, -0.4730328 ,  2.17929498,  1.13760578, -0.58171429,
       -0.5099881 ,  1.54514196,  1.54674838, -0.84117625, -0.17791251])

In [198]:
np.random.rand(10) # 0~1사이에서 10개 뽑음 

array([0.09277044, 0.00948238, 0.39084564, 0.19141791, 0.03245606,
       0.63743156, 0.95064866, 0.90088916, 0.65873055, 0.04710192])

In [201]:
np.random.randn(4).reshape(2,2)

array([[ 0.29411949,  1.64390509],
       [ 0.51914663, -1.52956145]])

In [202]:
np.random.randn(6).reshape(3,2)

array([[ 0.07721829, -0.94757824],
       [-0.84315351,  0.06729526],
       [-0.69778453,  0.51408556]])

#### 행렬 

In [214]:
A= np.array(range(4)).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [215]:
A.T # 전치행렬 

array([[0, 2],
       [1, 3]])

In [216]:
np.linalg.inv(A) # 역행렬 

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [217]:
A@np.linalg.inv(A) # 행렬곱 

array([[1., 0.],
       [0., 1.]])

#### 2차원 배열과 연립1차방정식

`-` 아래의 연립방정식 고려 

$\begin{cases}
y + z + w= 3 \\
x + z + w= 3 \\
x + y + w= 3 \\ 
x + y + z= 3 \\ 
\end{cases}$ 

`-` 행렬표현은? 

$\begin{bmatrix}
0 & 1 & 1 & 1 \\ 
1 & 0 & 1 & 1 \\
1 & 1 & 0 & 1 \\ 
1 & 1 & 1 & 0 \\ 
\end{bmatrix} \begin{bmatrix} x \\ y \\ z \\ w \end{bmatrix} = \begin{bmatrix} 3 \\ 3 \\ 3 \\ 3  \end{bmatrix}$

`-` 풀이

In [218]:
A = np.array([[0,1,1,1],[1,0,1,1],[1,1,0,1],[1,1,1,0]])
A

array([[0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]])

In [220]:
b=np.array([3,3,3,3]).reshape(4,1)
b

array([[3],
       [3],
       [3],
       [3]])

In [222]:
np.linalg.inv(A) @ b

array([[1.],
       [1.],
       [1.],
       [1.]])