# (노트) 넘파이 2022

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [파이썬특강]

### import 

In [224]:
import numpy as np

### numpy공부 1단계

#### 선언 

In [225]:
a=np.array([1,2,3]) # list를 선언하고 np.array화 
l=[1,2,3]

#### 기본연산 브로드캐스팅 

In [226]:
a+1

array([2, 3, 4])

In [227]:
l+1

TypeError: can only concatenate list (not "int") to list

In [228]:
a*2

array([2, 4, 6])

In [229]:
l*2

[1, 2, 3, 1, 2, 3]

In [230]:
a/2

array([0.5, 1. , 1.5])

In [231]:
l/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [232]:
a-2

array([-1,  0,  1])

In [233]:
l-2

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [234]:
a**2

array([1, 4, 9])

In [235]:
l**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [236]:
a%2 # %2 = 2로 나눈 나머지를 리턴

array([1, 0, 1])

In [237]:
l%2

TypeError: unsupported operand type(s) for %: 'list' and 'int'

#### 기타수학연산지원 

In [238]:
np.sqrt(a), np.sqrt(l)

(array([1.        , 1.41421356, 1.73205081]),
 array([1.        , 1.41421356, 1.73205081]))

In [239]:
np.log(a), np.log(l)

(array([0.        , 0.69314718, 1.09861229]),
 array([0.        , 0.69314718, 1.09861229]))

In [240]:
np.exp(a), np.exp(l)

(array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([ 2.71828183,  7.3890561 , 20.08553692]))

In [241]:
np.sin(a), np.sin(l)

(array([0.84147098, 0.90929743, 0.14112001]),
 array([0.84147098, 0.90929743, 0.14112001]))

### numpy공부 2단계 

#### 인덱싱 1차원 

`-` 선언 

In [242]:
l=[11,22,33,44,55,66]
a=np.array(l)

`-` 인덱스로 접근 

In [243]:
l[0],l[1],l[2],l[3],l[4],l[5]

(11, 22, 33, 44, 55, 66)

In [244]:
a[0],a[1],a[2],a[3],a[4],a[5]

(11, 22, 33, 44, 55, 66)

`-` `:`이용 (슬라이싱) 

In [245]:
l[2:4] ## index=2에서 출발해서 index=4에서 멈춘다. (4는 포함하지 않음) 

[33, 44]

In [246]:
a[2:4]

array([33, 44])

`-` 정수배열에 의한 인덱싱 

In [247]:
a

array([11, 22, 33, 44, 55, 66])

In [248]:
a[[0,2,4]]

array([11, 33, 55])

`-` 부울값에 의한 인덱싱 

In [249]:
a

array([11, 22, 33, 44, 55, 66])

In [250]:
a[[True,False,True,False,True,False]]

array([11, 33, 55])

응용하면? 

In [251]:
a < 33

array([ True,  True, False, False, False, False])

In [252]:
a[a<33]

array([11, 22])

리스트는 불가능 

In [253]:
l

[11, 22, 33, 44, 55, 66]

In [254]:
l<33 ## 여기서부터 에러남 

TypeError: '<' not supported between instances of 'list' and 'int'

#### 인덱싱 2차원 

`-` 중첩리스트와 2차원 np.array 선언 

In [255]:
A = [[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8],[-5,-6,-7,-8]]
A2 = np.array(A)

In [256]:
A

[[1, 2, 3, 4], [-1, -2, -3, -4], [5, 6, 7, 8], [-5, -6, -7, -8]]

In [257]:
A2

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

`-` A에서 원소인덱싱 

In [258]:
A[0][0] # (1,1)의 원소 

1

In [259]:
A[1][2] # (2,3)의 원소 

-3

In [260]:
A[-1][0] # (4,1)의 원소 

-5

`-` A2에서 원소인덱싱 

In [261]:
A2[0][0] # (1,1)의 원소 

1

In [262]:
A2[1][2] # (2,3)의 원소 

-3

In [263]:
A2[-1][0] # (4,1)의 원소 

-5

`-` 이렇게 해도된다? (넘파이에서 제시하는 신기술, R에서는 기본탑재기능, 이중 list는 불가능) 

In [264]:
A2[0,0] # (1,1)의 원소 

1

In [265]:
A2[1,2] # (2,3)의 원소 

-3

In [266]:
A2[-1,0] # (4,1)의 원소

-5

`-` 슬라이싱!

In [267]:
A2

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

In [268]:
A2[0,:] ## 1행

array([1, 2, 3, 4])

In [269]:
A2[0] ## 1행

array([1, 2, 3, 4])

In [270]:
A2[[0,2],:] # 1,3행 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [271]:
A2[[0,2]] # 1,3 행 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [272]:
A2[:,0] # 1열 

array([ 1, -1,  5, -5])

In [273]:
A2[:,[0,2]] # 1,3열 

array([[ 1,  3],
       [-1, -3],
       [ 5,  7],
       [-5, -7]])

#### 1차원 배열의 선언 

`-` 리스트나 튜플을 선언하고 형변환 

In [274]:
np.array((1,2,3))

array([1, 2, 3])

In [275]:
np.array([1,2,3])

array([1, 2, 3])

`-` range()를 이용하여 만들고 형변환 

In [276]:
np.array(range(12))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

`-` np.zeros, np.ones 

In [277]:
np.zeros(3)

array([0., 0., 0.])

In [278]:
np.ones(3)

array([1., 1., 1.])

`-` np.linspace 

In [279]:
np.linspace(0,1,12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

`-` np.arange

In [280]:
np.arange(5)

array([0, 1, 2, 3, 4])

#### reshape 

`-` reshape: ndarray의 특수한 기능 

In [281]:
l=[11,22,33,44,55,66]
a=np.array(l)

In [282]:
a ## 길이가 6인 벡터

array([11, 22, 33, 44, 55, 66])

In [283]:
a.reshape(2,3)

array([[11, 22, 33],
       [44, 55, 66]])

In [284]:
a ## reshape은 a자체를 변화시키진 않음

array([11, 22, 33, 44, 55, 66])

In [285]:
b = a.reshape(3,2)
b

array([[11, 22],
       [33, 44],
       [55, 66]])

`-` 다시 b를 a처럼 바꾸고싶다면? 

In [286]:
b

array([[11, 22],
       [33, 44],
       [55, 66]])

In [287]:
b.reshape(6)

array([11, 22, 33, 44, 55, 66])

`-` reshape with -1

In [288]:
a=np.array(range(24))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [289]:
a.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [290]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [291]:
a.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [292]:
a.reshape(6,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [293]:
a.reshape(8,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [294]:
a.reshape(12,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [295]:
a=a.reshape(12,-1)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [296]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### 2차원 배열의 선언 

In [297]:
np.zeros((3,3)) # np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [298]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [299]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [300]:
np.diag([1,2,3]) # np.diag((1,2,3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### 랜덤으로 생성 

In [301]:
np.random.randn(10) # 표준정규분포에서 10개 뽑음

array([ 0.44061615,  0.36691872, -0.32069182, -0.63029849, -1.3942187 ,
        1.15455084,  0.87235237,  0.34417005, -1.3727437 , -0.45079427])

In [302]:
np.random.rand(10) # 0~1사이에서 10개 뽑음 

array([0.66082979, 0.05598307, 0.18905264, 0.01297172, 0.3371496 ,
       0.25495874, 0.28447852, 0.55942857, 0.52117175, 0.35920542])

In [303]:
np.random.randn(4).reshape(2,2)

array([[-0.59906778,  1.04432385],
       [-0.4431056 ,  0.00252869]])

In [304]:
np.random.randn(6).reshape(3,2)

array([[ 0.57007242, -0.44500429],
       [-1.6278574 ,  0.37105558],
       [ 0.404343  , -0.64245438]])

#### 행렬 

In [305]:
A= np.array(range(4)).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [306]:
A.T # 전치행렬 

array([[0, 2],
       [1, 3]])

In [307]:
np.linalg.inv(A) # 역행렬 

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [308]:
A@np.linalg.inv(A) # 행렬곱 

array([[1., 0.],
       [0., 1.]])

### numpy공부 3단계: 차원의 개념

#### 2차원 배열과 연립1차방정식

`-` 아래의 연립방정식 고려 

$\begin{cases}
y + z + w= 3 \\
x + z + w= 3 \\
x + y + w= 3 \\ 
x + y + z= 3 \\ 
\end{cases}$ 

`-` 행렬표현은? 

$\begin{bmatrix}
0 & 1 & 1 & 1 \\ 
1 & 0 & 1 & 1 \\
1 & 1 & 0 & 1 \\ 
1 & 1 & 1 & 0 \\ 
\end{bmatrix} \begin{bmatrix} x \\ y \\ z \\ w \end{bmatrix} = \begin{bmatrix} 3 \\ 3 \\ 3 \\ 3  \end{bmatrix}$

`-` 풀이

In [317]:
A = np.array([[0,1,1,1],[1,0,1,1],[1,1,0,1],[1,1,1,0]])
A

array([[0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]])

In [318]:
b=np.array([3,3,3,3]).reshape(4,1)
b

array([[3],
       [3],
       [3],
       [3]])

In [319]:
np.linalg.inv(A) @ b

array([[1.],
       [1.],
       [1.],
       [1.]])

`-` 다른풀이 

b를 아래와 같이 만들어도 된다. 

In [323]:
b=np.array([3,3,3,3])
b

array([3, 3, 3, 3])

In [324]:
np.linalg.inv(A) @ b

array([1., 1., 1., 1.])

#### `@`의 유연성

`-` 엄밀하게는 아래의 행렬곱이 가능하다. 
- (2,2) @ (2,1) => (2,1) 
- (1,2) @ (2,2) => (1,2) 

In [329]:
A = np.array([1,2,3,4]).reshape(2,2) 
b = np.array([1,2]).reshape(2,1) 
A@b

array([[ 5],
       [11]])

In [330]:
A.shape, b.shape, (A@b).shape

((2, 2), (2, 1), (2, 1))

In [332]:
A = np.array([1,2,3,4]).reshape(2,2) 
b = np.array([1,2]).reshape(1,2) 
b@A

array([[ 7, 10]])

In [335]:
A.shape, b.shape, (b@A).shape

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

`-` 당연히 아래는 성립안한다. 

In [336]:
A = np.array([1,2,3,4]).reshape(2,2) 
b = np.array([1,2]).reshape(2,1) 
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [337]:
A = np.array([1,2,3,4]).reshape(2,2) 
b = np.array([1,2]).reshape(1,2) 
A@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

`-` 아래는 어떨까? 계산가능할까? $\to$ 모두 계산가능!
- (2,) @ (2,2) => (2,)
- (2,2) @ (2,) => (2,)

In [342]:
A = np.array([1,2,3,4]).reshape(2,2) 
b = np.array([1,2])
A@b

array([ 5, 11])

In [360]:
A.shape, b.shape, (A@b).shape

((2, 2), (2,), (2,))

- b를 마치 (2,1)처럼 본다. 

In [345]:
A = np.array([1,2,3,4]).reshape(2,2) 
b = np.array([1,2])
b@A

array([ 7, 10])

In [361]:
b.shape, A.shape, (b@A).shape

((2,), (2, 2), (2,))

- b를 마치 (1,2)처럼 보는 느낌

`-` 아래는 어떠할까? 

In [367]:
b1=np.array([1,2,3,4])
b2=np.array([1,2,3,4])
b1@b2

30

In [368]:
b1.shape,b2.shape,(b1@b2).shape

((4,), (4,), ())

- (1,4) @ (4,1) 로 생각함 

In [365]:
b1=np.array([1,2,3,4])
b2=np.array([1,2,3,4])
b2@b1

30

In [366]:
b2.shape,b1.shape,(b2@b1).shape

((4,), (4,), ())

- (1,4) @ (4,1) 로 생각함 

`-` 즉 마치 아래와 같이 해석한다. 

In [377]:
b1=np.array([1,2,3,4]).reshape(1,4)
b2=np.array([1,2,3,4]).reshape(4,1)
b1@b2

array([[30]])

In [378]:
b1.shape,b2.shape,(b1@b2).shape

((1, 4), (4, 1), (1, 1))

`-` 때로는 (4,1)@(1,4)와 같은 계산결과를 얻고 싶을 수 있는데 이때는 차원을 명시해야함 

In [590]:
b1=np.array([1,2,3,4]).reshape(4,1)
b2=np.array([1,2,3,4]).reshape(1,4)
b1@b2

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [591]:
b1.shape, b2.shape, (b1@b2).shape

((4, 1), (1, 4), (4, 4))

`-` 아래도 가능 

In [593]:
b1=np.array([1,2,3,4])
b2=np.array([1,2,3,4])

#### 차원 

`-` 아래는 모두 미묘하게 다르다. 

In [392]:
a= np.array(1) # 스칼라, 0d array
a, a.shape

(array(1), ())

In [393]:
a= np.array([1]) #벡터, 1d array
a, a.shape

(array([1]), (1,))

In [394]:
a= np.array([[1]]) #메트릭스, 2d array
a, a.shape

(array([[1]]), (1, 1))

In [395]:
a= np.array([[[1]]]) #텐서, 3d array
a, a.shape

(array([[[1]]]), (1, 1, 1))

### numpy공부 4단계: 축의 개념 

#### np.concatenate

`-` 기본예제 

In [401]:
a=np.array([1,2])
b=-a 

In [402]:
np.concatenate([a,b])

array([ 1,  2, -1, -2])

`-` 응용 

In [403]:
a=np.array([1,2])
b=-a
c=2*a

In [404]:
np.concatenate([a,b,c])

array([ 1,  2, -1, -2,  2,  4])

- 여기까진 딱히 칸캐터네이트의 메리트가 없어보이죠? 
- 리스트였다면 a+b+c 하면 되는 기능이니까? 

`-` 2array 에 적용해보자 

In [405]:
a=np.array(range(4)).reshape(2,2) 
b=-a

In [408]:
np.concatenate([a,b])

array([[ 0,  1],
       [ 2,  3],
       [ 0, -1],
       [-2, -3]])

`-` 옆으로 붙일려면? 

In [409]:
np.concatenate([a,b],axis=1)

array([[ 0,  1,  0, -1],
       [ 2,  3, -2, -3]])

`-` axis=1이 뭐지? axis=0,2 등을 치면 어떻게 될까? 

In [410]:
np.concatenate([a,b],axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 0, -1],
       [-2, -3]])

- 이건 그냥 np.concatenate([a,b])와 같다. 
- np.concatenate([a,b])는 np.concatenate([a,b],axis=0) 의 생략버전이군? 

In [411]:
np.concatenate([a,b],axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

- 이런건 없다. 

`-` axis의 의미가 뭔지 좀 궁금함. 좀더 예제를 살펴보자. 

In [422]:
a=np.array(range(2*3*4)).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [423]:
b=-a
b

array([[[  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]]])

In [424]:
np.concatenate([a,b],axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]]])

In [425]:
np.concatenate([a,b],axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]]])

In [426]:
np.concatenate([a,b],axis=2)

array([[[  0,   1,   2,   3,   0,  -1,  -2,  -3],
        [  4,   5,   6,   7,  -4,  -5,  -6,  -7],
        [  8,   9,  10,  11,  -8,  -9, -10, -11]],

       [[ 12,  13,  14,  15, -12, -13, -14, -15],
        [ 16,  17,  18,  19, -16, -17, -18, -19],
        [ 20,  21,  22,  23, -20, -21, -22, -23]]])

- 이번에는 2까지 된다? 

In [427]:
np.concatenate([a,b],axis=3)

AxisError: axis 3 is out of bounds for array of dimension 3

- 3까지는 안된다? 

`-` 뭔가 나름의 방식으로 합쳐지는데 원리가 뭘까? 

(분석1) np.concatenate([a,b],axis=0)

In [430]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [435]:
a.shape,b.shape, np.concatenate([a,b],axis=0).shape

((2, 3, 4), (2, 3, 4), (4, 3, 4))

- 첫번째차원이 바뀌었다 => 첫번째 축이 바뀌었다 => axis=0 (파이썬은 0부터 시작하니까!)

(분석2) np.concatenate([a,b],axis=1)

In [434]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [436]:
a.shape,b.shape, np.concatenate([a,b],axis=1).shape

((2, 3, 4), (2, 3, 4), (2, 6, 4))

- 두번째차원이 바뀌었다 => 두번째 축이 바뀌었다 => axis=1 

(분석3) np.concatenate([a,b],axis=2)

In [437]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [439]:
a.shape,b.shape, np.concatenate([a,b],axis=2).shape

((2, 3, 4), (2, 3, 4), (2, 3, 8))

- 세번째차원이 바뀌었다 => 세번째 축이 바뀌었다 => axis=2

(분석4) np.concatenate([a,b],axis=3) 

In [440]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [441]:
a.shape,b.shape, np.concatenate([a,b],axis=3).shape

AxisError: axis 3 is out of bounds for array of dimension 3

- 네번째 차원은 없다 => 네번째 축도 없다 => axis=3으로 하면 에러가 난다. 

(보너스) np.concatenate([a,b],axis=-1)

In [440]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [443]:
np.concatenate([a,b],axis=-1)

array([[[  0,   1,   2,   3,   0,  -1,  -2,  -3],
        [  4,   5,   6,   7,  -4,  -5,  -6,  -7],
        [  8,   9,  10,  11,  -8,  -9, -10, -11]],

       [[ 12,  13,  14,  15, -12, -13, -14, -15],
        [ 16,  17,  18,  19, -16, -17, -18, -19],
        [ 20,  21,  22,  23, -20, -21, -22, -23]]])

In [445]:
a.shape,b.shape,np.concatenate([a,b],axis=-1).shape

((2, 3, 4), (2, 3, 4), (2, 3, 8))

- 마지막 차원이 바뀌었다 => 마지막 축이 바뀌었다 => axis= -1 

(보너스2) np.concatenate([a,b],axis=-2)

In [447]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [448]:
np.concatenate([a,b],axis=-2)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]]])

In [449]:
a.shape,b.shape,np.concatenate([a,b],axis=-2).shape

((2, 3, 4), (2, 3, 4), (2, 6, 4))

- 마지막에서 두번째 차원이 바뀌었다 => 마지막에서 두번째 축이 바뀌었다 => axis=-2 

`-` 0차원은 축이 없으므로 concatenate를 쓸 수 없다. 

In [452]:
a=np.array(1)
b=np.array(-1) 

In [453]:
a.shape,b.shape

((), ())

In [454]:
np.concatenate([a,b])

ValueError: zero-dimensional arrays cannot be concatenated

`-` 꼭 a,b가 같은 차원일 필요는 없다. 

In [458]:
a=np.array(range(4)).reshape(2,2)
b=np.array(range(2)).reshape(2,1) 

In [459]:
np.concatenate([a,b],axis=1)

array([[0, 1, 0],
       [2, 3, 1]])

In [460]:
a.shape,b.shape,np.concatenate([a,b],axis=1).shape

((2, 2), (2, 1), (2, 3))

#### np.stack

`-` 혹시 아래가 가능할까? 
- (3,) 결합 (3,) => (3,2) 

In [465]:
a=np.array([1,2,3])
b=-a

In [466]:
a,b

(array([1, 2, 3]), array([-1, -2, -3]))

In [467]:
np.concatenate([a,b],axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

- 불가능

`-` 아래와 같이 하면 가능하다. 

In [473]:
a=np.array([1,2,3])
b=-a

In [474]:
np.concatenate([a.reshape(3,1), b.reshape(3,1)],axis=1)

array([[ 1, -1],
       [ 2, -2],
       [ 3, -3]])

- 분석: (3) (3) => (3,1) (3,1) => (3,1) concat (3,1) 

`-` 이걸 줄여서 아래와 같이 할 수 있다. 

In [475]:
np.stack([a, b],axis=1)

array([[ 1, -1],
       [ 2, -2],
       [ 3, -3]])

`-` 아래도 가능 

In [477]:
np.stack([a,b],axis=0)

array([[ 1,  2,  3],
       [-1, -2, -3]])

`-` 분석해보고 외우자 

(분석1)

In [478]:
a=np.array([1,2,3])
b=-a

In [480]:
a.shape,b.shape,np.stack([a,b],axis=0).shape

((3,), (3,), (2, 3))

- (3) (3) => 첫위치에 축을 추가 (axis=0) => (1,3) (1,3) => (2,3) 

(분석2) 

In [484]:
a=np.array([1,2,3])
b=-a

In [485]:
a.shape,b.shape,np.stack([a,b],axis=1).shape

((3,), (3,), (3, 2))

- (3) (3) => 두번째 위치에 축을 추가 (axis=1) => (3,1) (3,1) => (3,2) 

`-` 고차원예제 

In [490]:
a=np.arange(3*4*5).reshape(3,4,5)
b=-a

In [496]:
a.shape,b.shape

((3, 4, 5), (3, 4, 5))

In [497]:
np.stack([a,b],axis=0).shape # (3,4,5) => (1,3,4,5) // 첫위치에 축이 추가

(2, 3, 4, 5)

In [498]:
np.stack([a,b],axis=1).shape # (3,4,5) => (3,1,4,5) // 두번쨰 위치에 축이 추가

(3, 2, 4, 5)

In [499]:
np.stack([a,b],axis=2).shape # (3,4,5) => (3,4,1,5) // axis=2 

(3, 4, 2, 5)

In [500]:
np.stack([a,b],axis=3).shape # (3,4,5) => (3,4,5,1) // axis=3

(3, 4, 5, 2)

In [502]:
np.stack([a,b],axis=-1).shape # (3,4,5) => (3,4,5,1) // axis=-1 <=> axis=3 

(3, 4, 5, 2)

***np.concatenate 는 축의 총 갯수를 유지하면서 결합, np.stack은 축의 갯수를 하나 증가시키며 결합*** 

#### sum 

`-` 1차원 

In [504]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [505]:
a.sum()

6

In [506]:
a.sum(axis=0)

6

`-` 2차원 

In [508]:
a=np.array(range(6)).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [509]:
a.sum(axis=0)

array([3, 5, 7])

In [510]:
a.sum(axis=1)

array([ 3, 12])

`-` 2차원 결과 분석 

In [513]:
a.shape, a.sum(axis=0).shape 

((2, 3), (3,))

- 첫번째 축이 삭제됨 

In [514]:
a.shape, a.sum(axis=1).shape 

((2, 3), (2,))

- 두번째 축이 삭제됨 

`-` 연습

In [518]:
a=np.array(range(10)).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

(문제1) 1열의 합, 2열의 합을 계산하고 싶다면? 

(풀이) 차원이 (5,2) => (2,) 로 나와야 한다 (그럼 첫번째 축이 삭제되어야하네?)

In [520]:
a.sum(axis=0)

array([20, 25])

(문제2) 1행의 합, 2행의 합, ..., 5행의 합을 계산하고 싶다면? 

(풀이) 차원이 (5,2) => (5,)로 나와야 한다 (그럼 두번째 축이 삭제되어야하네?)

In [521]:
a.sum(axis=1)

array([ 1,  5,  9, 13, 17])

#### mean, max, min, prod

`-` 모두 sum과 유사한논리 

In [673]:
a=np.array(range(10)).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [677]:
a.mean(axis=0), a.max(axis=0), a.min(axis=0), a.prod(axis=0)

(array([4., 5.]), array([8, 9]), array([0, 1]), array([  0, 945]))

In [678]:
a.mean(axis=1), a.max(axis=1), a.min(axis=1), a.prod(axis=1)

(array([0.5, 2.5, 4.5, 6.5, 8.5]),
 array([1, 3, 5, 7, 9]),
 array([0, 2, 4, 6, 8]),
 array([ 0,  6, 20, 42, 72]))

#### argmax, argmin

`-` 1차원 

In [532]:
a=np.array([1,-2,3,10,4])
a

array([ 1, -2,  3, 10,  4])

In [533]:
a.argmax()

3

In [534]:
a.argmax(axis=0)

3

In [535]:
a.argmin()

1

In [536]:
a.argmin(axis=0)

1

`-` 2차원 

In [540]:
np.random.seed(1)
a=np.random.randn(4*5).reshape(4,5)
a

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944],
       [-1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521]])

In [541]:
a.argmin(axis=0)

array([1, 2, 3, 0, 1])

In [543]:
a.argmax(axis=1)

array([0, 1, 0, 4])

#### cumprod, cumsum

`-` 1차원 

In [600]:
a=np.array([1,2,3,4])

In [601]:
a.cumsum(), a.cumprod()

(array([ 1,  3,  6, 10]), array([ 1,  2,  6, 24]))

In [602]:
a.cumsum(axis=0), a.cumprod(axis=0)

(array([ 1,  3,  6, 10]), array([ 1,  2,  6, 24]))

`-` 2차원 

In [612]:
a=np.array(range(3*4)).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [613]:
a.cumsum(axis=0), a.cumprod(axis=0)

(array([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21]]),
 array([[  0,   1,   2,   3],
        [  0,   5,  12,  21],
        [  0,  45, 120, 231]]))

In [614]:
a.cumsum(axis=1), a.cumprod(axis=1)

(array([[ 0,  1,  3,  6],
        [ 4,  9, 15, 22],
        [ 8, 17, 27, 38]]),
 array([[   0,    0,    0,    0],
        [   4,   20,  120,  840],
        [   8,   72,  720, 7920]]))

#### diff 

`-` 1차차분 

In [616]:
a=np.array([1,2,4,6,7])
a

array([1, 2, 4, 6, 7])

In [617]:
np.diff(a)

array([1, 2, 2, 1])

`-` 2차차분 

In [621]:
np.diff(np.diff(a))

array([ 1,  0, -1])

In [620]:
np.diff(a,n=2)

array([ 1,  0, -1])

`-` prepend, append

In [627]:
a

array([1, 2, 4, 6, 7])

In [636]:
np.diff(a,prepend=100) # [100, a] 와 같은 리스트를 차분 

array([-99,   1,   2,   2,   1])

In [637]:
np.diff(a,append=100) # [a, 100] 와 같은 리스트를 차분 

array([ 1,  2,  2,  1, 93])

In [638]:
np.diff(a,prepend=a[0]) # [a[0], a] 와 같은 리스트를 차분 

array([0, 1, 2, 2, 1])

In [639]:
np.diff(a,append=a[-1]) # [a, a[-1]] 와 같은 리스트를 차분

array([1, 2, 2, 1, 0])

`-` 2차원 array의 차분 

In [642]:
a=np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [643]:
np.diff(a,axis=0)

array([[6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6]])

In [644]:
np.diff(a,axis=1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### split(ver1)

`-` 1차원

In [556]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [557]:
np.split(a,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [558]:
np.split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [559]:
np.split(a,6)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

`-` 2차원

In [568]:
b=np.stack([a,a])
b

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [569]:
b.shape

(2, 6)

In [570]:
np.split(b,2,axis=0)

[array([[1, 2, 3, 4, 5, 6]]), array([[1, 2, 3, 4, 5, 6]])]

In [571]:
np.split(b,2,axis=1)

[array([[1, 2, 3],
        [1, 2, 3]]),
 array([[4, 5, 6],
        [4, 5, 6]])]

In [572]:
np.split(b,3,axis=1)

[array([[1, 2],
        [1, 2]]),
 array([[3, 4],
        [3, 4]]),
 array([[5, 6],
        [5, 6]])]

#### split(ver2)

`-` 1차원: 리스트입력 

In [579]:
np.random.seed(43052)
a=np.random.rand(12)
a

array([0.81768226, 0.04953212, 0.83868626, 0.61977707, 0.12254052,
       0.11712779, 0.8795562 , 0.97941543, 0.90986893, 0.96667407,
       0.59164493, 0.84014933])

In [582]:
np.split(a,(2,5)) # 처음2, 그다음3(=합쳐서5), 나머지 

[array([0.81768226, 0.04953212]),
 array([0.83868626, 0.61977707, 0.12254052]),
 array([0.11712779, 0.8795562 , 0.97941543, 0.90986893, 0.96667407,
        0.59164493, 0.84014933])]

In [583]:
np.split(a,(1,3,5)) # :1, 1:3, 3:5, 5: 

[array([0.81768226]),
 array([0.04953212, 0.83868626]),
 array([0.61977707, 0.12254052]),
 array([0.11712779, 0.8795562 , 0.97941543, 0.90986893, 0.96667407,
        0.59164493, 0.84014933])]

`-` 2차원: 리스트입력 

In [585]:
a= np.arange(30).reshape(6,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [587]:
np.split(a,[3,4],axis=0) # :3, 3:4, 4: 

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])]

In [589]:
np.split(a,[1,3,4],axis=1) # :1, 1:3, 3:4, 4: 

[array([[ 0],
        [ 5],
        [10],
        [15],
        [20],
        [25]]),
 array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17],
        [21, 22],
        [26, 27]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23],
        [28]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29]])]

### numpy공부 5단계: 랜덤모듈 

#### 심플 랜덤데이터 

`-` 0~1사이의 난수생성 (유니폼) 

In [651]:
np.random.rand(10)

array([0.36838019, 0.08044368, 0.47142422, 0.43324944, 0.22441988,
       0.01174913, 0.91587271, 0.88325068, 0.32707103, 0.45758847])

In [724]:
np.random.rand(10)*2 

array([0.17357698, 1.54728811, 0.42947961, 0.54618299, 1.72232505,
       1.71506913, 0.3777304 , 1.79139203, 0.92771729, 1.84567438])

- 0~2사이에 난수생성 

In [655]:
np.random.rand(10)+1

array([1.85295256, 1.45750574, 1.26272651, 1.97333158, 1.838797  ,
       1.30833822, 1.90005548, 1.15576246, 1.42542199, 1.36933063])

- 1~2사이에 난수생성 

In [657]:
np.random.rand(10)*2+1

array([1.46425599, 2.51877008, 1.71378585, 1.57511749, 2.24413128,
       2.64926146, 1.91524319, 1.74615005, 2.93089931, 1.53133061])

- (0,1) -> (0,2) -> (1,3) 사이의 난수생성 

`-` 표준정규분포 

In [661]:
np.random.randn(10) # N(0,1)에서 추출 

array([-0.30741791, -0.97222481,  0.7195569 , -1.38687131, -2.31300954,
        1.16746569, -0.43949896, -0.5344806 , -0.61180546, -0.09264951])

In [662]:
np.random.randn(10)+1 # N(1,1)에서 추출 

array([1.03059075, 0.45034902, 0.16416266, 0.70403348, 1.35219517,
       1.99221104, 0.86248567, 0.72117275, 0.12252714, 0.99729087])

In [665]:
np.random.randn(10)*2 # N(0,4)에서 추출 

array([ 0.18785135,  0.33272003, -0.71425681,  0.82201527,  0.53307576,
       -1.14574555,  2.02801834,  4.21591501,  1.04908636, -2.2047736 ])

In [679]:
np.random.randn(10)*2+3 # N(3,4)에서 추출 

array([-0.74700375,  2.5325643 , -0.08782487,  7.39282872,  1.97335439,
        3.60636284,  4.15125448,  4.67069242,  1.02484023,  2.91304426])

`-` np.random.randint 

In [716]:
np.random.randint(10) # [0,10) 의 범위에서 하나의 정수 생성 

9

In [717]:
np.random.randint(10, size=(20,)) # [0,10)의 범위에서 20개의 정수생성

array([8, 7, 6, 2, 8, 1, 4, 0, 5, 1, 2, 3, 0, 4, 8, 5, 1, 4, 3, 2])

In [719]:
np.random.randint(10, size=(2,2)) # [0,10)의 범위에서 (2,2) shape 의 정수생성 

array([[3, 5],
       [9, 9]])

In [726]:
np.random.randint(low=10,size=(2,2)) # 위와 같은코드, 즉 [0,10)의 범위에서 (2,2) shape의 정수생성

array([[2, 5],
       [5, 3]])

In [723]:
np.random.randint(low=10,high=20,size=(5,5)) # [10,20) 의 범위에서 (2,2) shape정수생성

array([[15, 10, 19, 10, 16],
       [14, 18, 17, 17, 11],
       [10, 16, 18, 14, 10],
       [16, 13, 18, 15, 11],
       [15, 14, 10, 15, 18]])

엥 ??

의문: np.random.randint(low=10,size=(2,2))는 np.random.randint(high=10,size=(2,2))이어야 맞는거 아닌가

***저도 그런것 같아요, 그런데 구현을 이상하게 한듯합니다***

In [698]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, 

> note: Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).