# (노트) einsum 질문대응

- toc:true
- branch: master
- badges: true
- comments: true
- author: 신록예찬
- hide: false
- categories: [데이터과학]

In [36]:
import numpy as np

### (2,3) @ (3,4) 행렬곱 

In [38]:
A = np.array(range(2*3)).reshape(2,3)
B = np.array(range(3*4)).reshape(3,4) 

A는 (2,3) martix -> A매트릭스의 각 원소는 $a_{ij}$로 볼 수 있고 i=1,2 and j=1,2,3 

B는 (3,3) matrix -> B매트릭스의 각 원소는 $b_{jk}$로 볼 수 있고, j=1,2,3 and k=1,2,3,4 

In [39]:
A @ B

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

(1,1)의 원소는 $a_{11}b_{11}+a_{12}b_{21}+a_{13}b_{31}$ 으로 볼 수 있음 

In [43]:
A[0,0]*B[0,0] + A[0,1]*B[1,0] + A[0,2]*B[2,0]

20

유사한 논리로 (i,k)의 원소는 아래와 같이 볼 수 있음 

$\sum_{j=1}^{n} a_{ij}b_{jk}$

(재해석) 

가능한 모든 $a_{ij}$, $b_{jk}$에 대하여 $\sum_{j=1}^{n} a_{ij}b_{jk}$와 같은 연산을 정의한다면 결과는 $c_{ik}$로 나옴 = 최종차원 ik

마치 $a_{ij}, b_{jk} \to c_{ik}$ 로 가는 변환이 이루어진것 같으므로 `ij,jk -> ik`이라는 약어로 선형변환을 해석할 수 있음 

In [46]:
np.einsum('ij, jk -> ik',A,B)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [47]:
np.einsum('ij, jk -> ik',B,A)

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,4)->(3,newaxis,4) (2,3)->(3,2) 

이건 수행불가능한데  $\sum_{j=1}^{n} b_{ij}a_{jk}$ 꼴로 연산을 정의할 수 없기 때문임. ($b$의 두번쨰축과 $a$의 첫번째축의 차원이 같지않음, b의 두번째축은 4, a의 첫번째 축은 2)

### (3,) @ (3,) -> None (무차원, 무축, 축이0개, scalar)

`-` 내적이라고 합니당

In [51]:
a= np.array([1,2,3])
b= -a 

`-` 방법1

In [52]:
a @ b 

-14

In [53]:
b @ a 

-14

`-` 방법2

In [57]:
np.einsum('i, i -> ',a,b)

-14

### (3,) @ (3,) -> (3,3) 

`-` 외적

In [58]:
a= np.array([1,2,3])
b= -a 

In [59]:
a.reshape(3,1) @ b.reshape(1,3)

array([[-1, -2, -3],
       [-2, -4, -6],
       [-3, -6, -9]])

`-` 아인슈타인법

In [62]:
np.einsum('i,j -> ij',a,b)

array([[-1, -2, -3],
       [-2, -4, -6],
       [-3, -6, -9]])

`-` a,b 길이 달라도 가능 

In [64]:
a= np.array([1,2,3])
b= np.array([1,2,3,4])

In [65]:
a.reshape(3,1) @ b.reshape(1,4)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [66]:
np.einsum('i,j -> ij',a,b)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

### 아인슈타인법은 텐서간의 연산 일반화 버전임 

대칭행렬 

In [67]:
A=np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [68]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [69]:
np.einsum('ij->ji', A)

array([[1, 3],
       [2, 4]])

대각선원소만! 

In [75]:
A=np.array(range(5*5)).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
np.diag(A)

array([ 0,  6, 12, 18, 24])

In [77]:
np.einsum('ii -> i',A)

array([ 0,  6, 12, 18, 24])

trace~

In [75]:
A=np.array(range(5*5)).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
0+6+12+18+24

60

In [78]:
np.trace(A)

60

In [81]:
np.einsum('ii ->',A)

60

(2,3,4,5) @ (4,) -> (2,3,5) 

In [90]:
A = np.array(range(2*3*4*5)).reshape(2,3,4,5)
b = np.array(range(4)) 

In [94]:
np.einsum('ijkl,k -> ijl',A,b)

array([[[ 70,  76,  82,  88,  94],
        [190, 196, 202, 208, 214],
        [310, 316, 322, 328, 334]],

       [[430, 436, 442, 448, 454],
        [550, 556, 562, 568, 574],
        [670, 676, 682, 688, 694]]])

A@b 는 불가능 

In [96]:
A@b 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 5)

(2,3,4,5) @ (3,) -> (2,4,5) 

In [98]:
A = np.array(range(2*3*4*5)).reshape(2,3,4,5)
b = np.array(range(3)) 

In [99]:
np.einsum('ijkl,j -> ikl',A,b)

array([[[100, 103, 106, 109, 112],
        [115, 118, 121, 124, 127],
        [130, 133, 136, 139, 142],
        [145, 148, 151, 154, 157]],

       [[280, 283, 286, 289, 292],
        [295, 298, 301, 304, 307],
        [310, 313, 316, 319, 322],
        [325, 328, 331, 334, 337]]])

A @ b 혹은 b @ A 는 모두 불가능 

In [114]:
A @ b 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

In [115]:
b @ A 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

`-` 아래는 가능함 

In [109]:
np.array(range(4)) @ A

array([[[ 70,  76,  82,  88,  94],
        [190, 196, 202, 208, 214],
        [310, 316, 322, 328, 334]],

       [[430, 436, 442, 448, 454],
        [550, 556, 562, 568, 574],
        [670, 676, 682, 688, 694]]])

In [113]:
A @ np.array(range(5))

array([[[  30,   80,  130,  180],
        [ 230,  280,  330,  380],
        [ 430,  480,  530,  580]],

       [[ 630,  680,  730,  780],
        [ 830,  880,  930,  980],
        [1030, 1080, 1130, 1180]]])

### np.einsum은 다양한 텐서연산으로 확장할 수 있음. 그런데 @는 2차원 매트릭스만 특화된 연산자임 

고차원일 경우에는 `@` 를 쓰는게 아님

2차원이하일 경우는 유연하게 해석하여 처리하는데 3차원 이상의 경우 맨 마지막 2개의 차원만 인정함 (저도 이건 몰랐어ㅛㅇ.. 저는 처음 2개의 차원으로 알고있었어요) 

헷갈리니까 2차원 넘어가면 np.einsum을 써야함 

그래도 @의 동작을 알아보자 

In [118]:
A=np.array(range(2*3*4*5*6*7*9)).reshape(2,3,4,5,6,7,9) 

A는 (7,9)로 해석함 -> 앞에 7, 뒤에 9를 붙일 수 있음

In [127]:
c= A @ np.array(range(9))
c.shape

(2, 3, 4, 5, 6, 7)

In [125]:
c= A @ np.array(range(7))
c.shape

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 7 is different from 9)

In [129]:
c= np.array(range(7))@ A 
c.shape

(2, 3, 4, 5, 6, 9)

In [130]:
c= A @ np.array(range(7))
c.shape

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 7 is different from 9)