# conv2d

### tf.keras.layers.Convolution2D

In [64]:
import tensorflow as tf 
import tensorflow.experimental.numpy as tnp 

In [65]:
import numpy as np

In [66]:
tf.experimental.numpy.experimental_enable_numpy_behavior()

### errors

`-` 되는상황!

In [97]:
conv2d = tf.keras.layers.Conv2D(1,kernel_size=(2,2))

In [98]:
XXX = tf.constant(range(1*3*3*1),dtype=tf.float64).reshape(1,3,3,1)
conv2d(XXX)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 5.024056 ],
         [ 6.3606877]],

        [[ 9.033952 ],
         [10.370584 ]]]], dtype=float32)>

`-` 입력의 차원이 4차원 텐서가 아니면 에러발생시킴: ValueError

In [99]:
XXX = tf.constant(range(1*3*3),dtype=tf.float64).reshape(1,3,3)
conv2d(XXX)

ValueError: Input 0 of layer "conv2d_19" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (1, 3, 3)

In [100]:
XXX = tf.constant(range(3*3),dtype=tf.float64).reshape(3,3)
conv2d(XXX)

ValueError: Input 0 of layer "conv2d_19" is incompatible with the layer: expected min_ndim=4, found ndim=2. Full shape received: (3, 3)

`-` 데이터타입에 따른 에러: InvalidArgumentError

In [101]:
XXX = tf.constant(range(1*3*3*1)).reshape(1,3,3,1)
conv2d(XXX)

InvalidArgumentError: Exception encountered when calling layer "conv2d_19" (type Conv2D).

cannot compute Conv2D as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:Conv2D]

Call arguments received:
  • inputs=tf.Tensor(shape=(1, 3, 3, 1), dtype=int32)

In [102]:
XXX = tf.constant(range(1*3*3*1),dtype=tf.float16).reshape(1,3,3,1)
conv2d(XXX)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 5.024056 ],
         [ 6.3606877]],

        [[ 9.033952 ],
         [10.370584 ]]]], dtype=float32)>

In [103]:
XXX = tf.constant(range(1*3*3*1),dtype=tf.float32).reshape(1,3,3,1)
conv2d(XXX)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 5.024056 ],
         [ 6.3606877]],

        [[ 9.033952 ],
         [10.370584 ]]]], dtype=float32)>

In [105]:
XXX = tf.constant(range(1*3*3*1),dtype=tf.float64).reshape(1,3,3,1)
conv2d(XXX)

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 5.024056 ],
         [ 6.3606877]],

        [[ 9.033952 ],
         [10.370584 ]]]], dtype=float32)>

### test1

`-` 자료

In [191]:
conv2d = tf.keras.layers.Conv2D(1,kernel_size=(2,2))
XXX = tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1)

`-` 보기편하게

In [192]:
XXX.reshape(1,4,4) # 흑백이미지라 생각하자!

<tf.Tensor: shape=(1, 4, 4), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])>

`-` 출력 

In [193]:
conv2d(XXX)

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[-4.290876 ],
         [-4.5067925],
         [-4.722709 ]],

        [[-5.154542 ],
         [-5.3704586],
         [-5.5863748]],

        [[-6.0182076],
         [-6.234124 ],
         [-6.45004  ]]]], dtype=float32)>

`-` 지금까지 코드를 정리하면

In [194]:
XXX = tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1) ## 다시 XXX 오브젝트 생성
conv2d = tf.keras.layers.Conv2D(1,(2,2)) ## 다시 cv2d object 생성 
conv2d(XXX) ## cv2d object에 XXX 통과!

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[1.4649818],
         [2.0731397],
         [2.6812975]],

        [[3.8976133],
         [4.505771 ],
         [5.113929 ]],

        [[6.3302445],
         [6.938402 ],
         [7.546561 ]]]], dtype=float32)>

`-` 실행할때마다 결과가 다르다? -> 뭔가 랜덤으로 결정되는 부분이 있군 -> seed 통일 

In [195]:
tf.random.set_seed(43052)
XXX = tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1) ## 다시 XXX 오브젝트 생성
conv2d = tf.keras.layers.Conv2D(1,(2,2)) ## 다시 cv2d object 생성 
conv2d(XXX) ## cv2d object에 XXX 통과!

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[ -4.125754 ],
         [ -5.312817 ],
         [ -6.4998803]],

        [[ -8.874006 ],
         [-10.0610695],
         [-11.248133 ]],

        [[-13.622259 ],
         [-14.809322 ],
         [-15.996386 ]]]], dtype=float32)>

- 이제 실행결과가 계속 일치함

`-` 입력과 출력을 보기 편하게 바꾸자

In [196]:
XXX.reshape(1,4,4) ## XXX 

<tf.Tensor: shape=(1, 4, 4), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])>

In [197]:
conv2d(XXX).reshape(1,3,3) ## 2dcv(XXX) 

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[ -4.125754 ,  -5.312817 ,  -6.4998803],
        [ -8.874006 , -10.0610695, -11.248133 ],
        [-13.622259 , -14.809322 , -15.996386 ]]], dtype=float32)>

`-` ??? XXX가 들어가서 뭐가 어떻게 되어서 conv2(XXX)가 되었다는거야? 

In [198]:
tf.constant(conv2d.weights[0]).reshape(2,2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.13014299, -0.23927206],
       [-0.20175874, -0.6158894 ]], dtype=float32)>

In [199]:
0 * -0.13014299 + 1 * -0.23927206 + 4 * -0.20175874 + 5 * -0.6158894

-4.1257540200000005

- 대충 느낌옴.. 

`-` 이미지를 특정 윈도우크기로 나누고 각 픽셀에 어떠한 값을 각각 곱한 다음 다 더하는 연산이 이루어지는거 같다 ->  확인해보자!

`-` 웨이트를 좀 바꾸어보자. (현재는 암산이 불가능하니까)

In [200]:
conv2d.get_weights()

[array([[[[-0.13014299]],
 
         [[-0.23927206]]],
 
 
        [[[-0.20175874]],
 
         [[-0.6158894 ]]]], dtype=float32),
 array([0.], dtype=float32)]

- get_weights는 2개의 원소를 가진 리스트가 나온다. 

In [201]:
conv2d.get_weights()[0].shape # 첫번째 weight의 shape은 2,2,1,1 

(2, 2, 1, 1)

In [202]:
w=np.array([1/4,1/4,1/4,1/4],dtype=np.float32).reshape(2,2,1,1) # weights
w

array([[[[0.25]],

        [[0.25]]],


       [[[0.25]],

        [[0.25]]]], dtype=float32)

In [203]:
b=np.array([3],dtype=np.float32) # bias
b

array([3.], dtype=float32)

In [204]:
conv2d.set_weights([w,b]) # 재설정

`-` 재설정된 가중치로 다시 conv2d를 수행하자 -> 예상이 맞다면 4개픽셀의 평균 + 3일것 

In [205]:
XXX.reshape(1,4,4)

<tf.Tensor: shape=(1, 4, 4), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])>

In [206]:
conv2d(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[ 5.5,  6.5,  7.5],
        [ 9.5, 10.5, 11.5],
        [13.5, 14.5, 15.5]]], dtype=float32)>

In [207]:
(0+1+4+5)/4+3, (1+2+5+6)/4+3 , (2+3+6+7)/4+3

(5.5, 6.5, 7.5)

### tf.keras.layers.Conv2D(1,kernel_size=(2,2)) 요약 및 수동구현  

`-` 요약

(1) size=(2,2)인 윈도우를 만듬. 

(2) XXX에 윈도우를 통과시켜서 (2,2)크기의 sub XXX 를 얻음. sub XXX의 각 원소에 conv2d.weights[0]의 각 원소를 element-wise하게 곱한다. 

(3) (2)의 결과를 모두 더한다. 그리고 그 결과에 다시 conv2d.weights[1]을 수행 

(4) 윈도우를 이동시키면서 반복!

`-` 이걸 컨볼루션 연산이라고 한다. 첫번째 윈도우에 한정하여 이걸 수동으로 구현하면 아래와 같다. 

In [208]:
conv2d(XXX).reshape(1,3,3)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[ 5.5,  6.5,  7.5],
        [ 9.5, 10.5, 11.5],
        [13.5, 14.5, 15.5]]], dtype=float32)>

In [209]:
XXX[0,:2,:2,0] # subXXX

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0., 1.],
       [4., 5.]])>

In [210]:
tf.reshape(conv2d.weights[0],(2,2)) #conv2d.weights[0]의 각원소 

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.25, 0.25],
       [0.25, 0.25]], dtype=float32)>

In [211]:
XXX[0,:2,:2,0] * tf.reshape(conv2d.weights[0],(2,2)) # element-wise 곱

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.  , 0.25],
       [1.  , 1.25]])>

In [212]:
tf.reduce_sum(XXX[0,:2,:2,0] * tf.reshape(conv2d.weights[0],(2,2))) # element-wise 곱 -> 합

<tf.Tensor: shape=(), dtype=float64, numpy=2.5>

In [213]:
conv2d.weights[1] # bias 

<tf.Variable 'conv2d_33/bias:0' shape=(1,) dtype=float32, numpy=array([3.], dtype=float32)>

In [214]:
tf.reduce_sum(XXX[0,:2,:2,0] * tf.reshape(conv2d.weights[0],(2,2))) + conv2d.weights[1] 

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.5])>

note: 컨볼루션은 결국 선형연산

### test2

`-` XXX의 관측치가 여러개라면? 

In [215]:
XXX = tnp.arange(2*4*4*1,dtype=tf.float64).reshape(2,4,4,1)

In [216]:
XXX.reshape(2,4,4)

<tf.Tensor: shape=(2, 4, 4), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]],

       [[16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.]]])>

In [217]:
conv2d(XXX).reshape(2,3,3)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[ 5.5,  6.5,  7.5],
        [ 9.5, 10.5, 11.5],
        [13.5, 14.5, 15.5]],

       [[21.5, 22.5, 23.5],
        [25.5, 26.5, 27.5],
        [29.5, 30.5, 31.5]]], dtype=float32)>

관측치별로 컨볼루션이 적용된다 

### test3 

`-` 윈도우의 크기가 (3,3)이라면? 

In [218]:
XXX = tnp.arange(1*4*4*1,dtype=tf.float64).reshape(1,4,4,1) 
conv2d = tf.keras.layers.Conv2D(1,(3,3))

In [219]:
XXX.reshape(1,4,4)

<tf.Tensor: shape=(1, 4, 4), dtype=float64, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])>

In [220]:
conv2d(XXX).reshape(1,2,2)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[-2.8441195, -2.418283 ],
        [-1.1407745, -0.7149395]]], dtype=float32)>

In [221]:
np.array(conv2d.weights[0]).reshape(3,3)

array([[-0.3444655 ,  0.4521824 ,  0.236296  ],
       [ 0.54707503,  0.19746327,  0.20471048],
       [-0.1245549 , -0.25237298, -0.4904977 ]], dtype=float32)

In [222]:
np.sum(XXX.reshape(1,4,4)[:,:3,:3] * np.array(conv2d.weights[0]).reshape(3,3))

-2.8441193103790283

### test4

`-` conv2의 채널이 여러개라면? 

In [303]:
XXX = tnp.array([1]*1*2*2*1,dtype=tf.float64).reshape(1,2,2,1) 
conv2d = tf.keras.layers.Conv2D(3,(2,2))

- 편의를 위해서 XXX는 1만을 설정. -> 이렇게 되면 conv2d(XXX)의 결과는 모든 weights의 합이 되어 결과를 체크하기 편리하다. 

In [304]:
conv2d(XXX)

<tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[-0.36161608, -1.1864698 ,  0.36680287]]]], dtype=float32)>

- 입력차원이 (1,2,2,1) / 출력차원이 (1,1,1,3) => conv2d는 (2,2,1)를 (1,1,3)으로 보내는 변환이라 해석할 수 있다. 

In [306]:
conv2d.weights # (2,2)는 커널의 크기, 1는 XXX의 채널수, 3은 conv2d(XXX)의 채널수

[<tf.Variable 'conv2d_49/kernel:0' shape=(2, 2, 1, 3) dtype=float32, numpy=
 array([[[[ 0.34987062, -0.42536667, -0.23450106]],
 
         [[-0.15203184, -0.17105693,  0.12885928]]],
 
 
        [[[-0.46592194, -0.14798307,  0.01712328]],
 
         [[-0.09353292, -0.44206303,  0.45532137]]]], dtype=float32)>,
 <tf.Variable 'conv2d_49/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [311]:
np.array(conv2d.weights[0])[...,0].reshape(2,2).sum()

-0.36161608

In [312]:
np.array(conv2d.weights[0])[...,1].reshape(2,2).sum()

-1.1864698

In [313]:
np.array(conv2d.weights[0])[...,2].reshape(2,2).sum()

0.36680287

### test5 

`-` X의 채널도 여러개이고, conv2의 채널도 여러개라면? 

In [344]:
XXX = tnp.array([1]*1*2*2*3,dtype=tf.float64).reshape(1,2,2,3) 
conv2d = tf.keras.layers.Conv2D(4,(2,2))

In [345]:
conv2d(XXX)

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[ 0.04870808,  1.5503743 , -0.5173418 , -0.8040104 ]]]],
      dtype=float32)>

- 입력차원이 (1,2,2,2) / 출력차원이 (1,1,1,3) => conv2d는 (2,2,2)를 (1,1,3)으로 보내는 변환이라 해석할 수 있다. 

In [346]:
conv2d.weights # (2,2)는 커널의 크기, 3는 XXX의 채널수, 4은 conv2d(XXX)의 채널수

[<tf.Variable 'conv2d_52/kernel:0' shape=(2, 2, 3, 4) dtype=float32, numpy=
 array([[[[-0.06062004,  0.27159846, -0.35087395,  0.05619323],
          [ 0.17420346,  0.03172404,  0.10250252, -0.2861783 ],
          [-0.34434512,  0.3421561 ,  0.17365706, -0.10712236]],
 
         [[-0.20626149,  0.265002  , -0.40033156,  0.4335292 ],
          [ 0.01527935,  0.45321858, -0.19586432, -0.3797094 ],
          [ 0.03717214,  0.2208283 ,  0.3757074 ,  0.22027957]]],
 
 
        [[[-0.35246146,  0.4008683 ,  0.06744468, -0.05409959],
          [ 0.41204262, -0.15033433, -0.25883394,  0.4195491 ],
          [ 0.06376296, -0.03911704,  0.30243152, -0.28761363]],
 
         [[ 0.45764613, -0.08449683, -0.2228171 ,  0.03668833],
          [ 0.03148475,  0.29475772, -0.05836084, -0.45254976],
          [-0.17919523, -0.45583105, -0.05200329, -0.4029768 ]]]],
       dtype=float32)>,
 <tf.Variable 'conv2d_52/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [365]:
np.array(conv2d.weights[0])[...,0].sum() # conv2d(X)의 첫채널 

0.04870808

In [366]:
np.array(conv2d.weights[0])[...,1].sum() # conv2d(X)의 두번째 채널 

1.5503743

In [367]:
np.array(conv2d.weights[0])[...,2].sum() # conv2d(X)의 세번째 채널 

-0.51734185

In [368]:
np.array(conv2d.weights[0])[...,3].sum() # conv2d(X)의 네번쨰 채널 

-0.8040104

In [362]:
Rconv = np.array(conv2d.weights[0])[...,0][...,0].sum() # X의 첫번째 채널에 conv
Gconv = np.array(conv2d.weights[0])[...,0][...,1].sum() # X의 두번쨰 채널에 conv 
Bconv = np.array(conv2d.weights[0])[...,0][...,2].sum() # X의 세번째 채널에 conv

In [364]:
Rconv+Gconv+Bconv, np.array(conv2d.weights[0])[...,0].sum() # conv2d(X)의 첫채널 

(0.04870805, 0.04870808)