In [1]:
from fastai.text.all import *

In [2]:
path = untar_data(URLs.HUMAN_NUMBERS)

In [3]:
path.ls()

(#2) [Path('/home/cgb2/.fastai/data/human_numbers/train.txt'),Path('/home/cgb2/.fastai/data/human_numbers/valid.txt')]

In [4]:
lines = L()
with open(path/'train.txt') as f: lines += L(*f.readlines())
with open(path/'valid.txt') as f: lines += L(*f.readlines())

In [5]:
lines

(#9998) ['one \n','two \n','three \n','four \n','five \n','six \n','seven \n','eight \n','nine \n','ten \n'...]

In [292]:
text= 'h e l l o '*100
text

'h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o h e l l o

In [164]:
tokens= text.split(' ')[:-1]

In [293]:
vocab = L(*tokens).unique()
vocab

(#4) ['h','e','l','o']

In [294]:
word2idx = {w:i for i,w in enumerate(vocab)}
word2idx

{'h': 0, 'e': 1, 'l': 2, 'o': 3}

In [296]:
nums= [word2idx[i] for i in tokens]

In [297]:
nums

[0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 1,
 2,
 2,
 3,


In [298]:
[(tokens[i],tokens[i+1]) for i in range(0,4)]

[('h', 'e'), ('e', 'l'), ('l', 'l'), ('l', 'o')]

In [299]:
[(tokens[i:i+2],tokens[i+2]) for i in range(0,3)]

[(['h', 'e'], 'l'), (['e', 'l'], 'l'), (['l', 'l'], 'o')]

- 이전 세단어를 기반으로 다음단어를 예측하자. 

In [284]:
seqs = [(tensor(nums[i:i+3]), nums[i+3]) for i in range(0,len(nums)-4,3)]
seqs

[(tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),


In [285]:
#bs = 64 
cut = int(len(seqs)*0.8)
dls = DataLoaders.from_dsets(seqs[:cut],seqs[cut:],bs=64,shuffle=False)

In [286]:
dls

In [289]:
seqs[:cut]

[(tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),
 (tensor([0, 1, 2]), 2),
 (tensor([2, 3, 0]), 1),
 (tensor([1, 2, 2]), 3),
 (tensor([3, 0, 1]), 2),
 (tensor([2, 2, 3]), 0),


In [255]:
x,y=dls.one_batch()

In [262]:
import torch

In [267]:
len(x[:,0])

64

In [300]:
embdd = torch.nn.Embedding(4,20)

In [283]:
embdd()

tensor([[-0.1576],
        [ 0.1989],
        [ 0.8843],
        [-0.7738],
        [ 0.1989],
        [-0.1576],
        [ 0.1989],
        [ 0.8843],
        [-0.7738],
        [ 0.1989],
        [-0.1576],
        [ 0.1989],
        [ 0.8843],
        [-0.7738],
        [ 0.1989],
        [-0.1576],
        [ 0.1989],
        [ 0.8843],
        [-0.7738],
        [ 0.1989],
        [-0.1576],
        [ 0.1989],
        [ 0.8843],
        [-0.7738],
        [ 0.1989],
        [-0.1576],
        [ 0.1989],
        [ 0.8843],
        [-0.7738],
        [ 0.1989],
        [-0.1576],
        [ 0.1989],
        [ 0.8843],
        [-0.7738],
        [ 0.1989],
        [-0.1576],
        [ 0.1989],
        [ 0.8843],
        [-0.7738],
        [ 0.1989],
        [-0.1576],
        [ 0.1989],
        [ 0.8843],
        [-0.7738],
        [ 0.1989],
        [-0.1576],
        [ 0.1989],
        [ 0.8843],
        [-0.7738],
        [ 0.1989],
        [-0.1576],
        [ 0.1989],
        [ 0.

In [250]:
class LMModel1(Module): 
    def __init__(self, vocab_sz, n_hidden):
        self.i_h = nn.Embedding(vocab_sz,n_hidden)
        self.h_h = nn.Linear(n_hidden,n_hidden)
        self.h_o = nn.Linear(n_hidden,vocab_sz) 
    def forward(self,x):
        h= F.relu(self.h_h(self.i_h(x[:,0])))
        h= h+ self.i_h(x[:,1])
        h= F.relu(self.h_h(h))
        h= h+self.i_h(x[:,2])
        h= F.relu(self.h_h(h))
        return self.h_o(h)

In [251]:
lrnr = Learner(dls, LMModel1(len(vocab),64), loss_func=F.cross_entropy, metrics=accuracy)

In [252]:
lrnr.fit(10)

epoch,train_loss,valid_loss,accuracy,time
0,1.377013,1.259831,0.411765,00:00
1,1.304814,1.133680,0.411765,00:00
2,1.237525,1.016505,0.794118,00:00
3,1.172959,0.907818,0.794118,00:00
4,1.111081,0.808152,0.794118,00:00
5,1.051669,0.715376,0.794118,00:00
6,0.994467,0.627306,1.000000,00:00
7,0.939126,0.544385,1.000000,00:00
8,0.885393,0.466045,1.000000,00:00
9,0.833281,0.393567,1.000000,00:00


In [238]:
x,y = dls.one_batch()

In [242]:
x

tensor([[0, 1, 2],
        [2, 3, 0],
        [1, 2, 2],
        [3, 0, 1],
        [2, 2, 3],
        [0, 1, 2],
        [2, 3, 0],
        [1, 2, 2],
        [3, 0, 1],
        [2, 2, 3],
        [0, 1, 2],
        [2, 3, 0],
        [1, 2, 2],
        [3, 0, 1],
        [2, 2, 3],
        [0, 1, 2],
        [2, 3, 0],
        [1, 2, 2],
        [3, 0, 1],
        [2, 2, 3],
        [0, 1, 2],
        [2, 3, 0],
        [1, 2, 2],
        [3, 0, 1],
        [2, 2, 3],
        [0, 1, 2],
        [2, 3, 0],
        [1, 2, 2],
        [3, 0, 1],
        [2, 2, 3],
        [0, 1, 2],
        [2, 3, 0],
        [1, 2, 2],
        [3, 0, 1],
        [2, 2, 3],
        [0, 1, 2],
        [2, 3, 0],
        [1, 2, 2],
        [3, 0, 1],
        [2, 2, 3],
        [0, 1, 2],
        [2, 3, 0],
        [1, 2, 2],
        [3, 0, 1],
        [2, 2, 3],
        [0, 1, 2],
        [2, 3, 0],
        [1, 2, 2],
        [3, 0, 1],
        [2, 2, 3],
        [0, 1, 2],
        [2, 3, 0],
        [1, 

In [243]:
y

tensor([2, 1, 3, 2, 0, 2, 1, 3, 2, 0, 2, 1, 3, 2, 0, 2, 1, 3, 2, 0, 2, 1, 3, 2,
        0, 2, 1, 3, 2, 0, 2, 1, 3, 2, 0, 2, 1, 3, 2, 0, 2, 1, 3, 2, 0, 2, 1, 3,
        2, 0, 2, 1, 3, 2, 0, 2, 1, 3, 2, 0, 2, 1, 3, 2])

In [246]:
lrnr.model(x)

tensor([[-0.8150, -1.7917,  1.5827,  0.2822],
        [-0.7357,  1.4659, -0.7889, -0.4297],
        [-0.7201, -1.6277, -0.1399,  0.9542],
        [-0.6613, -0.6674,  1.7314, -0.7023],
        [ 1.5952, -0.9948, -0.9767, -0.0061],
        [-0.8150, -1.7917,  1.5827,  0.2822],
        [-0.7357,  1.4659, -0.7889, -0.4297],
        [-0.7201, -1.6277, -0.1399,  0.9542],
        [-0.6613, -0.6674,  1.7314, -0.7023],
        [ 1.5952, -0.9948, -0.9767, -0.0061],
        [-0.8150, -1.7917,  1.5827,  0.2822],
        [-0.7357,  1.4659, -0.7889, -0.4297],
        [-0.7201, -1.6277, -0.1399,  0.9542],
        [-0.6613, -0.6674,  1.7314, -0.7023],
        [ 1.5952, -0.9948, -0.9767, -0.0061],
        [-0.8150, -1.7917,  1.5827,  0.2822],
        [-0.7357,  1.4659, -0.7889, -0.4297],
        [-0.7201, -1.6277, -0.1399,  0.9542],
        [-0.6613, -0.6674,  1.7314, -0.7023],
        [ 1.5952, -0.9948, -0.9767, -0.0061],
        [-0.8150, -1.7917,  1.5827,  0.2822],
        [-0.7357,  1.4659, -0.7889